<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Credit risk with R.</title>
  <meta name="description" content="Credit risk with R." />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="Credit risk with R." />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Credit risk with R." />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="the-merton-model..html"/>
<style type="text/css">
p.abstract{
  text-align: center;
  font-weight: bold;
}
div.abstract{
  margin: auto;
  width: 90%;
}
</style>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="loan-analysis..html"><a href="loan-analysis..html"><i class="fa fa-check"></i><b>1</b> Loan analysis.</a>
<ul>
<li class="chapter" data-level="1.1" data-path="loan-analysis..html"><a href="loan-analysis..html#explore-the-database."><i class="fa fa-check"></i><b>1.1</b> Explore the database.</a></li>
<li class="chapter" data-level="1.2" data-path="loan-analysis..html"><a href="loan-analysis..html#logistic-models."><i class="fa fa-check"></i><b>1.2</b> Logistic models.</a></li>
<li class="chapter" data-level="1.3" data-path="loan-analysis..html"><a href="loan-analysis..html#prediction-and-model-evaluation."><i class="fa fa-check"></i><b>1.3</b> Prediction and model evaluation.</a></li>
<li class="chapter" data-level="1.4" data-path="loan-analysis..html"><a href="loan-analysis..html#the-bank-strategy."><i class="fa fa-check"></i><b>1.4</b> The bank strategy.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="the-merton-model..html"><a href="the-merton-model..html"><i class="fa fa-check"></i><b>2</b> The Merton model.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-merton-model..html"><a href="the-merton-model..html#minimize-a-function-in-r."><i class="fa fa-check"></i><b>2.1</b> Minimize a function in R.</a></li>
<li class="chapter" data-level="2.2" data-path="the-merton-model..html"><a href="the-merton-model..html#applied-example."><i class="fa fa-check"></i><b>2.2</b> Applied example.</a></li>
<li class="chapter" data-level="2.3" data-path="the-merton-model..html"><a href="the-merton-model..html#inside-view-of-the-mertons-model."><i class="fa fa-check"></i><b>2.3</b> Inside view of the Merton’s model.</a></li>
<li class="chapter" data-level="2.4" data-path="the-merton-model..html"><a href="the-merton-model..html#the-probability-of-default-as-a-function-of-some-parameters."><i class="fa fa-check"></i><b>2.4</b> The probability of default as a function of some parameters.</a></li>
<li class="chapter" data-level="2.5" data-path="the-merton-model..html"><a href="the-merton-model..html#got-capital-structure."><i class="fa fa-check"></i><b>2.5</b> GoT: capital structure.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html"><i class="fa fa-check"></i><b>3</b> The Gaussian copula model.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#the-basics."><i class="fa fa-check"></i><b>3.1</b> The basics.</a></li>
<li class="chapter" data-level="3.2" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#introduction-to-example-24.6."><i class="fa fa-check"></i><b>3.2</b> Introduction to example 24.6.</a></li>
<li class="chapter" data-level="3.3" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#one-firm."><i class="fa fa-check"></i><b>3.3</b> One firm.</a></li>
<li class="chapter" data-level="3.4" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#two-firms."><i class="fa fa-check"></i><b>3.4</b> Two firms.</a></li>
<li class="chapter" data-level="3.5" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#ten-firms."><i class="fa fa-check"></i><b>3.5</b> Ten firms.</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="credit-var-example-24.7..html"><a href="credit-var-example-24.7..html"><i class="fa fa-check"></i><b>4</b> Credit VaR example 24.7.</a></li>
<li class="chapter" data-level="" data-path="references..html"><a href="references..html"><i class="fa fa-check"></i>References.</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Credit risk with R.</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Credit risk with R.</h1>
<p class="author multi-author"><em>Dr. Martin Lozano.</em></p>
<address class="author_afil">
<a href="https://mlozanoqf.github.io/" class="uri">https://mlozanoqf.github.io/</a><br>
</address>
<p class="date"><em> Last compiled on: 28/11/2022, 00:42:30.</em></p>
<div class="abstract">
<p class="abstract">Abstract</p>
This material relies on John C. Hull <span class="citation">(Hull 2015)</span> credit risk chapters and Lore Dirick credit risk DataCamp course. Some mathematical background is skipped to emphasize the data analysis, model logic, discussion, graphical approach and R coding. As in the philosophy of Donald Knuth <span class="citation">(Knuth 1984)</span>, the objective of this document is to explain to human beings what we want a computer to do as literate programming. This is a work in progress and it is under revision.
</div>
</div>
<div id="loan-analysis." class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">1</span> Loan analysis.<a href="loan-analysis..html#loan-analysis." class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This section relies on the DataCamp course <em>Credit Risk Modeling in R</em> by Lore Dirick. However, we incorporate a slightly different database and an extended analysis.</p>
<div id="explore-the-database." class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Explore the database.<a href="loan-analysis..html#explore-the-database." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s load the data called <tt><code>loan_data_ARF.rds</code></tt> and then understand its structure. This database is available upon request.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="loan-analysis..html#cb2-1" aria-hidden="true" tabindex="-1"></a>loan_data <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;loan_data_ARF.rds&quot;</span>)</span>
<span id="cb2-2"><a href="loan-analysis..html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(loan_data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    29092 obs. of  10 variables:
##  $ loan_status   : int  0 0 0 0 0 0 1 0 1 0 ...
##  $ loan_amnt     : int  5000 2400 10000 5000 3000 12000 9000 3000 10000 1000 ...
##  $ int_rate      : num  10.6 11 13.5 11 11 ...
##  $ grade         : Factor w/ 7 levels &quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;,..: 2 3 3 1 5 2 3 2 2 4 ...
##  $ emp_length    : int  10 25 13 3 9 11 0 3 3 0 ...
##  $ home_ownership: Factor w/ 4 levels &quot;MORTGAGE&quot;,&quot;OTHER&quot;,..: 4 4 4 4 4 3 4 4 4 4 ...
##  $ annual_inc    : num  24000 12252 49200 36000 48000 ...
##  $ age           : int  33 31 24 39 24 28 22 22 28 22 ...
##  $ sex           : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 2 2 2 2 1 2 ...
##  $ region        : Factor w/ 4 levels &quot;E&quot;,&quot;N&quot;,&quot;S&quot;,&quot;W&quot;: 1 1 3 3 2 2 2 2 4 1 ...</code></pre>
<p>This could be a typical database taken from any given financial institution like a bank or a firm that uses credit channels to sell their products or services. Here, we have 29,092 observations of 10 variables. Each observation corresponds to one individual loan and each variable allow us to understand the individual and the loan characteristics. One important variable, our dependent variable, is <tt><code>loan_status</code></tt> the value of 0 is no default and the value of 1 is default. A default occurs when a borrower is unable to make timely payments, misses payments, or avoids or stops making payments on interest or principal owed. Then, the definition of default depends on the interests and objectives of the analysis. The variable <tt><code>loan_status</code></tt> is dichotomic or categorical. Here, we are interested to predict whether a new application will default or not in the future.</p>
<p>Clearly, <tt><code>loan_data_ARF.rds</code></tt> is past information as we know with certainty whether the individual defaulted (1) or not (0). Past information is helpful to better understand how likely is that one individual may default according to the rest of their variable values. This kind of data could be easily found in most financial firms as they store details about the applicant and its corresponding loan. Past information is useful to train our quantitative models and eventually make predictions of new applicants, and even evaluate our predictions.</p>
<p>We can look at the information in different ways. For example, look at the first 10 rows (out of 29,092) and their corresponding 10 variables.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="loan-analysis..html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(loan_data, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    loan_status loan_amnt int_rate grade emp_length home_ownership annual_inc
## 1            0      5000    10.65     B         10           RENT      24000
## 2            0      2400    10.99     C         25           RENT      12252
## 3            0     10000    13.49     C         13           RENT      49200
## 4            0      5000    10.99     A          3           RENT      36000
## 5            0      3000    10.99     E          9           RENT      48000
## 6            0     12000    12.69     B         11            OWN      75000
## 7            1      9000    13.49     C          0           RENT      30000
## 8            0      3000     9.91     B          3           RENT      15000
## 9            1     10000    10.65     B          3           RENT     100000
## 10           0      1000    16.29     D          0           RENT      28000
##    age sex region
## 1   33   0      E
## 2   31   0      E
## 3   24   0      S
## 4   39   0      S
## 5   24   1      N
## 6   28   1      N
## 7   22   1      N
## 8   22   1      N
## 9   28   0      W
## 10  22   1      E</code></pre>
<p>The <tt><code>CrossTable()</code></tt> function is used in different contexts. Generating tables like this is only one way we can use it. Here, instead of looking the details of the first 10 rows, we summarize with respect to <tt><code>home_ownership</code></tt>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="loan-analysis..html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(loan_data<span class="sc">$</span>home_ownership)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  29092 
## 
##  
##           |  MORTGAGE |     OTHER |       OWN |      RENT | 
##           |-----------|-----------|-----------|-----------|
##           |     12002 |        97 |      2301 |     14692 | 
##           |     0.413 |     0.003 |     0.079 |     0.505 | 
##           |-----------|-----------|-----------|-----------|
## 
## 
## 
## </code></pre>
<p>These tables illustrate the data structure and contents. We can also use two variables instead of one. In particular, instead of counting for home ownership we can add a second dimension like <tt><code>loan_status</code></tt>. This allows us to create more informative tables.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="loan-analysis..html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(loan_data<span class="sc">$</span>home_ownership, loan_data<span class="sc">$</span>loan_status, <span class="at">prop.r =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-2"><a href="loan-analysis..html#cb8-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  29092 
## 
##  
##                          | loan_data$loan_status 
## loan_data$home_ownership |         0 |         1 | Row Total | 
## -------------------------|-----------|-----------|-----------|
##                 MORTGAGE |     10821 |      1181 |     12002 | 
##                          |     0.902 |     0.098 |     0.413 | 
## -------------------------|-----------|-----------|-----------|
##                    OTHER |        80 |        17 |        97 | 
##                          |     0.825 |     0.175 |     0.003 | 
## -------------------------|-----------|-----------|-----------|
##                      OWN |      2049 |       252 |      2301 | 
##                          |     0.890 |     0.110 |     0.079 | 
## -------------------------|-----------|-----------|-----------|
##                     RENT |     12915 |      1777 |     14692 | 
##                          |     0.879 |     0.121 |     0.505 | 
## -------------------------|-----------|-----------|-----------|
##             Column Total |     25865 |      3227 |     29092 | 
## -------------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>This table reveals defaults by home ownership. We can use histograms to see one variable distribution. In this case we have the interest rate distribution.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="loan-analysis..html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loan_data, <span class="fu">aes</span>(<span class="at">x =</span> int_rate)) <span class="sc">+</span> </span>
<span id="cb10-2"><a href="loan-analysis..html#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb10-3"><a href="loan-analysis..html#cb10-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="loan-analysis..html#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb10-5"><a href="loan-analysis..html#cb10-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Interest rate&quot;</span>,</span>
<span id="cb10-6"><a href="loan-analysis..html#cb10-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Interest rate histogram&quot;</span>,</span>
<span id="cb10-7"><a href="loan-analysis..html#cb10-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="loan-analysis..html#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-2-1.png" alt="Interest rate histogram." width="672"  />
<p class="caption">
Figure 1.1: Interest rate histogram.
</p>
</div>
<p>The following is a similar figure for the annual income.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="loan-analysis..html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loan_data, <span class="fu">aes</span>(<span class="at">x =</span> annual_inc)) <span class="sc">+</span> </span>
<span id="cb11-2"><a href="loan-analysis..html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="loan-analysis..html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb11-4"><a href="loan-analysis..html#cb11-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Annual income&quot;</span>,</span>
<span id="cb11-5"><a href="loan-analysis..html#cb11-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Annual income histogram&quot;</span>,</span>
<span id="cb11-6"><a href="loan-analysis..html#cb11-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="loan-analysis..html#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-3-1.png" alt="Annual income histogram." width="672"  />
<p class="caption">
Figure 1.2: Annual income histogram.
</p>
</div>
<p>The histogram looks suspicious. We have a very large values of the annual income in the horizontal axis (6,000,000) and apparently no observations. We can plot the values and explore the data further as the histogram may be hiding something.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="loan-analysis..html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loan_data, <span class="fu">aes</span>(int_rate, annual_inc)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="loan-analysis..html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-3"><a href="loan-analysis..html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Annual income&quot;</span>,</span>
<span id="cb12-4"><a href="loan-analysis..html#cb12-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Interest rate&quot;</span>,</span>
<span id="cb12-5"><a href="loan-analysis..html#cb12-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Annual income inspection.&quot;</span>,</span>
<span id="cb12-6"><a href="loan-analysis..html#cb12-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="loan-analysis..html#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-4-1.png" alt="Annual income inspection." width="672"  />
<p class="caption">
Figure 1.3: Annual income inspection.
</p>
</div>
<p>There are some individuals with a very high income. We should explore further and investigate if this are valid observations or simply a mistake in the original database.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="loan-analysis..html#cb13-1" aria-hidden="true" tabindex="-1"></a>high_income <span class="ot">&lt;-</span> loan_data[(loan_data<span class="sc">$</span>annual_inc <span class="sc">&gt;</span> <span class="dv">1000000</span>), ]</span>
<span id="cb13-2"><a href="loan-analysis..html#cb13-2" aria-hidden="true" tabindex="-1"></a>high_income</span></code></pre></div>
<pre><code>##       loan_status loan_amnt int_rate grade emp_length home_ownership annual_inc
## 4861            0     12025    14.27     C         13           RENT    1782000
## 13931           0     10000     6.54     A         16            OWN    1200000
## 15386           0      1500    10.99     A          5       MORTGAGE    1900000
## 16713           0     12000     7.51     A          1       MORTGAGE    1200000
## 19486           0      5000    12.73     C         12       MORTGAGE    6000000
## 22811           0     10000    10.99     A          1       MORTGAGE    1200000
## 23361           0      6400     7.40     A          7       MORTGAGE    1440000
## 23683           0      6600     7.74     A          9       MORTGAGE    1362000
## 28468           0      8450    12.29     C          0           RENT    2039784
##       age sex region
## 4861   63   0      E
## 13931  36   0      W
## 15386  60   1      N
## 16713  32   0      E
## 19486 144   1      E
## 22811  40   1      E
## 23361  44   1      E
## 23683  47   0      E
## 28468  42   0      E</code></pre>
<p>One guy is not only rich, he is 144 years old. So, my decision is to drop these 9 observations. Cleaning data is a common task when dealing with large databases. This is fine as long as we do not alter the nature of the data.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="loan-analysis..html#cb15-1" aria-hidden="true" tabindex="-1"></a>high_income_index <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value =</span> <span class="fu">as.integer</span>(<span class="fu">rownames</span>(high_income)))</span>
<span id="cb15-2"><a href="loan-analysis..html#cb15-2" aria-hidden="true" tabindex="-1"></a>loan_data <span class="ot">&lt;-</span> loan_data[<span class="sc">-</span>high_income_index<span class="sc">$</span>value,]</span>
<span id="cb15-3"><a href="loan-analysis..html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loan_data, <span class="fu">aes</span>(int_rate, annual_inc)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="loan-analysis..html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a href="loan-analysis..html#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Annual income&quot;</span>,</span>
<span id="cb15-6"><a href="loan-analysis..html#cb15-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Interest rate&quot;</span>,</span>
<span id="cb15-7"><a href="loan-analysis..html#cb15-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Annual income without extreme values.&quot;</span>,</span>
<span id="cb15-8"><a href="loan-analysis..html#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="loan-analysis..html#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-5"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-5-1.png" alt="Annual income without extreme values." width="672"  />
<p class="caption">
Figure 1.4: Annual income without extreme values.
</p>
</div>
<p>Remember the database has originally 29,092 rows and now we are dropping 9 so we end up with 29,083. See the result.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="loan-analysis..html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(loan_data, <span class="fu">aes</span>(<span class="at">x =</span> annual_inc)) <span class="sc">+</span> </span>
<span id="cb16-2"><a href="loan-analysis..html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="loan-analysis..html#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb16-4"><a href="loan-analysis..html#cb16-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Annual income&quot;</span>,</span>
<span id="cb16-5"><a href="loan-analysis..html#cb16-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Annual income histogram second version.&quot;</span>,</span>
<span id="cb16-6"><a href="loan-analysis..html#cb16-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="loan-analysis..html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-6"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-6-1.png" alt="Annual income histogram second version." width="672"  />
<p class="caption">
Figure 1.5: Annual income histogram second version.
</p>
</div>
<p>Somewhat better now.</p>
</div>
<div id="logistic-models." class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Logistic models.<a href="loan-analysis..html#logistic-models." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Logistic models allows us to make predictions about loan defaults. Logistic regression is a statistical model that in its basic form uses a logistic function to model a binary dependent variable like <tt><code>loan_status</code></tt>. In this case, the binary dependent variable is default or no default. A good reference for this section is <span class="citation">Hull (2020)</span>.</p>
<p>First, load the data and split it into two sets: (1) training and (2) test. The training set is for building and estimate models and the test set is used to evaluate our model predictions with new data for our models. This is, when estimating models, it is common practice to separate the available data into two portions, <em>training</em> and <em>test</em> data, where the training data is used to estimate parameters (in-sample) and the test data is used to evaluate its accuracy (out of sample). Because the test data is not used in determining the estimation, it should provide a reliable indication of how well the model is likely to estimate or forecast on new data. In sum, we train the model, we test the model, and once we are OK with the model performance on new data, we are ready to use it in real-life applications. If we ignore this split and use the whole database to produce our models, we may succeed at explaining defaults in our database but we may fail to explain defaults for new loan applications.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="loan-analysis..html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># It is convenient to set the loan_status as factor.</span></span>
<span id="cb17-2"><a href="loan-analysis..html#cb17-2" aria-hidden="true" tabindex="-1"></a>loan_data<span class="sc">$</span>loan_status <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(loan_data<span class="sc">$</span>loan_status)</span>
<span id="cb17-3"><a href="loan-analysis..html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb17-4"><a href="loan-analysis..html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># idea de Pablo Elizondo usar runif del 1 al nrow(loan_data), eso simplificaria el proces. </span></span>
<span id="cb17-5"><a href="loan-analysis..html#cb17-5" aria-hidden="true" tabindex="-1"></a>index_train <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">runif</span>(<span class="dv">1</span> <span class="sc">:</span> <span class="fu">nrow</span>(loan_data), <span class="dv">0</span> , <span class="dv">1</span>), </span>
<span id="cb17-6"><a href="loan-analysis..html#cb17-6" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">:</span> <span class="fu">nrow</span>(loan_data)))</span>
<span id="cb17-7"><a href="loan-analysis..html#cb17-7" aria-hidden="true" tabindex="-1"></a>index_train <span class="ot">&lt;-</span> <span class="fu">order</span>(index_train[, <span class="dv">1</span>])</span>
<span id="cb17-8"><a href="loan-analysis..html#cb17-8" aria-hidden="true" tabindex="-1"></a>index_train <span class="ot">&lt;-</span> index_train[<span class="dv">1</span><span class="sc">:</span> (<span class="dv">2</span><span class="sc">/</span><span class="dv">3</span> <span class="sc">*</span> <span class="fu">nrow</span>(loan_data))]</span>
<span id="cb17-9"><a href="loan-analysis..html#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create training_set</span></span>
<span id="cb17-10"><a href="loan-analysis..html#cb17-10" aria-hidden="true" tabindex="-1"></a>training_set <span class="ot">&lt;-</span> loan_data[index_train, ]</span>
<span id="cb17-11"><a href="loan-analysis..html#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create test_set</span></span>
<span id="cb17-12"><a href="loan-analysis..html#cb17-12" aria-hidden="true" tabindex="-1"></a>test_set <span class="ot">&lt;-</span> loan_data[<span class="sc">-</span>index_train, ]</span></code></pre></div>
<p>We have 29,083 observations in <tt><code>loan_data</code></tt>. The code above randomly selects <span class="math inline">\(29083 \times (2/3)=19388\)</span> rows to form the . The <tt><code>test_set</code></tt> are the remaining <span class="math inline">\(29083-19388=9695\)</span> rows. The random selection is highly recommended as the <tt><code>loan_data</code></tt> may have some structure or sorting that could bias our model estimation and negatively impact our model test. For example, imagine that for some weird reason the database is sorted in such a way that the first observations are all no default. If that is the case, then the training and the test set would not have portions of default and no default cases and we may distort the whole analysis. The random selection allow us to replicate a real situation in which our database is unsorted, with different characteristics.</p>
<p>Take a look of the training set structure.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="loan-analysis..html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># See the data structure.</span></span>
<span id="cb18-2"><a href="loan-analysis..html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(training_set)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    19388 obs. of  10 variables:
##  $ loan_status   : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ loan_amnt     : int  4000 5000 18000 5600 2700 15000 14500 12000 4800 4050 ...
##  $ int_rate      : num  10.2 14.3 18.3 7.9 14.3 ...
##  $ grade         : Factor w/ 7 levels &quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;,..: 2 3 6 1 3 2 1 4 1 1 ...
##  $ emp_length    : int  6 3 10 3 5 10 11 9 1 17 ...
##  $ home_ownership: Factor w/ 4 levels &quot;MORTGAGE&quot;,&quot;OTHER&quot;,..: 4 4 4 4 1 1 1 1 4 1 ...
##  $ annual_inc    : num  26000 280000 121000 32000 88500 75000 97600 57600 92000 75000 ...
##  $ age           : int  27 36 24 22 32 23 23 28 48 31 ...
##  $ sex           : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 2 2 2 1 2 1 1 1 2 1 ...
##  $ region        : Factor w/ 4 levels &quot;E&quot;,&quot;N&quot;,&quot;S&quot;,&quot;W&quot;: 2 2 2 4 2 4 3 4 2 3 ...</code></pre>
<p>Variables as factors are useful for model estimation and data visualization. Factors are variables in R which take on a limited number of different values; such variables are often referred to as categorical variables.</p>
<p>Assume we think that the <tt><code>loan_status</code></tt> depends on the age of the individual. We can estimate a simple logistic model to learn about the relationship between age and loan status.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="loan-analysis..html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting a simple logistic model.</span></span>
<span id="cb20-2"><a href="loan-analysis..html#cb20-2" aria-hidden="true" tabindex="-1"></a>log_model_age <span class="ot">&lt;-</span> <span class="fu">glm</span>(loan_status <span class="sc">~</span> age, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb20-3"><a href="loan-analysis..html#cb20-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> training_set)</span>
<span id="cb20-4"><a href="loan-analysis..html#cb20-4" aria-hidden="true" tabindex="-1"></a>log_model_age</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = loan_status ~ age, family = &quot;binomial&quot;, data = training_set)
## 
## Coefficients:
## (Intercept)          age  
##    -1.90097     -0.00623  
## 
## Degrees of Freedom: 19387 Total (i.e. Null);  19386 Residual
## Null Deviance:       13580 
## Residual Deviance: 13580     AIC: 13580</code></pre>
<p>Apparently, there is a negative relationship between age and loan status. The AIC value (13580) is useful when comparing models. The Akaike information criterion (AIC) is a mathematical method for evaluating how well a model fits the data it was generated from. In statistics, AIC is used to compare different possible models and determine which one is the best fit for the data. At the moment we cannot interpret the AIC simply because we only have one model and we cannot compare it with another AIC.</p>
<p>Let’s estimate another simple model where the interest rate category is used as a predictor of the <tt><code>loan_status</code></tt>. Remember we are not conducting any prediction at all at this moment, we are only estimating models using the training set.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="loan-analysis..html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a glm model with variable int_rate as a predictor.</span></span>
<span id="cb22-2"><a href="loan-analysis..html#cb22-2" aria-hidden="true" tabindex="-1"></a>log_model_ir <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> loan_status <span class="sc">~</span> int_rate, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb22-3"><a href="loan-analysis..html#cb22-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> training_set)</span>
<span id="cb22-4"><a href="loan-analysis..html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the parameter estimates.</span></span>
<span id="cb22-5"><a href="loan-analysis..html#cb22-5" aria-hidden="true" tabindex="-1"></a>log_model_ir</span></code></pre></div>
<pre><code>## 
## Call:  glm(formula = loan_status ~ int_rate, family = &quot;binomial&quot;, data = training_set)
## 
## Coefficients:
## (Intercept)     int_rate  
##      -3.710        0.142  
## 
## Degrees of Freedom: 19387 Total (i.e. Null);  19386 Residual
## Null Deviance:       13580 
## Residual Deviance: 13210     AIC: 13220</code></pre>
<p>The AIC is a lower (13220 versus 13580), so we have a better model now.</p>
<p>Using one single predictor as age or interest rate could be a limited approach. Let’s add some more. Also, let’s introduce the <tt><code>summary()</code></tt> function to extract more information about the model estimation results. The <tt><code>log_model_multi</code></tt> below assumes that the loan status depend on the age, interest rate, grade, loan amount, and annual income.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="loan-analysis..html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple variables in a logistic regression model.</span></span>
<span id="cb24-2"><a href="loan-analysis..html#cb24-2" aria-hidden="true" tabindex="-1"></a>log_model_multi <span class="ot">&lt;-</span> <span class="fu">glm</span>(loan_status <span class="sc">~</span> age <span class="sc">+</span> int_rate <span class="sc">+</span> grade <span class="sc">+</span> <span class="fu">log</span>(loan_amnt) <span class="sc">+</span> </span>
<span id="cb24-3"><a href="loan-analysis..html#cb24-3" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">log</span>(annual_inc) , <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb24-4"><a href="loan-analysis..html#cb24-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> training_set)</span>
<span id="cb24-5"><a href="loan-analysis..html#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain significance levels using summary().</span></span>
<span id="cb24-6"><a href="loan-analysis..html#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model_multi)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = loan_status ~ age + int_rate + grade + log(loan_amnt) + 
##     log(annual_inc), family = &quot;binomial&quot;, data = training_set)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1545  -0.5351  -0.4397  -0.3382   2.6101  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      1.996240   0.477911   4.177 2.95e-05 ***
## age             -0.002302   0.003825  -0.602   0.5473    
## int_rate         0.038767   0.017249   2.247   0.0246 *  
## gradeB           0.503409   0.087435   5.758 8.54e-09 ***
## gradeC           0.748229   0.117765   6.354 2.10e-10 ***
## gradeD           0.964343   0.147283   6.548 5.85e-11 ***
## gradeE           1.033442   0.190817   5.416 6.10e-08 ***
## gradeF           1.619470   0.257900   6.279 3.40e-10 ***
## gradeG           1.867494   0.440232   4.242 2.21e-05 ***
## log(loan_amnt)   0.015718   0.036341   0.433   0.6654    
## log(annual_inc) -0.470748   0.046423 -10.140  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 13579  on 19387  degrees of freedom
## Residual deviance: 13028  on 19377  degrees of freedom
## AIC: 13050
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Our multi-factor model works well. In <tt><code>log_model_multi</code></tt>, the AIC value is the lowest so far (13050 versus 13220), so this should be considered as the best model at the moment. The <tt><code>summary()</code></tt> function shows the significance levels of the estimators, but we are currently more interested in the goodness of fit of the models because we want to conduct predictions about the <tt><code>loan_status</code></tt>. This is, we are interested to use a model to find out whether new applicants in the test set are expected to default or not, rather than in the applicants’ credit risk factors. This is why we are concentrated in AIC now.</p>
<p>When a customer fill out a credit application form, we collect information but we do not know for sure whether she or he will eventually default. A credit risk model can help us in this task.</p>
</div>
<div id="prediction-and-model-evaluation." class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Prediction and model evaluation.<a href="loan-analysis..html#prediction-and-model-evaluation." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s take our three models: <tt><code>log_model_age</code></tt>, <tt><code>log_model_ir</code></tt> and <tt><code>log_model_multi</code></tt> from the previous subsection to carry out a simple prediction exercise. We start by identifying one observation in the test set and ask the models to estimate the <tt><code>loan_status</code></tt>. This is, we take the first guy age, then we apply the <tt><code>log_model_age</code></tt> model, and compare the predicted <tt><code>loan_status</code></tt> with respect to what really happened. Remember we know what really happened with this guy because we have the information in the test set. Every model is expected to produce different <tt><code>loan_status</code></tt> estimates. If the model is good, then the predicted <tt><code>loan_status</code></tt> will match what really happened.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="loan-analysis..html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define one single observation in test_set.</span></span>
<span id="cb26-2"><a href="loan-analysis..html#cb26-2" aria-hidden="true" tabindex="-1"></a>test_case <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(test_set[<span class="dv">1</span>, ])</span>
<span id="cb26-3"><a href="loan-analysis..html#cb26-3" aria-hidden="true" tabindex="-1"></a>test_case</span></code></pre></div>
<pre><code>##   loan_status loan_amnt int_rate grade emp_length home_ownership annual_inc age
## 1           0      5000    10.65     B         10           RENT      24000  33
##   sex region
## 1   0      E</code></pre>
<p>We know in advance that the <tt><code>loan_status</code></tt> of this observation taken from the test set is 0. However, the models cannot know this simply because we did not use the test set to estimate the logistic models. Our models were estimated using the training set. A good credit risk model should estimate a no default given this new applicant.</p>
<p>The values of <tt><code>loan_status</code></tt> in the test set is either 0 or 1. However, the logistic models estimate the <tt><code>loan_status</code></tt> as values in the range of 0 to 1. This mean that we would expect the estimated <tt><code>loan_status</code></tt> to be close to 0. But, how close? We will deal with this issue later.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="loan-analysis..html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the loan status with log_model_age and log_model_ir models.</span></span>
<span id="cb28-2"><a href="loan-analysis..html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Esteban Gonzalez, as.numeric no es realmente necesario. </span></span>
<span id="cb28-3"><a href="loan-analysis..html#cb28-3" aria-hidden="true" tabindex="-1"></a>log_model_age_pred <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(log_model_age, <span class="at">newdata =</span> test_case, </span>
<span id="cb28-4"><a href="loan-analysis..html#cb28-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">type =</span> <span class="st">&quot;response&quot;</span>))</span>
<span id="cb28-5"><a href="loan-analysis..html#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember the test_case is only one observation (one row).</span></span>
<span id="cb28-6"><a href="loan-analysis..html#cb28-6" aria-hidden="true" tabindex="-1"></a>log_model_ir_pred <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(log_model_ir, <span class="at">newdata =</span> test_case, </span>
<span id="cb28-7"><a href="loan-analysis..html#cb28-7" aria-hidden="true" tabindex="-1"></a>                              <span class="at">type =</span> <span class="st">&quot;response&quot;</span>))</span>
<span id="cb28-8"><a href="loan-analysis..html#cb28-8" aria-hidden="true" tabindex="-1"></a>log_model_multi_pred <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(log_model_multi, <span class="at">newdata =</span> test_case, </span>
<span id="cb28-9"><a href="loan-analysis..html#cb28-9" aria-hidden="true" tabindex="-1"></a>                              <span class="at">type =</span> <span class="st">&quot;response&quot;</span>))</span>
<span id="cb28-10"><a href="loan-analysis..html#cb28-10" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">&quot;log_model_age&quot;</span>   <span class="ot">=</span> log_model_age_pred, </span>
<span id="cb28-11"><a href="loan-analysis..html#cb28-11" aria-hidden="true" tabindex="-1"></a>                     <span class="st">&quot;log_model_ir&quot;</span>    <span class="ot">=</span> log_model_ir_pred, </span>
<span id="cb28-12"><a href="loan-analysis..html#cb28-12" aria-hidden="true" tabindex="-1"></a>                     <span class="st">&quot;log_model_multi&quot;</span> <span class="ot">=</span> log_model_multi_pred)</span>
<span id="cb28-13"><a href="loan-analysis..html#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(predictions) <span class="ot">&lt;-</span> <span class="st">&quot;predictions of a known no-default&quot;</span></span>
<span id="cb28-14"><a href="loan-analysis..html#cb28-14" aria-hidden="true" tabindex="-1"></a>predictions</span></code></pre></div>
<pre><code>##                 predictions of a known no-default
## log_model_age                          0.10846236
## log_model_ir                           0.09996702
## log_model_multi                        0.14461840</code></pre>
<p>These values are low as they are close to 0. We could interpret this as a certain ability of the models to predict this single case from the test set. However, several questions remains unanswered and requires further analysis. For example: How can we determine if the prediction is low enough to consider it as a non-default? We may need a cut-off value to decide. We will explore this issue later.</p>
<p>Another aspect is: What about the rest of the cases in the test set? We have 9,695 observations in the test set and in the example above we only test for the first one. We are interested in the entire test set, not only for one observation. Fortunately, this issue is easy to address as we only need to change the parameter in the function. In particular, instead of (which is one observation) we can change it to (which is the entire 9,695 test set).</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="loan-analysis..html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the loan status with the three models.</span></span>
<span id="cb30-2"><a href="loan-analysis..html#cb30-2" aria-hidden="true" tabindex="-1"></a>pred_log_model_age <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_age, <span class="at">newdata =</span> test_set, </span>
<span id="cb30-3"><a href="loan-analysis..html#cb30-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb30-4"><a href="loan-analysis..html#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Now newdata = test_set so we are testing all the test set observations.</span></span>
<span id="cb30-5"><a href="loan-analysis..html#cb30-5" aria-hidden="true" tabindex="-1"></a>pred_log_model_ir <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_ir, <span class="at">newdata =</span> test_set, </span>
<span id="cb30-6"><a href="loan-analysis..html#cb30-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb30-7"><a href="loan-analysis..html#cb30-7" aria-hidden="true" tabindex="-1"></a>pred_log_model_multi <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_multi, <span class="at">newdata =</span> test_set, </span>
<span id="cb30-8"><a href="loan-analysis..html#cb30-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb30-9"><a href="loan-analysis..html#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co"># The range of the estimated loan status.</span></span>
<span id="cb30-10"><a href="loan-analysis..html#cb30-10" aria-hidden="true" tabindex="-1"></a>log_model_age_predall <span class="ot">&lt;-</span> <span class="fu">range</span>(pred_log_model_age)</span>
<span id="cb30-11"><a href="loan-analysis..html#cb30-11" aria-hidden="true" tabindex="-1"></a>log_model_ir_predall <span class="ot">&lt;-</span> <span class="fu">range</span>(pred_log_model_ir)</span>
<span id="cb30-12"><a href="loan-analysis..html#cb30-12" aria-hidden="true" tabindex="-1"></a>log_model_multi_predall <span class="ot">&lt;-</span> <span class="fu">range</span>(pred_log_model_multi)</span>
<span id="cb30-13"><a href="loan-analysis..html#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="loan-analysis..html#cb30-14" aria-hidden="true" tabindex="-1"></a>predictions_2 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">&quot;log_model_age&quot;</span>   <span class="ot">=</span> log_model_age_predall, </span>
<span id="cb30-15"><a href="loan-analysis..html#cb30-15" aria-hidden="true" tabindex="-1"></a>                       <span class="st">&quot;log_model_ir&quot;</span>    <span class="ot">=</span> log_model_ir_predall,</span>
<span id="cb30-16"><a href="loan-analysis..html#cb30-16" aria-hidden="true" tabindex="-1"></a>                       <span class="st">&quot;log_model_multi&quot;</span> <span class="ot">=</span> log_model_multi_predall)</span>
<span id="cb30-17"><a href="loan-analysis..html#cb30-17" aria-hidden="true" tabindex="-1"></a>aic <span class="ot">&lt;-</span> <span class="fu">rbind</span>(log_model_age<span class="sc">$</span>aic, log_model_ir<span class="sc">$</span>aic, log_model_multi<span class="sc">$</span>aic)</span>
<span id="cb30-18"><a href="loan-analysis..html#cb30-18" aria-hidden="true" tabindex="-1"></a>predictions_2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(predictions_2, aic)</span>
<span id="cb30-19"><a href="loan-analysis..html#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(predictions_2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;lower value&quot;</span>, <span class="st">&quot;higer value&quot;</span>, <span class="st">&quot;AIC&quot;</span>)</span>
<span id="cb30-20"><a href="loan-analysis..html#cb30-20" aria-hidden="true" tabindex="-1"></a>predictions_2</span></code></pre></div>
<pre><code>##                 lower value higer value      AIC
## log_model_age    0.08417892   0.1165453 13580.65
## log_model_ir     0.05019756   0.3982977 13215.61
## log_model_multi  0.01739107   0.4668004 13050.30</code></pre>
<p>Now, instead of the prediction of one single applicant we have conducted a prediction of all 9,695 observations in the test set. The lower value column corresponds to the lower predicted <tt><code>loan_status</code></tt> for each model. The logistic models produce values in the range of zero to one, and in this case the ranges are rather narrow.</p>
<p>Narrow ranges (the difference between higher and lower <tt><code>loan_status</code></tt> predicted values) could be problematic because the model could not be able to differentiate between defaults (predictions closer to 1) and no-defaults (predictions closer to 0). The higher AIC corresponds to the worst model and the lower AIC to the best model. Here, we can see some consistency because the best model according to the AIC, corresponds to the model with the higher prediction range.</p>
<p>Let’s explore all the predicted <tt><code>loan_status</code></tt> values for the <tt><code>log_model_age</code></tt>:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="loan-analysis..html#cb32-1" aria-hidden="true" tabindex="-1"></a>pred_log_model_age_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pred_log_model_age)</span>
<span id="cb32-2"><a href="loan-analysis..html#cb32-2" aria-hidden="true" tabindex="-1"></a>pred_log_model_age_plot <span class="ot">&lt;-</span> <span class="fu">gather</span>(pred_log_model_age_plot)</span>
<span id="cb32-3"><a href="loan-analysis..html#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="loan-analysis..html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_log_model_age_plot, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> key)) <span class="sc">+</span> </span>
<span id="cb32-5"><a href="loan-analysis..html#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="loan-analysis..html#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb32-7"><a href="loan-analysis..html#cb32-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Default prediction&quot;</span>,</span>
<span id="cb32-8"><a href="loan-analysis..html#cb32-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Age model prediction histogram.&quot;</span>,</span>
<span id="cb32-9"><a href="loan-analysis..html#cb32-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Very limited prediction range.&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-10"><a href="loan-analysis..html#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-7-1.png" alt="Age model prediction histogram." width="672"  />
<p class="caption">
Figure 1.6: Age model prediction histogram.
</p>
</div>
<p>The <tt><code>log_model_age</code></tt> fails to predict values ranging from 0 to 1. In fact, these values are quite concentrated in a very small range of values. As a consequence, this model fails to differentiate between default and no default predictions.</p>
<p>Let’s visualize the predictions of the <tt><code>log_model_ir</code></tt> and <tt><code>log_model_multi</code></tt>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="loan-analysis..html#cb33-1" aria-hidden="true" tabindex="-1"></a>pred_ir_multi <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(pred_log_model_ir,</span>
<span id="cb33-2"><a href="loan-analysis..html#cb33-2" aria-hidden="true" tabindex="-1"></a>                                   pred_log_model_multi))</span>
<span id="cb33-3"><a href="loan-analysis..html#cb33-3" aria-hidden="true" tabindex="-1"></a>pred_ir_multi <span class="ot">&lt;-</span> <span class="fu">gather</span>(pred_ir_multi)</span>
<span id="cb33-4"><a href="loan-analysis..html#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="loan-analysis..html#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_ir_multi, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> key)) <span class="sc">+</span> </span>
<span id="cb33-6"><a href="loan-analysis..html#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="loan-analysis..html#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb33-8"><a href="loan-analysis..html#cb33-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Default prediction&quot;</span>,</span>
<span id="cb33-9"><a href="loan-analysis..html#cb33-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Interest rate and multi models predictions histograms.&quot;</span>,</span>
<span id="cb33-10"><a href="loan-analysis..html#cb33-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Multi model performs somewhat better.&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-11"><a href="loan-analysis..html#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-8-1.png" alt="Interest rate and multi models predictions histograms." width="672"  />
<p class="caption">
Figure 1.7: Interest rate and multi models predictions histograms.
</p>
</div>
<p>Looks better, but not quite. Presumably, a model which considers all available predictors could be better for predicting the <tt><code>loan_status</code></tt>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="loan-analysis..html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logistic regression model using all available predictors in the data set.</span></span>
<span id="cb34-2"><a href="loan-analysis..html#cb34-2" aria-hidden="true" tabindex="-1"></a>log_model_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(loan_status <span class="sc">~</span> age <span class="sc">+</span> int_rate <span class="sc">+</span> grade <span class="sc">+</span> <span class="fu">log</span>(loan_amnt) <span class="sc">+</span> </span>
<span id="cb34-3"><a href="loan-analysis..html#cb34-3" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">log</span>(annual_inc) <span class="sc">+</span> emp_length <span class="sc">+</span> home_ownership <span class="sc">+</span> sex <span class="sc">+</span></span>
<span id="cb34-4"><a href="loan-analysis..html#cb34-4" aria-hidden="true" tabindex="-1"></a>                      region, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="at">data =</span> training_set)</span>
<span id="cb34-5"><a href="loan-analysis..html#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co">#glm(loan_status ~ ., family = &quot;binomial&quot;, data = training_set)</span></span>
<span id="cb34-6"><a href="loan-analysis..html#cb34-6" aria-hidden="true" tabindex="-1"></a>                  </span>
<span id="cb34-7"><a href="loan-analysis..html#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Loan status predictions for all test set elements.</span></span>
<span id="cb34-8"><a href="loan-analysis..html#cb34-8" aria-hidden="true" tabindex="-1"></a>predictions_all_full <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model_full, <span class="at">newdata =</span> test_set, </span>
<span id="cb34-9"><a href="loan-analysis..html#cb34-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb34-10"><a href="loan-analysis..html#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the predictions range.</span></span>
<span id="cb34-11"><a href="loan-analysis..html#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(predictions_all_full)</span></code></pre></div>
<pre><code>## [1] 1.422469e-09 8.544424e-01</code></pre>
<p>Now, the range is wider. A wider range means that the <tt><code>loan_status</code></tt> estimates are now closer to 1. This is good because we need the model to be able to predict both no-defaults (0) and defaults (1). Let’s see a prediction comparisons of <tt><code>log_model_multi</code></tt> and .</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="loan-analysis..html#cb36-1" aria-hidden="true" tabindex="-1"></a>predictions_multi_full <span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(pred_log_model_multi, </span>
<span id="cb36-2"><a href="loan-analysis..html#cb36-2" aria-hidden="true" tabindex="-1"></a>                                             predictions_all_full))</span>
<span id="cb36-3"><a href="loan-analysis..html#cb36-3" aria-hidden="true" tabindex="-1"></a>predictions_multi_full <span class="ot">&lt;-</span> <span class="fu">gather</span>(predictions_multi_full)</span>
<span id="cb36-4"><a href="loan-analysis..html#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="loan-analysis..html#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predictions_multi_full, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> key)) <span class="sc">+</span> </span>
<span id="cb36-6"><a href="loan-analysis..html#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="loan-analysis..html#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb36-8"><a href="loan-analysis..html#cb36-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Default prediction&quot;</span>,</span>
<span id="cb36-9"><a href="loan-analysis..html#cb36-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Multi and full models predictions histograms.&quot;</span>,</span>
<span id="cb36-10"><a href="loan-analysis..html#cb36-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Full model performs somewhat better.&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-11"><a href="loan-analysis..html#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-10-1.png" alt="Multi and full models predictions histograms." width="672"  />
<p class="caption">
Figure 1.8: Multi and full models predictions histograms.
</p>
</div>
<p>The model predictions looks better than the other models.</p>
<p>Another question is: How can we know these model predictions corresponds to a default or no default? The loan status predictions go from 0 to 0.854 for the case of the model. At the end, these loan status estimations need to be interpreted or classified as a default or no default because we are interested on that. Are they closer enough to 0 to consider a no default? This issue is addressed by setting up a cut-off rate so we can split all estimated loan status into 0 or 1.</p>
<p>Let’s arbitrarily consider a cutoff of 0.15 for now. This mean that every estimated loan status below 0.15 will be considered as 0 (no-default), and every estimated loan status above 0.15 will be considered as 1 (default). Graphically it looks like this:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="loan-analysis..html#cb37-1" aria-hidden="true" tabindex="-1"></a>pred_log_model_full <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(predictions_all_full)</span>
<span id="cb37-2"><a href="loan-analysis..html#cb37-2" aria-hidden="true" tabindex="-1"></a>pred_log_model_full <span class="ot">&lt;-</span> <span class="fu">gather</span>(pred_log_model_full)</span>
<span id="cb37-3"><a href="loan-analysis..html#cb37-3" aria-hidden="true" tabindex="-1"></a>pred_log_model_full <span class="ot">&lt;-</span> <span class="fu">mutate</span>(pred_log_model_full, </span>
<span id="cb37-4"><a href="loan-analysis..html#cb37-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">def =</span> <span class="fu">ifelse</span>(value <span class="sc">&lt;</span> <span class="fl">0.15</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb37-5"><a href="loan-analysis..html#cb37-5" aria-hidden="true" tabindex="-1"></a>pred_log_model_full<span class="sc">$</span>def <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(pred_log_model_full<span class="sc">$</span>def)</span>
<span id="cb37-6"><a href="loan-analysis..html#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="loan-analysis..html#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_log_model_full, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> key)) <span class="sc">+</span> </span>
<span id="cb37-8"><a href="loan-analysis..html#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">adjust =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb37-9"><a href="loan-analysis..html#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.15</span>, <span class="at">linetype =</span> <span class="st">&quot;longdash&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="loan-analysis..html#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb37-11"><a href="loan-analysis..html#cb37-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Default prediction&quot;</span>,</span>
<span id="cb37-12"><a href="loan-analysis..html#cb37-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Full model prediction histogram.&quot;</span>,</span>
<span id="cb37-13"><a href="loan-analysis..html#cb37-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;A cutoff of 0.15.&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-14"><a href="loan-analysis..html#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-11-1.png" alt="Full model prediction histogram." width="672"  />
<p class="caption">
Figure 1.9: Full model prediction histogram.
</p>
</div>
<p>Here, predicted <tt><code>loan_status</code></tt> values at the left of the dashed line represent no default and values at the right of the dashed line represent default. Let’s set up the rule to convert the estimated loan status into a binary variable 0 or 1. See how this transformation takes place:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="loan-analysis..html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a binary predictions-vector using a cut-off of 15%</span></span>
<span id="cb38-2"><a href="loan-analysis..html#cb38-2" aria-hidden="true" tabindex="-1"></a>pred_cutoff_15 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions_all_full <span class="sc">&gt;</span> <span class="fl">0.15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb38-3"><a href="loan-analysis..html#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">cbind</span>(predictions_all_full, pred_cutoff_15))</span></code></pre></div>
<pre><code>##    predictions_all_full pred_cutoff_15
## 1          1.357995e-08              0
## 2          2.986278e-08              0
## 18         2.299645e-02              0
## 26         2.403879e-01              1
## 27         1.778986e-01              1
## 28         2.600172e-02              0</code></pre>
<p>These are only the first 6 rows not all of them available in the test set. We can see that the rule works as expected because every estimated loan status below 0.15 is now considered as 0 (no-default), and every estimated loan status above 0.15 is considered as 1 (default). The table above show how we can create this binary variable given the logistic model prediction.</p>
<p>Note that the rows numbers in the table above are 1, 2, 18, 26, 27 and 28. These are not 1, 2, 3, 4, 5 and 6 because the <tt><code>test_set</code></tt> rows were selected randomly out of the <tt><code>loan_data</code></tt>. So, the row numbers in the table above correspond to the original place in <tt><code>loan_data</code></tt>.</p>
<p>Is a good model after all? We can add a new column to the previous table. This new variable represents what really happened with the loan. Then, the first column is the logistic model prediction, the second column the transformed binary variable given a cutoff of 0.15, and the third column is what actually happened (default or no-default).</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="loan-analysis..html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let&#39;s take from rows 101 to 110.</span></span>
<span id="cb40-2"><a href="loan-analysis..html#cb40-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">cbind</span>(predictions_all_full, pred_cutoff_15, </span>
<span id="cb40-3"><a href="loan-analysis..html#cb40-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">as.data.frame.numeric</span>(test_set<span class="sc">$</span>loan_status)))[<span class="dv">101</span><span class="sc">:</span><span class="dv">110</span>,]</span></code></pre></div>
<pre><code>##     predictions_all_full pred_cutoff_15 test_set$loan_status
## 308         1.537106e-01              1                    0
## 309         4.137654e-02              0                    0
## 310         3.113926e-02              0                    0
## 312         5.186962e-09              0                    0
## 318         5.337092e-02              0                    0
## 319         8.402239e-02              0                    0
## 323         2.795535e-01              1                    1
## 328         5.384112e-09              0                    0
## 329         1.893745e-01              1                    0
## 330         9.012136e-03              0                    0</code></pre>
<p>Let’s take a sample of 10 observations to conduct the comparison easily. Note that the model correctly predict a no default in most cases. Rows 308 and 329 predict a default incorrectly and row 323 predict a default correctly. There is an easy way to evaluate the rest of the cases in the test set using a simple table called confusion matrix.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="loan-analysis..html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct a confusion matrix.</span></span>
<span id="cb42-2"><a href="loan-analysis..html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(test_set<span class="sc">$</span>loan_status, pred_cutoff_15)</span></code></pre></div>
<pre><code>##    pred_cutoff_15
##        0    1
##   0 6554 2081
##   1  308  752</code></pre>
<p>The model predicts 6,554 of no-defaults correctly and 752 defaults correctly. However, the model predicts 2,081 defaults that are in fact no-defaults and 308 no-defaults that are in fact defaults. How good are these results? Which of these four values is more important? These are questions we address later. For now, we can say that different models and different cut-off rates lead to different confusion matrix results. Please note that adding all these values leads to 9,695 which are the number of observations in the test set.</p>
<p>You may want to see relative and not absolute values. Let’s try the <tt><code>CrossTable()</code></tt> function instead.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="loan-analysis..html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(test_set<span class="sc">$</span>loan_status, pred_cutoff_15, <span class="at">prop.r =</span> <span class="cn">TRUE</span>,</span>
<span id="cb44-2"><a href="loan-analysis..html#cb44-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  9695 
## 
##  
##                      | pred_cutoff_15 
## test_set$loan_status |         0 |         1 | Row Total | 
## ---------------------|-----------|-----------|-----------|
##                    0 |      6554 |      2081 |      8635 | 
##                      |     0.759 |     0.241 |     0.891 | 
## ---------------------|-----------|-----------|-----------|
##                    1 |       308 |       752 |      1060 | 
##                      |     0.291 |     0.709 |     0.109 | 
## ---------------------|-----------|-----------|-----------|
##         Column Total |      6862 |      2833 |      9695 | 
## ---------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>This table is more informative. The model correctly predicts no-defaults in 75.9% of all the observed no-default cases. In other words, the model fails to predict no-default in 24.1% of the total no-default cases. Now the default. The model correctly predicts the default in 70.9% of all the observed default cases (not bad), and fails to predict default in 29.1% of the total default cases.</p>
<p>Instead of arbitrarily consider a cutoff of 0.15, we can follow a different approach. Now consider that we are interested in taking the 20% highest estimates (closer to 1) of as default. Equivalently, this is to take the lowest 80% estimates (closer to 0) as no-default. Let’s calculate the new cut-off that meets this new criterion.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="loan-analysis..html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cutoff definition.</span></span>
<span id="cb46-2"><a href="loan-analysis..html#cb46-2" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fu">quantile</span>(predictions_all_full, <span class="fl">0.8</span>)</span>
<span id="cb46-3"><a href="loan-analysis..html#cb46-3" aria-hidden="true" tabindex="-1"></a>cutoff</span></code></pre></div>
<pre><code>##       80% 
## 0.1994621</code></pre>
<p>This new approach (taking the 20% highest estimates of as default) represent a cut-off of 0.1994621. Graphically:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="loan-analysis..html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred_log_model_full, <span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">fill =</span> key)) <span class="sc">+</span> </span>
<span id="cb48-2"><a href="loan-analysis..html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">adjust =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="loan-analysis..html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> cutoff, <span class="at">linetype =</span> <span class="st">&quot;longdash&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-4"><a href="loan-analysis..html#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb48-5"><a href="loan-analysis..html#cb48-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Default prediction&quot;</span>,</span>
<span id="cb48-6"><a href="loan-analysis..html#cb48-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Full model prediction histogram.&quot;</span>,</span>
<span id="cb48-7"><a href="loan-analysis..html#cb48-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;A cutoff of 0.1994621.&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-8"><a href="loan-analysis..html#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-13-1.png" alt="Full model prediction histogram new cutoff." width="672"  />
<p class="caption">
Figure 1.10: Full model prediction histogram new cutoff.
</p>
</div>
<p>Now the cut-off is 0.1994621. This splits the loan status predictions into two parts: higher than the cut-off is a default, and lower than the cutoff is a no-default. Taking the lowest 80% estimates (closer to 0) as no-default is an arbitrary decision. Here are the cut-off values depending on this arbitrary decision.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="loan-analysis..html#cb49-1" aria-hidden="true" tabindex="-1"></a>cutoff_all <span class="ot">&lt;-</span> <span class="fu">quantile</span>(predictions_all_full, <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="fl">0.1</span>))</span>
<span id="cb49-2"><a href="loan-analysis..html#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(cutoff_all)</span></code></pre></div>
<pre><code>##        cutoff_all
## 10%  1.168657e-08
## 20%  1.468925e-02
## 30%  2.410243e-02
## 40%  3.750625e-02
## 50%  6.183830e-02
## 60%  9.617009e-02
## 70%  1.467331e-01
## 80%  1.994621e-01
## 90%  2.922731e-01
## 100% 8.544424e-01</code></pre>
<p>We can show a similar summary table as we did with the cutoff of 0.15. Here, we show the predictive ability of the model and new cut-off of 0.1994621.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="loan-analysis..html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the predictions with the same model and new cutoff.</span></span>
<span id="cb51-2"><a href="loan-analysis..html#cb51-2" aria-hidden="true" tabindex="-1"></a>pred_full_20 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions_all_full <span class="sc">&gt;</span> cutoff, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb51-3"><a href="loan-analysis..html#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Show results in a confusion matrix.</span></span>
<span id="cb51-4"><a href="loan-analysis..html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(test_set<span class="sc">$</span>loan_status, pred_full_20, <span class="at">prop.r =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-5"><a href="loan-analysis..html#cb51-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  9695 
## 
##  
##                      | pred_full_20 
## test_set$loan_status |         0 |         1 | Row Total | 
## ---------------------|-----------|-----------|-----------|
##                    0 |      7309 |      1326 |      8635 | 
##                      |     0.846 |     0.154 |     0.891 | 
## ---------------------|-----------|-----------|-----------|
##                    1 |       447 |       613 |      1060 | 
##                      |     0.422 |     0.578 |     0.109 | 
## ---------------------|-----------|-----------|-----------|
##         Column Total |      7756 |      1939 |      9695 | 
## ---------------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>With a cutoff of 0.1994621 we accept 7,309 + 447 applications as those are the ones that the model predicts a no default. We can compare both confusion matrix:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="loan-analysis..html#cb53-1" aria-hidden="true" tabindex="-1"></a>cat <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;correct no-default&quot;</span>, <span class="st">&quot;false default&quot;</span>, </span>
<span id="cb53-2"><a href="loan-analysis..html#cb53-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;false no-default&quot;</span>, <span class="st">&quot;correct default&quot;</span>)</span>
<span id="cb53-3"><a href="loan-analysis..html#cb53-3" aria-hidden="true" tabindex="-1"></a>cut_15 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.759</span>, <span class="fl">0.241</span>, <span class="fl">0.291</span>, <span class="fl">0.709</span>)</span>
<span id="cb53-4"><a href="loan-analysis..html#cb53-4" aria-hidden="true" tabindex="-1"></a>cut_19 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.846</span>, <span class="fl">0.154</span>, <span class="fl">0.422</span>, <span class="fl">0.578</span>)</span>
<span id="cb53-5"><a href="loan-analysis..html#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(cat, cut_15, cut_19)</span></code></pre></div>
<pre><code>##      cat                  cut_15  cut_19 
## [1,] &quot;correct no-default&quot; &quot;0.759&quot; &quot;0.846&quot;
## [2,] &quot;false default&quot;      &quot;0.241&quot; &quot;0.154&quot;
## [3,] &quot;false no-default&quot;   &quot;0.291&quot; &quot;0.422&quot;
## [4,] &quot;correct default&quot;    &quot;0.709&quot; &quot;0.578&quot;</code></pre>
<p>The new cut-off of 0.1994621 improves the identification of no-defaults but worsen the identification of default. Also, the new cut-off fails less in the default and fails more in the no-default. Apparently there is some sort of trade-off here.</p>
<p>We can also look the detail of 0.1994621 cut-off. Comparing two columns, the one in the left with the actual loan status, and the right column with the estimated loan status.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="loan-analysis..html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparative table in detail.</span></span>
<span id="cb55-2"><a href="loan-analysis..html#cb55-2" aria-hidden="true" tabindex="-1"></a>true_and_predval <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(test_set<span class="sc">$</span>loan_status, pred_full_20,</span>
<span id="cb55-3"><a href="loan-analysis..html#cb55-3" aria-hidden="true" tabindex="-1"></a>                                     test_set<span class="sc">$</span>loan_status<span class="sc">==</span>pred_full_20)</span>
<span id="cb55-4"><a href="loan-analysis..html#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Show some values.</span></span>
<span id="cb55-5"><a href="loan-analysis..html#cb55-5" aria-hidden="true" tabindex="-1"></a>true_and_predval[<span class="dv">131</span><span class="sc">:</span><span class="dv">140</span>,]</span></code></pre></div>
<pre><code>##     test_set$loan_status pred_full_20 test_set$loan_status == pred_full_20
## 398                    0            0                                 TRUE
## 399                    1            1                                 TRUE
## 404                    0            1                                FALSE
## 414                    0            0                                 TRUE
## 417                    1            1                                 TRUE
## 419                    0            0                                 TRUE
## 420                    0            0                                 TRUE
## 425                    1            1                                 TRUE
## 431                    0            0                                 TRUE
## 435                    0            0                                 TRUE</code></pre>
<p>In this sample the model fails in 1 out of 10 individuals. Not bad at all. Let’s imagine we are a bank. We have a total of 9,695 applications for a loan in our desk (or computer). Assume we use the predictions from to decide whether we accept a loan application or not. Our model-based acceptance rule is the following: if then the model estimates a no-default and we accept the loan application. According to the extract of table above, we fortunately reject application 399, 417 and 425 because that was indeed a default. However, we reject application 404 incorrectly because it did not default. In principle, having a model as a base for a decision rule can lead to better results that guessing or a random approval rule.</p>
<p>Let’s count how many applications are accepted and rejected according to our rule.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="loan-analysis..html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accepted.</span></span>
<span id="cb57-2"><a href="loan-analysis..html#cb57-2" aria-hidden="true" tabindex="-1"></a>accept_20 <span class="ot">&lt;-</span> <span class="fu">sum</span>(pred_full_20 <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb57-3"><a href="loan-analysis..html#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Rejected.</span></span>
<span id="cb57-4"><a href="loan-analysis..html#cb57-4" aria-hidden="true" tabindex="-1"></a>reject_20 <span class="ot">&lt;-</span> <span class="fu">sum</span>(pred_full_20 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb57-5"><a href="loan-analysis..html#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(accept_20, reject_20)</span></code></pre></div>
<pre><code>##   accept_20 reject_20
## 1      7756      1939</code></pre>
<p>Taking the 20% highest estimates of as default and the lowest 80% as no-default mean that by construction, we accept 7,756 loan applications (80% of the total) and reject 1,939 (20% of the total). Then, the criterion determines the number of accepted applications and the model determines which applications to accept/reject.</p>
<p>We can evaluate our loan application rule as we have the corresponding real values in <tt><code>loan_status</code></tt>.</p>
<p>First, let’s illustrate the decision making process given the model estimates.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="loan-analysis..html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First 10 accept decisions.</span></span>
<span id="cb59-2"><a href="loan-analysis..html#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(true_and_predval[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], </span>
<span id="cb59-3"><a href="loan-analysis..html#cb59-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">decision =</span> </span>
<span id="cb59-4"><a href="loan-analysis..html#cb59-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(true_and_predval<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">0</span>, </span>
<span id="cb59-5"><a href="loan-analysis..html#cb59-5" aria-hidden="true" tabindex="-1"></a>                         <span class="st">&quot;accept&quot;</span>, <span class="st">&quot;reject&quot;</span>)), <span class="dv">12</span>)</span></code></pre></div>
<pre><code>##    test_set.loan_status pred_full_20 decision
## 1                     0            0   accept
## 2                     0            0   accept
## 18                    1            0   accept
## 26                    0            1   reject
## 27                    0            0   accept
## 28                    0            0   accept
## 30                    0            0   accept
## 32                    0            0   accept
## 34                    0            1   reject
## 35                    0            0   accept
## 36                    0            0   accept
## 37                    1            0   accept</code></pre>
<p>We can add an evaluation column.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="loan-analysis..html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First 10 accept decisions.</span></span>
<span id="cb61-2"><a href="loan-analysis..html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(true_and_predval[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">decision =</span> </span>
<span id="cb61-3"><a href="loan-analysis..html#cb61-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ifelse</span>(true_and_predval<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&quot;accept&quot;</span>, <span class="st">&quot;reject&quot;</span>),</span>
<span id="cb61-4"><a href="loan-analysis..html#cb61-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">evaluation =</span> <span class="fu">ifelse</span>(true_and_predval<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb61-5"><a href="loan-analysis..html#cb61-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">&quot;we rejected a good customer&quot;</span>, </span>
<span id="cb61-6"><a href="loan-analysis..html#cb61-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="fu">ifelse</span>(true_and_predval<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span></span>
<span id="cb61-7"><a href="loan-analysis..html#cb61-7" aria-hidden="true" tabindex="-1"></a>  true_and_predval<span class="sc">$</span><span class="st">`</span><span class="at">test_set$loan_status</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">0</span>,</span>
<span id="cb61-8"><a href="loan-analysis..html#cb61-8" aria-hidden="true" tabindex="-1"></a>                       <span class="st">&quot;good decision&quot;</span>, <span class="st">&quot;bad decision&quot;</span>))), <span class="dv">12</span>)</span></code></pre></div>
<pre><code>##    test_set.loan_status pred_full_20 decision                  evaluation
## 1                     0            0   accept               good decision
## 2                     0            0   accept               good decision
## 18                    1            0   accept                bad decision
## 26                    0            1   reject we rejected a good customer
## 27                    0            0   accept               good decision
## 28                    0            0   accept               good decision
## 30                    0            0   accept               good decision
## 32                    0            0   accept               good decision
## 34                    0            1   reject we rejected a good customer
## 35                    0            0   accept               good decision
## 36                    0            0   accept               good decision
## 37                    1            0   accept                bad decision</code></pre>
<p>Here we have the first 10 accepted loan applications. A good decision is because we accept the loan that did not default. A bad decision is because we accept the loan application and defaulted. We also have some cases in which we rejected a good customer and that is not good.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="loan-analysis..html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We accept loans that the model predicts a no-default (0).</span></span>
<span id="cb63-2"><a href="loan-analysis..html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># In &quot;accepted_loans&quot; we know whether the accepted loans are in fact</span></span>
<span id="cb63-3"><a href="loan-analysis..html#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co"># default or no-default.</span></span>
<span id="cb63-4"><a href="loan-analysis..html#cb63-4" aria-hidden="true" tabindex="-1"></a>accepted_loans <span class="ot">&lt;-</span> true_and_predval[pred_full_20 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb63-5"><a href="loan-analysis..html#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The code above says: if we accept the application, tell me what happened.</span></span>
<span id="cb63-6"><a href="loan-analysis..html#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(accepted_loans, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] 0 0 1 0 0 0 0 0 0 1
## Levels: 0 1</code></pre>
<p>Here we have the first 10 accepted loans. We fail at the third (which is row 18) and the tenth (which is row 37) as the previous table indicates.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="loan-analysis..html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bad_rate is the proportion of accepted loans that are in fact default.</span></span>
<span id="cb65-2"><a href="loan-analysis..html#cb65-2" aria-hidden="true" tabindex="-1"></a>bad_rate <span class="ot">&lt;-</span> <span class="fu">sum</span>(accepted_loans <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">length</span>(accepted_loans)</span>
<span id="cb65-3"><a href="loan-analysis..html#cb65-3" aria-hidden="true" tabindex="-1"></a>bad_rate</span></code></pre></div>
<pre><code>## [1] 0.0576328</code></pre>
<p>This is, by following the model-based rule, we accepted 7,756 loan applications that represent 80% of the total applications. However, 5.76% of those accepted applications were in fact a default. In particular, we accepted 447 loans that are defaults so: <span class="math inline">\(447/7756=0.0576328\)</span>.</p>
<p>Models are not perfect but we are always interested to find out a good model that leads to a lower bad rate because we do not want to accept many defaults. If we keep the same model and the test set the same, we could reduce this 5.76% by being more strict in the loan application which in simple terms mean to reduce the acceptance rate. This alternative could be controversial as a lower acceptance rate represents lower income (less customers) for the bank or financial firm. In any case, consider we reduce the acceptance rate from 80% to 65% so we can evaluate the impact over the bad rate.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="loan-analysis..html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># New cutoff value.</span></span>
<span id="cb67-2"><a href="loan-analysis..html#cb67-2" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fu">quantile</span>(predictions_all_full, <span class="fl">0.65</span>)</span>
<span id="cb67-3"><a href="loan-analysis..html#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the predictions_all_full into a binary variable.</span></span>
<span id="cb67-4"><a href="loan-analysis..html#cb67-4" aria-hidden="true" tabindex="-1"></a>pred_full_35 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions_all_full <span class="sc">&gt;</span> cutoff, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb67-5"><a href="loan-analysis..html#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co"># A data frame with real and predicted loan status.</span></span>
<span id="cb67-6"><a href="loan-analysis..html#cb67-6" aria-hidden="true" tabindex="-1"></a>true_and_predval <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(test_set<span class="sc">$</span>loan_status, pred_full_35)</span>
<span id="cb67-7"><a href="loan-analysis..html#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Loans that we accept given these new rules.</span></span>
<span id="cb67-8"><a href="loan-analysis..html#cb67-8" aria-hidden="true" tabindex="-1"></a>accepted_loans <span class="ot">&lt;-</span> true_and_predval[pred_full_35 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb67-9"><a href="loan-analysis..html#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Bad rate (accepted loan applications that are defaults).</span></span>
<span id="cb67-10"><a href="loan-analysis..html#cb67-10" aria-hidden="true" tabindex="-1"></a>bad_rate <span class="ot">&lt;-</span> <span class="fu">sum</span>(accepted_loans <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">length</span>(accepted_loans)</span>
<span id="cb67-11"><a href="loan-analysis..html#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the bad rate.</span></span>
<span id="cb67-12"><a href="loan-analysis..html#cb67-12" aria-hidden="true" tabindex="-1"></a>bad_rate</span></code></pre></div>
<pre><code>## [1] 0.03713107</code></pre>
<p>As expected, the bad rate is lower (from 5.76%% to 3.71%). This is, the lower the acceptance rate the lower the bad rate. In the extreme, if we accept 0 loan applications then our bad rate would be zero, but doing so is equivalent as going out of business. We can create a function such that given a vector of prediction of loan status we can return the bad rate for different cutoff values. This could be useful to build the <em>bank strategy</em> more easily. This function will reveal the trade-off between the acceptance rate and the bad rate. In particular, the lower the acceptance rate, the lower the income (bad thing) and the lower the bad rate (good thing). So, which combination is the optimal?</p>
</div>
<div id="the-bank-strategy." class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> The bank strategy.<a href="loan-analysis..html#the-bank-strategy." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A bank could be interested to understand the relationship between the acceptance rate and the bad rate given a model that predicts the loan status.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="loan-analysis..html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function.</span></span>
<span id="cb69-2"><a href="loan-analysis..html#cb69-2" aria-hidden="true" tabindex="-1"></a>strategy_bank <span class="ot">&lt;-</span> <span class="cf">function</span>(prob_of_def){</span>
<span id="cb69-3"><a href="loan-analysis..html#cb69-3" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">21</span>)</span>
<span id="cb69-4"><a href="loan-analysis..html#cb69-4" aria-hidden="true" tabindex="-1"></a>bad_rate <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">21</span>)</span>
<span id="cb69-5"><a href="loan-analysis..html#cb69-5" aria-hidden="true" tabindex="-1"></a>accept_rate <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="at">by =</span> <span class="sc">-</span><span class="fl">0.05</span>)</span>
<span id="cb69-6"><a href="loan-analysis..html#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">21</span>){</span>
<span id="cb69-7"><a href="loan-analysis..html#cb69-7" aria-hidden="true" tabindex="-1"></a>  cutoff[i] <span class="ot">&lt;-</span> <span class="fu">quantile</span>(prob_of_def, accept_rate[i])</span>
<span id="cb69-8"><a href="loan-analysis..html#cb69-8" aria-hidden="true" tabindex="-1"></a>  pred_i <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prob_of_def <span class="sc">&gt;</span> cutoff[i], <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb69-9"><a href="loan-analysis..html#cb69-9" aria-hidden="true" tabindex="-1"></a>  pred_as_good <span class="ot">&lt;-</span> test_set<span class="sc">$</span>loan_status[pred_i <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb69-10"><a href="loan-analysis..html#cb69-10" aria-hidden="true" tabindex="-1"></a>  bad_rate[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(pred_as_good <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">length</span>(pred_as_good)}</span>
<span id="cb69-11"><a href="loan-analysis..html#cb69-11" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">cbind</span>(accept_rate, <span class="at">cutoff =</span> <span class="fu">round</span>(cutoff, <span class="dv">4</span>), </span>
<span id="cb69-12"><a href="loan-analysis..html#cb69-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">bad_rate =</span> <span class="fu">round</span>(bad_rate, <span class="dv">4</span>))</span>
<span id="cb69-13"><a href="loan-analysis..html#cb69-13" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(<span class="fu">list</span>(<span class="at">table =</span> table, <span class="at">bad_rate =</span> bad_rate, </span>
<span id="cb69-14"><a href="loan-analysis..html#cb69-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">accept_rate =</span> accept_rate, <span class="at">cutoff =</span> cutoff))</span>
<span id="cb69-15"><a href="loan-analysis..html#cb69-15" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>We can evaluate this function for the and a bad model like the <tt><code>log_model_age</code></tt>. In principle, we expect the model to have a more attractive relationship between the acceptance rate and the bad rate. This is, lower bad rates for a given acceptance rate. Any financial institution could be interested in increasing the acceptance rate without increasing too much the bad rate.</p>
<p>Let’s apply the function to the and the <tt><code>log_model_age</code></tt>.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="loan-analysis..html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the strategy_bank function.</span></span>
<span id="cb70-2"><a href="loan-analysis..html#cb70-2" aria-hidden="true" tabindex="-1"></a>strategy_predictions_all_full <span class="ot">&lt;-</span> </span>
<span id="cb70-3"><a href="loan-analysis..html#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">strategy_bank</span>(<span class="fu">as.numeric</span>(predictions_all_full))</span>
<span id="cb70-4"><a href="loan-analysis..html#cb70-4" aria-hidden="true" tabindex="-1"></a>strategy_pred_log_model <span class="ot">&lt;-</span> <span class="fu">strategy_bank</span>(<span class="fu">as.numeric</span>(pred_log_model_age))</span>
<span id="cb70-5"><a href="loan-analysis..html#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">accept_rate =</span> strategy_pred_log_model<span class="sc">$</span>accept_rate,</span>
<span id="cb70-6"><a href="loan-analysis..html#cb70-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">log_model_bad_rate =</span> strategy_pred_log_model<span class="sc">$</span>bad_rate, </span>
<span id="cb70-7"><a href="loan-analysis..html#cb70-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">full_model_bad_rate =</span> strategy_predictions_all_full<span class="sc">$</span>bad_rate)</span></code></pre></div>
<pre><code>##    accept_rate log_model_bad_rate full_model_bad_rate
## 1         1.00         0.10933471         0.109334709
## 2         0.95         0.10849715         0.090662324
## 3         0.90         0.10849715         0.076790831
## 4         0.85         0.10849715         0.066626214
## 5         0.80         0.10547397         0.057632800
## 6         0.75         0.10547397         0.050612020
## 7         0.70         0.10396251         0.043619216
## 8         0.65         0.10396251         0.037131070
## 9         0.60         0.10092961         0.029396596
## 10        0.55         0.10092961         0.023443361
## 11        0.50         0.09933775         0.021039604
## 12        0.45         0.10206865         0.018565207
## 13        0.40         0.10206865         0.015471893
## 14        0.35         0.09907039         0.011788977
## 15        0.30         0.09972041         0.009281540
## 16        0.25         0.10343554         0.005363036
## 17        0.20         0.09722922         0.003610108
## 18        0.15         0.09360190         0.001374570
## 19        0.10         0.10125362         0.000000000
## 20        0.05         0.10516605         0.000000000
## 21        0.00         0.00000000         0.000000000</code></pre>
<p>The full model is superior because at any acceptance rate we can reach a lower bad rate. A plot can reveal the main differences of these two models: and <tt><code>log_model_age</code></tt>.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="loan-analysis..html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the strategy functions</span></span>
<span id="cb72-2"><a href="loan-analysis..html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb72-3"><a href="loan-analysis..html#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(strategy_predictions_all_full<span class="sc">$</span>accept_rate,</span>
<span id="cb72-4"><a href="loan-analysis..html#cb72-4" aria-hidden="true" tabindex="-1"></a>     strategy_predictions_all_full<span class="sc">$</span>bad_rate, </span>
<span id="cb72-5"><a href="loan-analysis..html#cb72-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Acceptance rate&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Bad rate&quot;</span>, </span>
<span id="cb72-6"><a href="loan-analysis..html#cb72-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">main =</span> <span class="st">&quot;log_model_full&quot;</span>)</span>
<span id="cb72-7"><a href="loan-analysis..html#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> strategy_predictions_all_full[[<span class="st">&quot;accept_rate&quot;</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb72-8"><a href="loan-analysis..html#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> strategy_predictions_all_full[[<span class="st">&quot;bad_rate&quot;</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb72-9"><a href="loan-analysis..html#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> strategy_predictions_all_full[[<span class="st">&quot;accept_rate&quot;</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, </span>
<span id="cb72-10"><a href="loan-analysis..html#cb72-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb72-11"><a href="loan-analysis..html#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> strategy_predictions_all_full[[<span class="st">&quot;bad_rate&quot;</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, </span>
<span id="cb72-12"><a href="loan-analysis..html#cb72-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb72-13"><a href="loan-analysis..html#cb72-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(strategy_pred_log_model<span class="sc">$</span>accept_rate, </span>
<span id="cb72-14"><a href="loan-analysis..html#cb72-14" aria-hidden="true" tabindex="-1"></a>     strategy_pred_log_model<span class="sc">$</span>bad_rate,</span>
<span id="cb72-15"><a href="loan-analysis..html#cb72-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Acceptance rate&quot;</span>, </span>
<span id="cb72-16"><a href="loan-analysis..html#cb72-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Bad rate&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">main =</span> <span class="st">&quot;log_model_age&quot;</span>)</span>
<span id="cb72-17"><a href="loan-analysis..html#cb72-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> strategy_pred_log_model[[<span class="st">&quot;accept_rate&quot;</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb72-18"><a href="loan-analysis..html#cb72-18" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> strategy_pred_log_model[[<span class="st">&quot;bad_rate&quot;</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb72-19"><a href="loan-analysis..html#cb72-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> strategy_pred_log_model[[<span class="st">&quot;accept_rate&quot;</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb72-20"><a href="loan-analysis..html#cb72-20" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> strategy_pred_log_model[[<span class="st">&quot;bad_rate&quot;</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="SUMMARY_files/figure-html/unnamed-chunk-14-1.png" alt="A good and a bad model." width="672"  />
<p class="caption">
Figure 1.11: A good and a bad model.
</p>
</div>
<p>The model is better because for any acceptance rate we can reach a lower bad rate compared with the <tt><code>log_model_age</code></tt>. This is because the model can identify defaults and no defaults with higher precision compared with the <tt><code>log_model_age</code></tt>. The value of a good model is that it can help us to make better business decisions, in this case better credit evaluation decisions.</p>
<p>The model ability to predict defaults and no defaults can be measured by the AUC. The AUC can be defined as the probability that the fit model will score a randomly drawn positive sample higher than a randomly drawn negative sample. AUC stands for area under the curve in the following context:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="loan-analysis..html#cb73-1" aria-hidden="true" tabindex="-1"></a>ROC_all_full <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_set<span class="sc">$</span>loan_status, predictions_all_full)</span>
<span id="cb73-2"><a href="loan-analysis..html#cb73-2" aria-hidden="true" tabindex="-1"></a>ROC_log_model <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_set<span class="sc">$</span>loan_status, pred_log_model_age)</span>
<span id="cb73-3"><a href="loan-analysis..html#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the ROCs on one plot</span></span>
<span id="cb73-4"><a href="loan-analysis..html#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ROC_all_full, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Full model in red, age model in blue&quot;</span>) </span>
<span id="cb73-5"><a href="loan-analysis..html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ROC_log_model, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="SUMMARY_files/figure-html/unnamed-chunk-15-1.png" width="672"  /></p>
<p>Sensitivity is the model ability to correctly identify defaults, these are known as true positive. Specificity is the model ability to correctly identify no-default loans, these are known as true negative.</p>
<p>As expected, the area under the curve (AUC) is higher for the red line which corresponds to the model. We can calculate the exact values:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="loan-analysis..html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the AUCs</span></span>
<span id="cb74-2"><a href="loan-analysis..html#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(ROC_all_full)</span></code></pre></div>
<pre><code>## Area under the curve: 0.8213</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="loan-analysis..html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(ROC_log_model)</span></code></pre></div>
<pre><code>## Area under the curve: 0.5301</code></pre>
<p>Note that the <tt><code>log_model_age</code></tt> has an AUC of 0.5301. This is close to a loan approval process in which we randomly accept and reject with no further analysis. In other words, the <tt><code>log_model_age</code></tt> is so bad that it is almost equivalent as using no model at all and accept and reject loan applications based on a random rule. A pure-random approval rule would look like this:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="loan-analysis..html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2020</span>)</span>
<span id="cb78-2"><a href="loan-analysis..html#cb78-2" aria-hidden="true" tabindex="-1"></a>pred_rand_model <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fu">length</span>(pred_log_model_age))</span>
<span id="cb78-3"><a href="loan-analysis..html#cb78-3" aria-hidden="true" tabindex="-1"></a>ROC_rand <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_set<span class="sc">$</span>loan_status, pred_rand_model)</span>
<span id="cb78-4"><a href="loan-analysis..html#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the ROCs on one plot</span></span>
<span id="cb78-5"><a href="loan-analysis..html#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ROC_rand, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Random rule model.&quot;</span>)</span></code></pre></div>
<p><img src="SUMMARY_files/figure-html/unnamed-chunk-16-1.png" width="672"  /></p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="loan-analysis..html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(ROC_rand)</span></code></pre></div>
<pre><code>## Area under the curve: 0.5105</code></pre>
<p>In theory, this random evaluation process would lead to an AUC of <span class="math inline">\(0.5 = (1 \times 1)/2\)</span>. In contrast, now imagine we have a perfect model:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="loan-analysis..html#cb81-1" aria-hidden="true" tabindex="-1"></a>pred_perfect_model <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(test_set<span class="sc">$</span>loan_status)</span>
<span id="cb81-2"><a href="loan-analysis..html#cb81-2" aria-hidden="true" tabindex="-1"></a>ROC_perfect <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_set<span class="sc">$</span>loan_status, pred_perfect_model)</span>
<span id="cb81-3"><a href="loan-analysis..html#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ROC_perfect, <span class="at">main =</span> <span class="st">&quot;Perfect model.&quot;</span>)</span></code></pre></div>
<p><img src="SUMMARY_files/figure-html/unnamed-chunk-17-1.png" width="672"  /></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="loan-analysis..html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(ROC_perfect)</span></code></pre></div>
<pre><code>## Area under the curve: 1</code></pre>
<p>In a perfect model, the AUC is equal to 1 (<span class="math inline">\(1 \times 1\)</span>). The model correctly identify defaults (100% sensitivity) and at the same time the model correctly identify no-defaults (100% specificity)</p>
<div style="page-break-after: always;"></div>
</div>
</div>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3RFWK4ZPH8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-3RFWK4ZPH8');
</script>
            </section>

          </div>
        </div>
      </div>

<a href="the-merton-model..html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
