<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.54">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Martín Lozano.">

<title>Credit risk with  R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Logistic_files/libs/clipboard/clipboard.min.js"></script>
<script src="Logistic_files/libs/quarto-html/quarto.js"></script>
<script src="Logistic_files/libs/quarto-html/popper.min.js"></script>
<script src="Logistic_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Logistic_files/libs/quarto-html/anchor.min.js"></script>
<link href="Logistic_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Logistic_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="Logistic_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="Logistic_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Logistic_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Logistic_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="Logistic_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="Logistic_files/libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="Logistic_files/libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<style>html{ scroll-behavior: smooth; }</style>






  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <style>

    #btn-back-to-top {

      position: fixed;

      bottom: 20px;

      right: 20px;

      width: 15px; /* Adjust the width */

      height: 15px; /* Adjust the height */

      box-sizing: content-box;

      z-index: 1000;

      background-color: rgba(0, 123, 255, 0.7);

      border: none;

      color: white;

      display: flex;

      align-items: center;

      justify-content: center;

    }

  </style>

</head>

<body>



<button type="button" class="btn btn-primary btn-lg bi bi-arrow-up" id="btn-back-to-top"></button>



<script>

  let backToTopButton = document.getElementById("btn-back-to-top");



  backToTopButton.addEventListener("click", function () {

    document.documentElement.scrollTop = 0;

  });

</script>







<div id="progress-bar" style="width: 0%; height:2px; background-color: rgb(89 127 235);; position: fixed; top: 0px; z-index: 2000;"></div>



<script id="progressbar" type="text/javascript">



document.addEventListener("DOMContentLoaded", function() {



    const bar = document.querySelector('#progress-bar');

    const post = document.querySelector('#quarto-content');

    const html = document.documentElement;

    

    const height = post.scrollHeight + post.offsetTop;

    

    window.addEventListener('scroll', () => {

        bar.style.width = (html.scrollTop / (height- html.clientHeight)) * 100 + '%';

    });

});

</script>
<link href="Logistic_files/libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">




<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction." id="toc-introduction." class="nav-link active" data-scroll-target="#introduction.">Introduction.</a></li>
  <li><a href="#loan-analysis." id="toc-loan-analysis." class="nav-link" data-scroll-target="#loan-analysis."><span class="header-section-number">1</span> Loan analysis.</a>
  <ul class="collapse">
  <li><a href="#explore-the-database." id="toc-explore-the-database." class="nav-link" data-scroll-target="#explore-the-database."><span class="header-section-number">1.1</span> Explore the database.</a></li>
  <li><a href="#logistic-models." id="toc-logistic-models." class="nav-link" data-scroll-target="#logistic-models."><span class="header-section-number">1.2</span> Logistic models.</a></li>
  <li><a href="#prediction-and-model-evaluation." id="toc-prediction-and-model-evaluation." class="nav-link" data-scroll-target="#prediction-and-model-evaluation."><span class="header-section-number">1.3</span> Prediction and model evaluation.</a></li>
  <li><a href="#the-bank-strategy." id="toc-the-bank-strategy." class="nav-link" data-scroll-target="#the-bank-strategy."><span class="header-section-number">1.4</span> The bank strategy.</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Credit risk with <i class="fa-brands fa-r-project" aria-label="r-project"></i> <span style="color:white">R</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta column-page-right">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Martín Lozano. </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">December 25, 2024, 02:55:43 am.</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    This material relies on <span class="citation" data-cites="Hull">Hull (<a href="#ref-Hull" role="doc-biblioref">2015</a>)</span> credit risk chapters and Lore Dirick credit risk DataCamp course. Some mathematical background is skipped to emphasize the data analysis, model logic, discussion, graphical approach and R coding <span class="citation" data-cites="Rref">(<a href="#ref-Rref" role="doc-biblioref">R Core Team 2024</a>)</span>. As in the philosophy of <span class="citation" data-cites="knuth1984literate">Knuth (<a href="#ref-knuth1984literate" role="doc-biblioref">1984</a>)</span>, the objective of this document is to explain to human beings what we want a computer to do as literate programming. This is a work in progress and it is under revision.
  </div>
</div>


</header>


<section id="introduction." class="level1 unnumbered">
<h1 class="unnumbered">Introduction.</h1>
<p>Credit risk models play a pivotal role in the financial landscape, providing institutions with a systematic framework to assess and manage the risks associated with lending and investment activities. One crucial component of these models is the estimation of the probability of default, which quantifies the likelihood that a borrower will fail to meet their debt obligations. The relevance of credit risk models lies in their ability to enhance decision-making processes by offering a comprehensive understanding of the potential creditworthiness of individuals, companies, or financial instruments. By utilizing statistical methods, historical data, and various financial indicators, these models enable financial institutions to make informed decisions about lending, pricing, and portfolio management. The estimation of the probability of default not only aids in risk assessment but also supports regulatory compliance, allowing institutions to maintain a healthy balance between risk and return in their credit portfolios. In an ever-evolving financial landscape, the continual refinement and application of credit risk models are essential for fostering stability and resilience within the financial system.</p>
</section>
<section id="loan-analysis." class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Loan analysis.</h1>
<p>The main objective of this section is to predict whether a person or client applying for a loan will repay it or not. This issue can be considered a classification problem, where based on information about the client and the characteristics of their loan application, the client is classified into one of two categories: whether they will default or not. There are various ways to approach this classification problem; in this section, we will use a simple machine learning model called logistic regression. The model is first estimated or trained and then evaluated using new data to determine how well it performs the classification.</p>
<p>Let’s load the required R packages first.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># Logistic models</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(gmodels) <span class="co"># CrossTable()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gmodels' was built under R version 4.4.2</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">library</span>(tidyr) <span class="co"># gather()</span></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">library</span>(pROC) <span class="co"># roc</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pROC' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'pROC'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:gmodels':

    ci</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">library</span>(vembedr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This section relies on the DataCamp course <em>Credit Risk Modeling in R</em> by Lore Dirick. However, we incorporate a slightly different database and an extended analysis.</p>
<section id="explore-the-database." class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="explore-the-database."><span class="header-section-number">1.1</span> Explore the database.</h2>
<p>Let’s load the data called <tt><code>loan_data_ARF.rds</code></tt> and then understand its structure before conducting any further analysis. This database is available <a href="https://github.com/mlozanoqf/tutorial_arf/blob/main/loan_data_ARF.rds">here</a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"loan_data_ARF.rds"</span>)</span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="fu">str</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   29092 obs. of  10 variables:
 $ loan_status   : int  0 0 0 0 0 0 1 0 1 0 ...
 $ loan_amnt     : int  5000 2400 10000 5000 3000 12000 9000 3000 10000 1000 ...
 $ int_rate      : num  10.6 11 13.5 11 11 ...
 $ grade         : Factor w/ 7 levels "A","B","C","D",..: 2 3 3 1 5 2 3 2 2 4 ...
 $ emp_length    : int  10 25 13 3 9 11 0 3 3 0 ...
 $ home_ownership: Factor w/ 4 levels "MORTGAGE","OTHER",..: 4 4 4 4 4 3 4 4 4 4 ...
 $ annual_inc    : num  24000 12252 49200 36000 48000 ...
 $ age           : int  33 31 24 39 24 28 22 22 28 22 ...
 $ sex           : Factor w/ 2 levels "0","1": 1 1 1 1 2 2 2 2 1 2 ...
 $ region        : Factor w/ 4 levels "E","N","S","W": 1 1 3 3 2 2 2 2 4 1 ...</code></pre>
</div>
</div>
<p>This dataset could represent a typical collection of data from a financial institution, such as a bank or a company that uses credit channels to sell its products or services. It contains 29,092 observations across 10 variables. Each observation corresponds to the personal and loan characteristics of an individual loan.</p>
<p>A key variable, our dependent variable, is <code>loan_st</code>, which indicates loan status. A value of 0 represents no default, while a value of 1 represents default. A default occurs when a borrower fails to make timely payments, misses payments, or ceases payments on the interest or principal owed. The definition of default can vary depending on the goals and interests of the analysis. For the purposes of this study, we classify loans simply as either default or no default.</p>
<p>The variable <code>loan_st</code> is dichotomous, or categorical. Our primary interest lies in predicting whether a new loan application will result in default or not.</p>
<p>Clearly, <code>loan_data_ARF.rds</code> represents past information, as we know with certainty whether an individual defaulted (1) or not (0). Historical data is valuable for understanding how likely an individual is to default based on their personal and loan characteristics. It is also essential for training quantitative models to predict outcomes for new applicants and for evaluating the performance of our classifications.</p>
<p>A variable name is considered too long when a shorter name can convey the same purpose just as effectively. Let’s rename some of them.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>old_names <span class="ot">&lt;-</span> <span class="fu">colnames</span>(dat)</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">colnames</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"loan_st"</span>, <span class="st">"l_amnt"</span>, <span class="st">"int"</span>, <span class="st">"grade"</span>, <span class="st">"emp_len"</span>, </span>
<span id="cb16-3"><a href="#cb16-3"></a>                   <span class="st">"home"</span>, <span class="st">"income"</span>, <span class="st">"age"</span>, <span class="st">"sex"</span>, <span class="st">"region"</span>)</span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="fu">data.frame</span>(old_names, <span class="st">"new_names"</span> <span class="ot">=</span> <span class="fu">colnames</span>(dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        old_names new_names
1     loan_status   loan_st
2       loan_amnt    l_amnt
3        int_rate       int
4           grade     grade
5      emp_length   emp_len
6  home_ownership      home
7      annual_inc    income
8             age       age
9             sex       sex
10         region    region</code></pre>
</div>
</div>
<p>New variable names have now been assigned.</p>
<p>We can take a look at the information in different ways. For example, look at the first 10 rows out of 29,092.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">head</span>(dat, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   loan_st l_amnt   int grade emp_len home income age sex region
1        0   5000 10.65     B      10 RENT  24000  33   0      E
2        0   2400 10.99     C      25 RENT  12252  31   0      E
3        0  10000 13.49     C      13 RENT  49200  24   0      S
4        0   5000 10.99     A       3 RENT  36000  39   0      S
5        0   3000 10.99     E       9 RENT  48000  24   1      N
6        0  12000 12.69     B      11  OWN  75000  28   1      N
7        1   9000 13.49     C       0 RENT  30000  22   1      N
8        0   3000  9.91     B       3 RENT  15000  22   1      N
9        1  10000 10.65     B       3 RENT 100000  28   0      W
10       0   1000 16.29     D       0 RENT  28000  22   1      E</code></pre>
</div>
</div>
<p>Note that <tt><code>sex</code></tt> is 1 for female and 0 for male. Now, instead of looking the details of the first 10 rows, we can summarize with respect to <tt><code>home</code></tt> with the <tt><code>CrossTable()</code></tt> function.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">CrossTable</span>(dat<span class="sc">$</span>home)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|         N / Table Total |
|-------------------------|

 
Total Observations in Table:  29092 

 
          |  MORTGAGE |     OTHER |       OWN |      RENT | 
          |-----------|-----------|-----------|-----------|
          |     12002 |        97 |      2301 |     14692 | 
          |     0.413 |     0.003 |     0.079 |     0.505 | 
          |-----------|-----------|-----------|-----------|



 </code></pre>
</div>
</div>
<p>We can also use <tt><code>CrossTable()</code></tt> to summarize two variables. In particular, instead of counting for home ownership we can add a second dimension like <tt><code>loan_st</code></tt>. This allows us to create more informative tables.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">CrossTable</span>(dat<span class="sc">$</span>home, dat<span class="sc">$</span>loan_st, <span class="at">prop.r =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-2"><a href="#cb22-2"></a>           <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Row Total |
|-------------------------|

 
Total Observations in Table:  29092 

 
             | dat$loan_st 
    dat$home |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
    MORTGAGE |     10821 |      1181 |     12002 | 
             |     0.902 |     0.098 |     0.413 | 
-------------|-----------|-----------|-----------|
       OTHER |        80 |        17 |        97 | 
             |     0.825 |     0.175 |     0.003 | 
-------------|-----------|-----------|-----------|
         OWN |      2049 |       252 |      2301 | 
             |     0.890 |     0.110 |     0.079 | 
-------------|-----------|-----------|-----------|
        RENT |     12915 |      1777 |     14692 | 
             |     0.879 |     0.121 |     0.505 | 
-------------|-----------|-----------|-----------|
Column Total |     25865 |      3227 |     29092 | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>This table reveals defaults by home ownership. We can use histograms to see one variable distribution. In this case we have the interest rate distribution.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> int)) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">colour =</span> <span class="st">"black"</span>, </span>
<span id="cb24-3"><a href="#cb24-3"></a>                 <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Interest rate"</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-irh" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-irh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-irh-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-irh-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Interest rate histogram.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The following is a dotplot figure for the annual income.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(income)) <span class="sc">+</span> </span>
<span id="cb26-2"><a href="#cb26-2"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binwidth =</span> <span class="dv">100000</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb26-4"><a href="#cb26-4"></a>       <span class="at">x =</span> <span class="st">"Annual income"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-aib" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-aib-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Annual income dotplot.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <a href="#fig-aib" class="quarto-xref">Figure&nbsp;1.2</a> above appears suspicious. The horizontal axis shows a very large annual income value (6,000,000). Additionally, there are only a few individuals with extremely high incomes. We should investigate further to determine whether these are valid observations or errors in the original dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>high_income <span class="ot">&lt;-</span> dat[(dat<span class="sc">$</span>income <span class="sc">&gt;</span> <span class="dv">1000000</span>), ]</span>
<span id="cb27-2"><a href="#cb27-2"></a>high_income</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      loan_st l_amnt   int grade emp_len     home  income age sex region
4861        0  12025 14.27     C      13     RENT 1782000  63   0      E
13931       0  10000  6.54     A      16      OWN 1200000  36   0      W
15386       0   1500 10.99     A       5 MORTGAGE 1900000  60   1      N
16713       0  12000  7.51     A       1 MORTGAGE 1200000  32   0      E
19486       0   5000 12.73     C      12 MORTGAGE 6000000 144   1      E
22811       0  10000 10.99     A       1 MORTGAGE 1200000  40   1      E
23361       0   6400  7.40     A       7 MORTGAGE 1440000  44   1      E
23683       0   6600  7.74     A       9 MORTGAGE 1362000  47   0      E
28468       0   8450 12.29     C       0     RENT 2039784  42   0      E</code></pre>
</div>
</div>
<p>One individual (ID 19486) is not only extremely wealthy but also 144 years old. As a result, I have decided to remove these nine observations. Data cleaning is a common task when working with large datasets, and it is acceptable as long as the integrity of the data remains intact.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>high_income_index <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value =</span> <span class="fu">as.integer</span>(<span class="fu">rownames</span>(high_income)))</span>
<span id="cb29-2"><a href="#cb29-2"></a>dat <span class="ot">&lt;-</span> dat[<span class="sc">-</span>high_income_index<span class="sc">$</span>value,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Remember, the original dataset contains 29,092 rows. After removing 9 observations, we are left with 29,083 rows. Let’s take a look at the result.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(income)) <span class="sc">+</span> </span>
<span id="cb30-2"><a href="#cb30-2"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binwidth =</span> <span class="dv">10000</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Annual income"</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-aiwev" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aiwev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-aiwev-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aiwev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: Annual income without extreme values.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Somewhat better now.</p>
<p>We could also explore some gender issues.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>summary_table <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>  <span class="fu">group_by</span>(sex) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">summarize</span>(</span>
<span id="cb31-4"><a href="#cb31-4"></a>    <span class="at">Mean =</span> <span class="fu">mean</span>(income),</span>
<span id="cb31-5"><a href="#cb31-5"></a>    <span class="at">Median =</span> <span class="fu">median</span>(income),</span>
<span id="cb31-6"><a href="#cb31-6"></a>    <span class="at">Min =</span> <span class="fu">min</span>(income),</span>
<span id="cb31-7"><a href="#cb31-7"></a>    <span class="at">Max =</span> <span class="fu">max</span>(income),</span>
<span id="cb31-8"><a href="#cb31-8"></a>    <span class="at">Count =</span> <span class="fu">n</span>()</span>
<span id="cb31-9"><a href="#cb31-9"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb31-10"><a href="#cb31-10"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-11"><a href="#cb31-11"></a>    <span class="at">Gender =</span> <span class="fu">case_when</span>(</span>
<span id="cb31-12"><a href="#cb31-12"></a>      sex <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Male"</span>,</span>
<span id="cb31-13"><a href="#cb31-13"></a>      sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Female"</span></span>
<span id="cb31-14"><a href="#cb31-14"></a>    )</span>
<span id="cb31-15"><a href="#cb31-15"></a> )</span>
<span id="cb31-16"><a href="#cb31-16"></a>  </span>
<span id="cb31-17"><a href="#cb31-17"></a>summary_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  sex     Mean Median   Min    Max Count Gender
  &lt;fct&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt; &lt;chr&gt; 
1 0     66021.  56000  4000 900000 13877 Male  
2 1     67064.  57000  4200 948000 15206 Female</code></pre>
</div>
</div>
<p>The table shows that females tend to have slightly higher average and median incomes compared to males. Additionally, the income distribution for females appears more variable, with a wider range of incomes. While the sample sizes for both groups are similar, females are slightly more represented. Overall, the data suggests a modest income advantage for females and greater variability in their earnings.</p>
<p>The better we understand the data, the better positioned we are to analyze it, gain deeper insights into the problem, and interpret the solutions more effectively. However, there is a risk of falling into the trap of overexploration, losing sight of the main problem and failing to address the objectives. Data cleaning, for instance, can be an ongoing task. Removing outliers with excessively high incomes is just one example of how data cleaning can be approached. For now, we pause the exploration and cleaning process and move on to the next section, where we estimate models that will help us achieve the outlined objectives.</p>
</section>
<section id="logistic-models." class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="logistic-models."><span class="header-section-number">1.2</span> Logistic models.</h2>
<p>Logistic models allows us to make predictions about loan defaults. Logistic regression is a statistical model that in its basic form uses a logistic function to model a binary dependent variable like <tt><code>loan_st</code></tt>. In this case, the binary dependent variable is default (1) or no default (0). A good reference for this section is <span class="citation" data-cites="hull2020machine">Hull (<a href="#ref-hull2020machine" role="doc-biblioref">2020</a>)</span>.</p>
<p>First, load the data and split it into two sets: (1) training and (2) test. The training set is for building and estimate models, and the test set is used to evaluate our model predictions with new data. When estimating models, it is common practice to separate the available data into two parts, <em>training</em> and <em>test</em> data, where the training data is used to estimate parameters (in-sample) and the test data is used to evaluate its accuracy (out of sample). Because the test data is not used in determining the estimation, it should provide a reliable indication of how well the model is likely to estimate or forecast on new data. In sum, we train the model, we test the model, and once we are OK with the model performance on new data, we are ready to use it in real-life applications. If we ignore this split and use the whole database to estimate our models, we may succeed at explaining defaults in our database but we may fail to explain defaults for new loan applications.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># It is convenient to set the loan status as factor.</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>dat<span class="sc">$</span>loan_st <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dat<span class="sc">$</span>loan_st)</span>
<span id="cb33-3"><a href="#cb33-3"></a><span class="fu">set.seed</span>(<span class="dv">567</span>)</span>
<span id="cb33-4"><a href="#cb33-4"></a>index_train <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">runif</span>(<span class="dv">1</span> <span class="sc">:</span> <span class="fu">nrow</span>(dat), <span class="dv">0</span> , <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">:</span> <span class="fu">nrow</span>(dat)))</span>
<span id="cb33-5"><a href="#cb33-5"></a>index_train <span class="ot">&lt;-</span> <span class="fu">order</span>(index_train[, <span class="dv">1</span>])</span>
<span id="cb33-6"><a href="#cb33-6"></a>index_train <span class="ot">&lt;-</span> index_train[<span class="dv">1</span><span class="sc">:</span> (<span class="dv">2</span><span class="sc">/</span><span class="dv">3</span> <span class="sc">*</span> <span class="fu">nrow</span>(dat))]</span>
<span id="cb33-7"><a href="#cb33-7"></a><span class="co"># Create training set</span></span>
<span id="cb33-8"><a href="#cb33-8"></a>train <span class="ot">&lt;-</span> dat[index_train, ]</span>
<span id="cb33-9"><a href="#cb33-9"></a><span class="co"># Create test set</span></span>
<span id="cb33-10"><a href="#cb33-10"></a>test <span class="ot">&lt;-</span> dat[<span class="sc">-</span>index_train, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Variables as factors are useful for model estimation and data visualization. Factors are variables in R which take on a limited number of different values; such variables are often referred to as categorical variables.</p>
<p>We have 29,083 observations in <tt><code>dat</code></tt>. The code above randomly selects <span class="math inline">\(29083 \times (2/3)=19388\)</span> rows to form the <tt><code>train</code></tt>. The <tt><code>test</code></tt> are the remaining <span class="math inline">\(29083-19388=9695\)</span> rows. The random selection is highly recommended as the <tt><code>dat</code></tt> may have some structure or sorting that could bias our model estimation and negatively impact our model test. For example, imagine that for some weird reason the database is sorted in such a way that the first observations are all no default. If that is the case, then the training and the test set would not have portions of default and no default cases and we may distort the whole analysis. The random selection allows us to replicate a real situation in which our database is unsorted, with different characteristics.</p>
<p>Let’s see if the recent created <tt><code>train</code></tt> and <tt><code>test</code></tt> have the same basic properties than <tt><code>dat</code></tt>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="co"># Combine data into a list for processing</span></span>
<span id="cb34-2"><a href="#cb34-2"></a>data_list <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">dat =</span> dat<span class="sc">$</span>loan_st, <span class="at">train =</span> train<span class="sc">$</span>loan_st, <span class="at">test =</span> test<span class="sc">$</span>loan_st)</span>
<span id="cb34-3"><a href="#cb34-3"></a></span>
<span id="cb34-4"><a href="#cb34-4"></a><span class="co"># Compute proportions and combine into a data frame</span></span>
<span id="cb34-5"><a href="#cb34-5"></a>prop <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(data_list, <span class="cf">function</span>(x) <span class="fu">prop.table</span>(<span class="fu">table</span>(x))))</span>
<span id="cb34-6"><a href="#cb34-6"></a><span class="fu">colnames</span>(prop) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"no defaults"</span>, <span class="st">"defaults"</span>)</span>
<span id="cb34-7"><a href="#cb34-7"></a><span class="fu">row.names</span>(prop) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dat_prop"</span>, <span class="st">"train_prop"</span>, <span class="st">"test_prop"</span>)</span>
<span id="cb34-8"><a href="#cb34-8"></a>prop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           no defaults  defaults
dat_prop     0.8890417 0.1109583
train_prop   0.8882298 0.1117702
test_prop    0.8906653 0.1093347</code></pre>
</div>
</div>
<p>The proportions of “defaults” and “no defaults” in the train and test datasets are very similar to those in the original dataset, indicating that both samples are representative. Specifically, the proportion of “defaults” in the train and test datasets closely matches that of the original dataset, as does the proportion of “no defaults.” This suggests that the random sampling process has preserved the overall distribution of the target variable, ensuring that the train and test sets reflect the characteristics of the full dataset.</p>
<p>Assume we think that the <tt><code>loan_st</code></tt> depends on the age of the individual. We can estimate a simple logistic model to learn about the relationship between age and loan status.</p>
<p><span class="math inline">\(\log\left(\frac{p}{1-p}\right) = \beta_0 + \beta_1 \times \text{age}\)</span>.</p>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(p\)</span> is the probability that <code>loan_st = 1</code> (e.g., the probability of default).</p></li>
<li><p><span class="math inline">\(\beta_0\)</span> is the intercept, and <span class="math inline">\(\beta_1\)</span> is the coefficient for the predictor variable <code>age</code>.</p></li>
</ul>
<p>The dependent variable in logistic regression is expressed as: <span class="math inline">\(\log\left(\frac{p}{1-p}\right)\)</span>. This transformation, known as the <em>logit function</em>, maps probabilities <span class="math inline">\(p\)</span> which range between 0 and 1 to the entire real number line <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>. This allows the model to establish a linear relationship between the independent variable(s) (e.g., age) and the transformed dependent variable, making estimation feasible. The fraction <span class="math inline">\(\frac{p}{1-p}\)</span>, called the <em>odds</em>, represents the ratio of the probability of an event happening <span class="math inline">\(p\)</span> to the probability of it not happening <span class="math inline">\(1-p\)</span>, making it a natural choice for modeling binary outcomes.</p>
<p>Let’s estimate the age model.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="co"># Fitting a simple logistic model.</span></span>
<span id="cb36-2"><a href="#cb36-2"></a>logi_age <span class="ot">&lt;-</span> <span class="fu">glm</span>(loan_st <span class="sc">~</span> age, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> train)</span>
<span id="cb36-3"><a href="#cb36-3"></a>logi_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = loan_st ~ age, family = "binomial", data = train)

Coefficients:
(Intercept)          age  
   -1.90097     -0.00623  

Degrees of Freedom: 19387 Total (i.e. Null);  19386 Residual
Null Deviance:      13580 
Residual Deviance: 13580    AIC: 13580</code></pre>
</div>
</div>
<p>The estimated model is: <span class="math inline">\(\log\left(\frac{p}{1-p}\right) = -1.90097 - 0.00623 \times \text{age}\)</span>.</p>
<p>The model suggests there is a negative relationship between age and loan status.</p>
<p>We can solve for <span class="math inline">\(p\)</span> to find the estimate of the probability of default according to the age model: <span class="math inline">\(p = \frac{\exp(-1.90097 - 0.00623 \times \text{age})}{1 + \exp(-1.90097 - 0.00623 \times \text{age})}\)</span>. Let’s evaluate <span class="math inline">\(p\)</span> for a couple of age values.</p>
<p>Substituting <code>age = 18</code>: <span class="math inline">\(p = \frac{\exp(-1.90097 - 0.00623 \times 18)}{1 + \exp(-1.90097 - 0.00623 \times 18)}\)</span>,</p>
<p><span class="math inline">\(p = \frac{\exp(-2.01311)}{1 + \exp(-2.01311)} \approx \frac{0.1333}{1 + 0.1333} \approx 0.1176\)</span>.</p>
<p>Substituting <code>age = 60</code>: <span class="math inline">\(p = \frac{\exp(-1.90097 - 0.00623 \times 60)}{1 + \exp(-1.90097 - 0.00623 \times 60)}\)</span>,</p>
<p><span class="math inline">\(p = \frac{\exp(-2.27477)}{1 + \exp(-2.27477)} \approx \frac{0.1037}{1 + 0.1037} \approx 0.0939\)</span>.</p>
<p>The results of the default probability estimation evaluated at ages 18 and 60 are not very promising because the difference in probabilities is very small. This means that the model does not generate significantly differentiated default probabilities, even when evaluated over a wide age range. This can be problematic because it suggests that this is a poor model.</p>
<p>The following is a graphical representation of the logistic regression model’s output.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># Define the function for the logistic regression model</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>logistic_function <span class="ot">&lt;-</span> <span class="cf">function</span>(age) {</span>
<span id="cb38-3"><a href="#cb38-3"></a>  beta0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">1.90097</span></span>
<span id="cb38-4"><a href="#cb38-4"></a>  beta1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.00623</span></span>
<span id="cb38-5"><a href="#cb38-5"></a>  p <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> age) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> age))</span>
<span id="cb38-6"><a href="#cb38-6"></a>  <span class="fu">return</span>(p)</span>
<span id="cb38-7"><a href="#cb38-7"></a>}</span>
<span id="cb38-8"><a href="#cb38-8"></a></span>
<span id="cb38-9"><a href="#cb38-9"></a><span class="co"># Generate a sequence of ages</span></span>
<span id="cb38-10"><a href="#cb38-10"></a>ages <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1000</span>, <span class="dv">500</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb38-11"><a href="#cb38-11"></a></span>
<span id="cb38-12"><a href="#cb38-12"></a><span class="co"># Apply the logistic function to each age</span></span>
<span id="cb38-13"><a href="#cb38-13"></a>p_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(ages, logistic_function)</span>
<span id="cb38-14"><a href="#cb38-14"></a></span>
<span id="cb38-15"><a href="#cb38-15"></a><span class="co"># Create the plot</span></span>
<span id="cb38-16"><a href="#cb38-16"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-17"><a href="#cb38-17"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">age =</span> ages, <span class="at">p =</span> p_values), </span>
<span id="cb38-18"><a href="#cb38-18"></a>       <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> p)) <span class="sc">+</span></span>
<span id="cb38-19"><a href="#cb38-19"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb38-20"><a href="#cb38-20"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age"</span>, <span class="at">y =</span> <span class="st">"Probability (p)"</span>) <span class="sc">+</span></span>
<span id="cb38-21"><a href="#cb38-21"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-scolcam" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scolcam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-scolcam-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scolcam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: Sigmoid curve or logistic curve: age model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The logistic curve derived from this model is unreasonable because the probability <span class="math inline">\(p\)</span> changes very slowly with respect to age. This implies that, to observe the full range of probabilities from 0 to 1, we would require age values that are unrealistic or implausibly extreme. Such behavior suggests that the model is poorly specified, as it fails to generate meaningful distinctions in probabilities across a realistic range of ages.</p>
<p>The AIC value of the age model (13,580) is useful when comparing models. The Akaike information criterion (AIC) is a mathematical method for evaluating how well a model fits the data it was generated from. In statistics, AIC is used to compare different possible models and determine which one is the best fit for the data. At the moment we cannot interpret the AIC simply because we only have one model and we cannot compare it with another AIC.</p>
<p>Let’s estimate another simple model where the interest rate category is used as a predictor of the <tt><code>loan_st</code></tt>. Remember we are not conducting any prediction at all at this moment, we are only estimating models using the training set.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># Build a glm model with variable interest rate as a predictor.</span></span>
<span id="cb40-2"><a href="#cb40-2"></a>logi_int <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> loan_st <span class="sc">~</span> int, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> train)</span>
<span id="cb40-3"><a href="#cb40-3"></a><span class="co"># Print the parameter estimates.</span></span>
<span id="cb40-4"><a href="#cb40-4"></a>logi_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = loan_st ~ int, family = "binomial", data = train)

Coefficients:
(Intercept)          int  
     -3.710        0.142  

Degrees of Freedom: 19387 Total (i.e. Null);  19386 Residual
Null Deviance:      13580 
Residual Deviance: 13210    AIC: 13220</code></pre>
</div>
</div>
<p>The AIC is a lower (13,220 versus 13,580), so we have a better model now.</p>
<p>Using one single predictor as age or interest rate is clearly a limited approach. Let’s add some more predictors. Also, let’s introduce the <tt><code>summary()</code></tt> function to extract more information about the model estimation results. The <tt><code>logi_multi</code></tt> below assumes that the loan status depend on the age, interest rate, grade, loan amount, and annual income.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># Multiple variables in a logistic regression model.</span></span>
<span id="cb42-2"><a href="#cb42-2"></a>logi_multi <span class="ot">&lt;-</span> <span class="fu">glm</span>(loan_st <span class="sc">~</span> age <span class="sc">+</span> int <span class="sc">+</span> grade <span class="sc">+</span> <span class="fu">log</span>(l_amnt) <span class="sc">+</span> </span>
<span id="cb42-3"><a href="#cb42-3"></a>                  <span class="fu">log</span>(income) , <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> train)</span>
<span id="cb42-4"><a href="#cb42-4"></a><span class="co"># Obtain significance levels using summary().</span></span>
<span id="cb42-5"><a href="#cb42-5"></a><span class="fu">summary</span>(logi_multi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = loan_st ~ age + int + grade + log(l_amnt) + log(income), 
    family = "binomial", data = train)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  1.996240   0.477911   4.177 2.95e-05 ***
age         -0.002302   0.003825  -0.602   0.5473    
int          0.038767   0.017249   2.247   0.0246 *  
gradeB       0.503409   0.087435   5.758 8.54e-09 ***
gradeC       0.748229   0.117765   6.354 2.10e-10 ***
gradeD       0.964343   0.147283   6.548 5.85e-11 ***
gradeE       1.033442   0.190817   5.416 6.10e-08 ***
gradeF       1.619470   0.257900   6.279 3.40e-10 ***
gradeG       1.867494   0.440232   4.242 2.21e-05 ***
log(l_amnt)  0.015718   0.036341   0.433   0.6654    
log(income) -0.470748   0.046423 -10.140  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 13579  on 19387  degrees of freedom
Residual deviance: 13028  on 19377  degrees of freedom
AIC: 13050

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Our multi-factor model works well. In <tt><code>logi_multi</code></tt>, the AIC value is the lowest so far (13,050 versus 13,220), so this should be considered as the best in-sample model at the moment. The <tt><code>summary()</code></tt> function shows the significance levels of the estimators, but we are currently more interested in the goodness of fit of the models because we want to conduct predictions about the <tt><code>loan_st</code></tt>. This is, we are interested to use a model to find out whether new applicants in the test set are expected to default or not, rather than in the applicants’ credit risk factors. This is why we are concentrated in AIC now.</p>
<p>When a customer fill out a credit application form, we collect information but we do not know for sure whether she or he will eventually default. A credit risk model can help us in this task.</p>
</section>
<section id="prediction-and-model-evaluation." class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="prediction-and-model-evaluation."><span class="header-section-number">1.3</span> Prediction and model evaluation.</h2>
<p>Let’s take our three models: <tt><code>logi_age</code></tt>, <tt><code>logi_int</code></tt> and <tt><code>logi_multi</code></tt> from the previous subsection to carry out a simple prediction exercise. We start by identifying one observation in the test set and ask the models to predict the <tt><code>loan_st</code></tt>. This is, we take the first guy age, then we apply the <tt><code>logi_age</code></tt> model, and compare the predicted <tt><code>loan_st</code></tt> with respect to what really happened. Remember we know what really happened with this guy because we have the information in the test set. Every model is expected to produce different <tt><code>loan_st</code></tt> predictions. If the model is good, then the predicted <tt><code>loan_st</code></tt> will match what really happened.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># Define one single observation in test_set.</span></span>
<span id="cb44-2"><a href="#cb44-2"></a>John_Doe <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(test[<span class="dv">1</span>, ])</span>
<span id="cb44-3"><a href="#cb44-3"></a>John_Doe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  loan_st l_amnt   int grade emp_len home income age sex region
1       0   5000 10.65     B      10 RENT  24000  33   0      E</code></pre>
</div>
</div>
<p>We know in advance that the <tt><code>loan_st</code></tt> of this observation taken from the test set is 0. However, the models cannot know this simply because we did not use the test set to estimate the logistic models. Our models were estimated using the training set. A good credit risk model should predict a no default given this new applicant.</p>
<p>The values of <tt><code>loan_st</code></tt> in the test set is either 0 or 1. However, the logistic models estimate the <tt><code>loan_st</code></tt> as values in the range of 0 to 1. This mean that we would expect the estimated <tt><code>loan_st</code></tt> to be close to 0. <em>But, how close?</em> We will deal with this issue later.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># Predict the loan status.</span></span>
<span id="cb46-2"><a href="#cb46-2"></a>logi_age_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_age, <span class="at">newdata =</span> John_Doe, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb46-3"><a href="#cb46-3"></a>logi_int_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_int, <span class="at">newdata =</span> John_Doe, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb46-4"><a href="#cb46-4"></a>logi_multi_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_multi, <span class="at">newdata =</span> John_Doe, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb46-5"><a href="#cb46-5"></a><span class="co"># Collect all.</span></span>
<span id="cb46-6"><a href="#cb46-6"></a>pred_John <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">"logi_age"</span> <span class="ot">=</span> logi_age_pred, </span>
<span id="cb46-7"><a href="#cb46-7"></a>                     <span class="st">"logi_int"</span> <span class="ot">=</span> logi_int_pred, </span>
<span id="cb46-8"><a href="#cb46-8"></a>                     <span class="st">"logi_multi"</span> <span class="ot">=</span> logi_multi_pred)</span>
<span id="cb46-9"><a href="#cb46-9"></a><span class="co"># Prepare a table.</span></span>
<span id="cb46-10"><a href="#cb46-10"></a><span class="fu">colnames</span>(pred_John) <span class="ot">&lt;-</span> <span class="st">"Loan status predictions for John Doe."</span></span>
<span id="cb46-11"><a href="#cb46-11"></a>pred_John</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           Loan status predictions for John Doe.
logi_age                              0.10846236
logi_int                              0.09996702
logi_multi                            0.14461840</code></pre>
</div>
</div>
<p>These values are low as they are close to 0. We could interpret this as a certain ability of the models to predict this single case from the test set. However, several questions remains unanswered and requires further analysis. For example: <em>How can we determine if the prediction is low enough to consider it as a non-default?</em> We may need a cut-off value to decide. We will explore this issue later.</p>
<p>Another aspect is: <em>What about the rest of the cases in the test set?</em> We have 9,695 observations in the test set and in the example above we only test for the first one. We are interested in the entire test set, not only for John Doe. Fortunately, this issue is easy to address as we only need to change the <tt><code>newdata</code></tt> parameter in the <tt><code>predict()</code></tt> function. In particular, instead of <tt><code>newdata = John_Doe</code></tt>, which is one observation, and can change it to <tt><code>newdata = test</code></tt>, which is the entire 9,695 test set.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="co"># Predict the loan status with the three models.</span></span>
<span id="cb48-2"><a href="#cb48-2"></a>pred_logi_age <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_age, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb48-3"><a href="#cb48-3"></a>pred_logi_int <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_int, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb48-4"><a href="#cb48-4"></a>pred_logi_multi <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_multi, <span class="at">newdata =</span> test, </span>
<span id="cb48-5"><a href="#cb48-5"></a>                           <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb48-6"><a href="#cb48-6"></a></span>
<span id="cb48-7"><a href="#cb48-7"></a>pred_range <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">"logi_age"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_age), </span>
<span id="cb48-8"><a href="#cb48-8"></a>                     <span class="st">"logi_int"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_int),</span>
<span id="cb48-9"><a href="#cb48-9"></a>                     <span class="st">"logi_multi"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_multi))</span>
<span id="cb48-10"><a href="#cb48-10"></a>aic <span class="ot">&lt;-</span> <span class="fu">rbind</span>(logi_age<span class="sc">$</span>aic, logi_int<span class="sc">$</span>aic, logi_multi<span class="sc">$</span>aic)</span>
<span id="cb48-11"><a href="#cb48-11"></a>pred_range <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_range, aic)</span>
<span id="cb48-12"><a href="#cb48-12"></a><span class="fu">colnames</span>(pred_range) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"min(loan_st)"</span>, <span class="st">"max(loan_st)"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb48-13"><a href="#cb48-13"></a>pred_range</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           min(loan_st) max(loan_st)      AIC
logi_age     0.08417892    0.1165453 13580.65
logi_int     0.05019756    0.3982977 13215.61
logi_multi   0.01739107    0.4668004 13050.30</code></pre>
</div>
</div>
<p>Now, instead of the prediction of one single applicant we have conducted a prediction of all 9,695 applicants in the test set. The lower value column corresponds to the lower predicted <tt><code>loan_st</code></tt> for each model. The logistic models produce values in the range of zero to one, and in this case the ranges are rather narrow.</p>
<p>Narrow ranges (the difference between higher and lower <tt><code>loan_st</code></tt> predicted values) could be problematic because the model could not be able to discriminate between defaults (predictions closer to 1) and no-defaults (predictions closer to 0). The higher AIC corresponds to the worst in-sample model and the lower AIC to the best in-sample model. Here, we can see some in and out of sample consistency because the best model according to the AIC, corresponds to the model with the higher prediction range.</p>
<p>Let’s explore all the predicted <tt><code>loan_st</code></tt> values for the <tt><code>logi_age</code></tt>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(pred_logi_age), <span class="fu">aes</span>(<span class="at">x =</span> pred_logi_age)) <span class="sc">+</span> </span>
<span id="cb50-2"><a href="#cb50-2"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-amph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-amph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-amph-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-amph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: Age model prediction histogram.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <tt><code>logi_age</code></tt> fails to predict values ranging from 0 to 1. In fact, these values are quite concentrated in a very small range of values. As a consequence, this model fails to differentiate between default and no default predictions.</p>
<p>Let’s visualize the predictions of the <tt><code>logi_int</code></tt> and <tt><code>logi_multi</code></tt>. We first collect all predictions in a single data frame just for convenience.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a>pred_logi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(pred_logi_age, pred_logi_int,</span>
<span id="cb51-2"><a href="#cb51-2"></a>                                  pred_logi_multi))</span>
<span id="cb51-3"><a href="#cb51-3"></a>pred_logi <span class="ot">&lt;-</span> <span class="fu">gather</span>(pred_logi, <span class="at">key =</span> <span class="st">"model"</span>,  <span class="at">value =</span> <span class="st">"pred"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we plot the <tt><code>logi_int</code></tt> and <tt><code>logi_multi</code></tt>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="fu">ggplot</span>(pred_logi[pred_logi<span class="sc">$</span>model <span class="sc">!=</span> <span class="st">"pred_logi_age"</span>,], </span>
<span id="cb52-2"><a href="#cb52-2"></a>       <span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">fill =</span> model)) <span class="sc">+</span> </span>
<span id="cb52-3"><a href="#cb52-3"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-irammph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-irammph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-irammph-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-irammph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.6: Interest rate and multi models predictions histograms.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Let’s add the <tt><code>age</code></tt> model as well.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a><span class="fu">ggplot</span>(pred_logi, <span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">y =</span> model, <span class="at">fill =</span> model)) <span class="sc">+</span> </span>
<span id="cb53-2"><a href="#cb53-2"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Model"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-aairaammpb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aairaammpb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-aairaammpb-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aairaammpb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.7: Age, Interest rate and multi models predictions boxplot.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Presumably, a model which considers all available predictors could be better for predicting the <tt><code>loan_st</code></tt>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="co"># Logistic regression model using all available predictors in the data set.</span></span>
<span id="cb54-2"><a href="#cb54-2"></a>logi_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(loan_st <span class="sc">~</span> age <span class="sc">+</span> int <span class="sc">+</span> grade <span class="sc">+</span> <span class="fu">log</span>(l_amnt) <span class="sc">+</span> </span>
<span id="cb54-3"><a href="#cb54-3"></a>                   <span class="fu">log</span>(income) <span class="sc">+</span> emp_len <span class="sc">+</span> home <span class="sc">+</span> sex <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4"></a>                   region, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> train)</span>
<span id="cb54-5"><a href="#cb54-5"></a><span class="co"># Loan status predictions for all test set elements.</span></span>
<span id="cb54-6"><a href="#cb54-6"></a>pred_logi_full <span class="ot">&lt;-</span> <span class="fu">predict</span>(logi_full, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb54-7"><a href="#cb54-7"></a><span class="co"># Look at the predictions range.</span></span>
<span id="cb54-8"><a href="#cb54-8"></a><span class="fu">range</span>(pred_logi_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.422469e-09 8.544424e-01</code></pre>
</div>
</div>
<p>Now, the <tt><code>pred_logi_full</code></tt> prediction range is wider. A wider range means that the <tt><code>loan_st</code></tt> predictions are now closer to 1. This is good because we need the model to be able to predict both no-defaults (0) and defaults (1). Let’s see a prediction comparison with respect to the rest of the models.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a>pred_range <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">"logi_age"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_age), </span>
<span id="cb56-2"><a href="#cb56-2"></a>                     <span class="st">"logi_int"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_int),</span>
<span id="cb56-3"><a href="#cb56-3"></a>                     <span class="st">"logi_multi"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_multi),</span>
<span id="cb56-4"><a href="#cb56-4"></a>                     <span class="st">"logi_full"</span> <span class="ot">=</span> <span class="fu">range</span>(pred_logi_full))</span>
<span id="cb56-5"><a href="#cb56-5"></a>aic <span class="ot">&lt;-</span> <span class="fu">rbind</span>(logi_age<span class="sc">$</span>aic, logi_int<span class="sc">$</span>aic, logi_multi<span class="sc">$</span>aic, logi_full<span class="sc">$</span>aic)</span>
<span id="cb56-6"><a href="#cb56-6"></a>pred_range <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pred_range, aic)</span>
<span id="cb56-7"><a href="#cb56-7"></a><span class="fu">colnames</span>(pred_range) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"min(loan_st)"</span>, <span class="st">"max(loan_st)"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb56-8"><a href="#cb56-8"></a>pred_range</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           min(loan_st) max(loan_st)      AIC
logi_age   8.417892e-02    0.1165453 13580.65
logi_int   5.019756e-02    0.3982977 13215.61
logi_multi 1.739107e-02    0.4668004 13050.30
logi_full  1.422469e-09    0.8544424 10763.67</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a>pred_logi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(pred_logi_age, pred_logi_int,</span>
<span id="cb58-2"><a href="#cb58-2"></a>                                  pred_logi_multi, pred_logi_full))</span>
<span id="cb58-3"><a href="#cb58-3"></a>pred_logi <span class="ot">&lt;-</span> <span class="fu">gather</span>(pred_logi, <span class="at">key =</span> <span class="st">"model"</span>,  <span class="at">value =</span> <span class="st">"pred"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>A graphical comparison of the new <tt><code>pred_logi_full</code></tt> and <tt><code>pred_logi_multi</code></tt>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="fu">ggplot</span>(pred_logi[pred_logi<span class="sc">$</span>model <span class="sc">!=</span> <span class="st">"pred_logi_age"</span> <span class="sc">&amp;</span></span>
<span id="cb59-2"><a href="#cb59-2"></a>                  pred_logi<span class="sc">$</span>model <span class="sc">!=</span> <span class="st">"pred_logi_int"</span> ,], </span>
<span id="cb59-3"><a href="#cb59-3"></a>       <span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">fill =</span> model)) <span class="sc">+</span> </span>
<span id="cb59-4"><a href="#cb59-4"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-mafmph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mafmph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-mafmph-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mafmph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.8: Multi and full models predictions histograms.
</figcaption>
</figure>
</div>
</div>
</div>
<p>And all of them together.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">ggplot</span>(pred_logi, <span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">y =</span> model, <span class="at">fill =</span> model)) <span class="sc">+</span> </span>
<span id="cb60-2"><a href="#cb60-2"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Model"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-airmafmpb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-airmafmpb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-airmafmpb-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-airmafmpb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.9: Age, Interest rate, multi and full models predictions boxplot.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <tt><code>logi_full</code></tt> model predictions looks better than the other models.</p>
<p>Another question is: <em>How can we know these model predictions corresponds to a default or no default?</em> The loan status predictions go from 0 to 0.854 for the case of the <tt><code>logi_full</code></tt> model. At the end, these loan status estimations need to be interpreted or classified as a default or no default because we are interested on that. <em>Are they closer enough to 0 to consider a no default?</em> This issue is addressed by setting up a cut-off rate so we can split all estimated loan status into 0 or 1.</p>
<p>Let’s arbitrarily consider a cutoff of 0.15 for now. This means that every estimated loan status below 0.15 will be considered as 0 (no-default), and every estimated loan status above 0.15 will be considered as 1 (default). This classification rule can be used by a financial firm to decide whether to accept or reject new loan applications by rejecting loan applications with an estimated loan status above 0.15, and accepting those with an estimated loan status below 0.15. The accept/reject loan decision now depends on a model estimation. However, this simple approach could be controversial as managers may be interested in allocating more loans, not less. An alternative that meets credit risk and managers interests is to create several cutoff ranges instead of a single cutoff of 0.15. For example, the financial firm may accept loan applications with an estimated loan status between 0.15 and 0.25 with a higher interest rate to compensate for the additional credit risk. On the other hand, we may consider a different view by incorporating a social criterion to help those people who are naturally excluded by the financial industry given their economic condition. If this is the case, then, we may be interested to identify those applicants with a lower estimated loan status.</p>
<p>For now, consider that every estimated loan status below 0.15 will be considered as 0 (no-default), and every estimated loan status above 0.15 will be considered as 1 (default). Graphically it looks like this:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="co"># Convert the predictions to a data frame</span></span>
<span id="cb61-2"><a href="#cb61-2"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb61-3"><a href="#cb61-3"></a>  <span class="at">Observation =</span> <span class="fu">seq_along</span>(pred_logi_full),  <span class="co"># Sequence for observation index</span></span>
<span id="cb61-4"><a href="#cb61-4"></a>  <span class="at">Predicted_Probabilities =</span> pred_logi_full</span>
<span id="cb61-5"><a href="#cb61-5"></a>)</span>
<span id="cb61-6"><a href="#cb61-6"></a></span>
<span id="cb61-7"><a href="#cb61-7"></a><span class="co"># Create the plot</span></span>
<span id="cb61-8"><a href="#cb61-8"></a><span class="fu">ggplot</span>(pred_data, <span class="fu">aes</span>(<span class="at">x =</span> Observation, <span class="at">y =</span> Predicted_Probabilities)) <span class="sc">+</span></span>
<span id="cb61-9"><a href="#cb61-9"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span>  <span class="co"># Points for predictions</span></span>
<span id="cb61-10"><a href="#cb61-10"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.15</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Horizontal line</span></span>
<span id="cb61-11"><a href="#cb61-11"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Observation"</span>, </span>
<span id="cb61-12"><a href="#cb61-12"></a>       <span class="at">y =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb61-13"><a href="#cb61-13"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-fmpaco" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fmpaco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-fmpaco-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fmpaco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.10: Full model predictions and cut-off.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a><span class="fu">ggplot</span>(pred_logi[pred_logi<span class="sc">$</span>model <span class="sc">==</span> <span class="st">"pred_logi_full"</span>,], </span>
<span id="cb62-2"><a href="#cb62-2"></a>       <span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">fill =</span> model)) <span class="sc">+</span> </span>
<span id="cb62-3"><a href="#cb62-3"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.15</span>, <span class="at">linetype =</span> <span class="st">"longdash"</span>) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-fmphaco" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fmphaco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-fmphaco-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fmphaco-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.11: Full model predictions histogram and cut-off.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Here, predicted <tt><code>loan_st</code></tt> values at the left of the dashed line represent no default predictions and values at the right of the dashed line represent default predictions. Let’s set up the rule to convert the estimated loan status into a binary (0 or 1) variable. See how this transformation takes place:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a><span class="co"># Make a binary predictions-vector using a cut-off of 15%</span></span>
<span id="cb63-2"><a href="#cb63-2"></a>pred_cutoff_15 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_logi_full <span class="sc">&gt;</span> <span class="fl">0.15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb63-3"><a href="#cb63-3"></a><span class="fu">head</span>(<span class="fu">cbind</span>(pred_logi_full, <span class="st">"rounded"</span> <span class="ot">=</span> <span class="fu">round</span>(pred_logi_full, <span class="dv">4</span>), pred_cutoff_15))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   pred_logi_full rounded pred_cutoff_15
1    1.357995e-08  0.0000              0
2    2.986278e-08  0.0000              0
18   2.299645e-02  0.0230              0
26   2.403879e-01  0.2404              1
27   1.778986e-01  0.1779              1
28   2.600172e-02  0.0260              0</code></pre>
</div>
</div>
<p>These are only the first 6 rows in the test set. We can see that the rule works as expected because every estimated loan status below 0.15 is now considered as 0 (no-default), and every estimated loan status above 0.15 is considered as 1 (default). The table above shows how we can create this binary variable given the logistic model prediction.</p>
<p>Note that the rows numbers in the table above are 1, 2, 18, 26, 27 and 28. These are not 1, 2, 3, 4, 5 and 6 because the <tt><code>test</code></tt> rows were selected randomly out of the <tt><code>dat</code></tt>. So, the row numbers in the table above correspond to the original place in <tt><code>dat</code></tt>.</p>
<p>Is <tt><code>logi_full</code></tt> a good model after all? We can add a new column to the previous table. This new variable represents what really happened with the loan. Then, the first column is the logistic model prediction, the second column the transformed binary variable given a cutoff of 0.15, and the third column is what actually happened (default or no-default). Let’s take a sample of 10 observations to conduct the comparison easily. Note that the model correctly predicts a no default in most cases. Rows 308 and 329 predict a default incorrectly and row 323 predict a default correctly.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a><span class="co"># Let's take from rows 101 to 110.</span></span>
<span id="cb65-2"><a href="#cb65-2"></a>(<span class="fu">cbind</span>(pred_logi_full, pred_cutoff_15, </span>
<span id="cb65-3"><a href="#cb65-3"></a>           <span class="fu">as.data.frame.numeric</span>(test<span class="sc">$</span>loan_st)))[<span class="dv">101</span><span class="sc">:</span><span class="dv">110</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in as.data.frame.numeric(test$loan_st): Direct call of
'as.data.frame.numeric()' is deprecated.  Use 'as.data.frame.vector()' or
'as.data.frame()' instead</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    pred_logi_full pred_cutoff_15 test$loan_st
308   1.537106e-01              1            0
309   4.137654e-02              0            0
310   3.113926e-02              0            0
312   5.186962e-09              0            0
318   5.337092e-02              0            0
319   8.402239e-02              0            0
323   2.795535e-01              1            1
328   5.384112e-09              0            0
329   1.893745e-01              1            0
330   9.012136e-03              0            0</code></pre>
</div>
</div>
<p>There is an easy way to evaluate the rest of the cases in the test set using a simple table called confusion matrix.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="co"># Construct a confusion matrix.</span></span>
<span id="cb68-2"><a href="#cb68-2"></a><span class="fu">table</span>(test<span class="sc">$</span>loan_st, pred_cutoff_15)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   pred_cutoff_15
       0    1
  0 6554 2081
  1  308  752</code></pre>
</div>
</div>
<p>The <tt><code>logi_full</code></tt> model predicts 6,554 of no-defaults correctly and 752 defaults correctly. However, the model predicts 2,081 defaults that are in fact no-defaults and 308 no-defaults that are in fact defaults. <em>How good are these results?</em> Which of these four values is more important? These are questions we address later. For now, we can say that different models and different cut-off rates lead to different confusion matrix results. Please note that adding all these values leads to 9,695 which are the number of observations in the test set.</p>
<p>You may want to see relative and not absolute values. Let’s try the <tt><code>CrossTable()</code></tt> function instead.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="fu">CrossTable</span>(test<span class="sc">$</span>loan_st, pred_cutoff_15, <span class="at">prop.r =</span> <span class="cn">TRUE</span>,</span>
<span id="cb70-2"><a href="#cb70-2"></a>           <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Row Total |
|-------------------------|

 
Total Observations in Table:  9695 

 
             | pred_cutoff_15 
test$loan_st |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
           0 |      6554 |      2081 |      8635 | 
             |     0.759 |     0.241 |     0.891 | 
-------------|-----------|-----------|-----------|
           1 |       308 |       752 |      1060 | 
             |     0.291 |     0.709 |     0.109 | 
-------------|-----------|-----------|-----------|
Column Total |      6862 |      2833 |      9695 | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>This table is more informative. The <tt><code>logi_full</code></tt> model correctly predicts no-defaults in 75.9% of all the actual no-default cases. In other words, the model fails to predict no-default in 24.1% of the total no-default cases. Now the default. The model correctly predicts default in 70.9% of all the actual default cases (not bad), and fails to predict default in 29.1% of the total default cases.</p>
<p>Instead of arbitrarily consider a cutoff of 0.15, we can follow a different approach. Now consider that we are interested in taking the 20% highest estimates (closer to 1) of <tt><code>pred_logi_full</code></tt> as default. Equivalently, this is to take the lowest 80% <tt><code>pred_logi_full</code></tt> estimates (closer to 0) as no-default. Let’s calculate the new cut-off that meets this new criterion.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1"></a><span class="co"># Cutoff definition.</span></span>
<span id="cb72-2"><a href="#cb72-2"></a>cutoff <span class="ot">&lt;-</span> <span class="fu">quantile</span>(pred_logi_full, <span class="fl">0.8</span>)</span>
<span id="cb72-3"><a href="#cb72-3"></a>cutoff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      80% 
0.1994621 </code></pre>
</div>
</div>
<p>This new approach (taking the 20% highest estimates of <tt><code>pred_logi_full</code></tt> as default) represents a cut-off of 0.1994621. Graphically:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1"></a><span class="fu">ggplot</span>(pred_logi[pred_logi<span class="sc">$</span>model <span class="sc">==</span> <span class="st">"pred_logi_full"</span>,], </span>
<span id="cb74-2"><a href="#cb74-2"></a>       <span class="fu">aes</span>(<span class="at">x =</span> pred, <span class="at">fill =</span> model)) <span class="sc">+</span> </span>
<span id="cb74-3"><a href="#cb74-3"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> cutoff, <span class="at">linetype =</span> <span class="st">"longdash"</span>) <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">x =</span> <span class="st">"Default prediction"</span>) <span class="sc">+</span></span>
<span id="cb74-6"><a href="#cb74-6"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-fmphncoo0" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fmphncoo0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-fmphncoo0-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fmphncoo0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.12: Full model prediction histogram new cutoff of 0.1994621.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now the cut-off is 0.1994621. This splits the loan status predictions into two parts: higher than the cut-off is a default, and lower than the cutoff is a no-default. Taking the lowest 80% estimates (closer to 0) as no-default is an arbitrary decision. Here are the cut-off values depending on this arbitrary decision.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1"></a>cutoff_all <span class="ot">&lt;-</span> <span class="fu">quantile</span>(pred_logi_full, <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="fl">0.1</span>))</span>
<span id="cb75-2"><a href="#cb75-2"></a><span class="fu">data.frame</span>(<span class="st">"cut_off"</span> <span class="ot">=</span> <span class="fu">round</span>(cutoff_all,<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     cut_off
10%  0.00000
20%  0.01469
30%  0.02410
40%  0.03751
50%  0.06184
60%  0.09617
70%  0.14673
80%  0.19946
90%  0.29227
100% 0.85444</code></pre>
</div>
</div>
<p>We can show a similar summary table as we did with the cutoff of 0.15. Here, we show the predictive ability of the <tt><code>logi_full</code></tt> model and new cut-off of 0.1994621.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1"></a><span class="co"># Calculate the predictions with the same model and new cutoff.</span></span>
<span id="cb77-2"><a href="#cb77-2"></a>pred_full_20 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_logi_full <span class="sc">&gt;</span> cutoff, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb77-3"><a href="#cb77-3"></a><span class="co"># Show results in a confusion matrix.</span></span>
<span id="cb77-4"><a href="#cb77-4"></a><span class="fu">CrossTable</span>(test<span class="sc">$</span>loan_st, pred_full_20, <span class="at">prop.r =</span> <span class="cn">TRUE</span>,</span>
<span id="cb77-5"><a href="#cb77-5"></a>           <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Row Total |
|-------------------------|

 
Total Observations in Table:  9695 

 
             | pred_full_20 
test$loan_st |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
           0 |      7309 |      1326 |      8635 | 
             |     0.846 |     0.154 |     0.891 | 
-------------|-----------|-----------|-----------|
           1 |       447 |       613 |      1060 | 
             |     0.422 |     0.578 |     0.109 | 
-------------|-----------|-----------|-----------|
Column Total |      7756 |      1939 |      9695 | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>With a cutoff of 0.1994621 we accept 7,309 + 447 = 7,756 applications as those are the ones that the model predicts a no default. We can compare both confusion matrix:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1"></a>cat <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"correct no-default"</span>, <span class="st">"false default"</span>, </span>
<span id="cb79-2"><a href="#cb79-2"></a>         <span class="st">"false no-default"</span>, <span class="st">"correct default"</span>)</span>
<span id="cb79-3"><a href="#cb79-3"></a>cut_15 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.759</span>, <span class="fl">0.241</span>, <span class="fl">0.291</span>, <span class="fl">0.709</span>)</span>
<span id="cb79-4"><a href="#cb79-4"></a>cut_1994621 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.846</span>, <span class="fl">0.154</span>, <span class="fl">0.422</span>, <span class="fl">0.578</span>)</span>
<span id="cb79-5"><a href="#cb79-5"></a><span class="fu">cbind</span>(<span class="st">"classification"</span> <span class="ot">=</span> cat, cut_15, cut_1994621)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     classification       cut_15  cut_1994621
[1,] "correct no-default" "0.759" "0.846"    
[2,] "false default"      "0.241" "0.154"    
[3,] "false no-default"   "0.291" "0.422"    
[4,] "correct default"    "0.709" "0.578"    </code></pre>
</div>
</div>
<p>The new cut-off of 0.1994621 improves the identification of no-defaults but worsen the identification of default. Also, the new cut-off fails less in the default and fails more in the no-default. Apparently, there is some sort of trade-off here.</p>
<p>We can also look the detail of 0.1994621 cut-off. Comparing two columns, the one in the left with the actual loan status, and the right column with the estimated loan status.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a><span class="co"># Comparative table in detail.</span></span>
<span id="cb81-2"><a href="#cb81-2"></a>real_pred_20 <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(test<span class="sc">$</span>loan_st, pred_full_20,</span>
<span id="cb81-3"><a href="#cb81-3"></a>                     <span class="st">"Did the model succeed?"</span> <span class="ot">=</span> test<span class="sc">$</span>loan_st<span class="sc">==</span>pred_full_20)</span>
<span id="cb81-4"><a href="#cb81-4"></a><span class="co"># Show some values.</span></span>
<span id="cb81-5"><a href="#cb81-5"></a>real_pred_20[<span class="dv">131</span><span class="sc">:</span><span class="dv">140</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    test$loan_st pred_full_20 Did the model succeed?
398            0            0                   TRUE
399            1            1                   TRUE
404            0            1                  FALSE
414            0            0                   TRUE
417            1            1                   TRUE
419            0            0                   TRUE
420            0            0                   TRUE
425            1            1                   TRUE
431            0            0                   TRUE
435            0            0                   TRUE</code></pre>
</div>
</div>
<p>In this sample the model fails in 1 out of 10 individuals. Not bad at all. Let’s imagine we are a bank. We have a total of 9,695 applications for a loan in our desk (or computer). Assume we use the predictions from <tt><code>pred_full_20</code></tt> to decide whether we accept a loan application or not. Our model-based acceptance rule is the following: if <tt><code>pred_full_20 = 0</code></tt> then the model estimates a no-default and we accept the loan application. According to the extract of table above, we fortunately reject application 399, 417 and 425 because that was indeed a default. However, we reject application 404 incorrectly because it did not default. In principle, having a model as a base for a decision rule can lead to better results that guessing or a random approval rule.</p>
<p>Let’s count how many applications are accepted and rejected according to our rule.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a><span class="co"># Accepted.</span></span>
<span id="cb83-2"><a href="#cb83-2"></a>accept_20 <span class="ot">&lt;-</span> <span class="fu">sum</span>(pred_full_20 <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb83-3"><a href="#cb83-3"></a><span class="co"># Rejected.</span></span>
<span id="cb83-4"><a href="#cb83-4"></a>reject_20 <span class="ot">&lt;-</span> <span class="fu">sum</span>(pred_full_20 <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb83-5"><a href="#cb83-5"></a><span class="fu">data.frame</span>(<span class="st">"total"</span> <span class="ot">=</span> <span class="fu">length</span>(pred_full_20), accept_20, reject_20)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  total accept_20 reject_20
1  9695      7756      1939</code></pre>
</div>
</div>
<p>Taking the 20% highest estimates of <tt><code>pred_logi_full</code></tt> as default and the lowest 80% <tt><code>pred_logi_full</code></tt> as no-default mean that by construction, we accept 7,756 loan applications (80% of the total) and reject 1,939 (20% of the total). Then, the criterion determines the number of accepted applications, and the model determines which applications to accept/reject.</p>
<p>We can evaluate our loan accept/reject rule as we have the corresponding real values in <tt><code>loan_st</code></tt>. First, let’s illustrate the decision making process given the model estimates.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a><span class="co"># First 10 accept decisions.</span></span>
<span id="cb85-2"><a href="#cb85-2"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(real_pred_20[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], </span>
<span id="cb85-3"><a href="#cb85-3"></a>                <span class="at">decision =</span> <span class="fu">ifelse</span>(real_pred_20<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">0</span>, </span>
<span id="cb85-4"><a href="#cb85-4"></a>                                  <span class="st">"accept"</span>, <span class="st">"reject"</span>)), <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   test.loan_st pred_full_20 decision
1             0            0   accept
2             0            0   accept
18            1            0   accept
26            0            1   reject
27            0            0   accept
28            0            0   accept
30            0            0   accept
32            0            0   accept
34            0            1   reject
35            0            0   accept
36            0            0   accept
37            1            0   accept</code></pre>
</div>
</div>
<p>We can add an evaluation column.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a><span class="co"># First 10 accept decisions.</span></span>
<span id="cb87-2"><a href="#cb87-2"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(real_pred_20[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], </span>
<span id="cb87-3"><a href="#cb87-3"></a>                <span class="at">decision =</span> <span class="fu">ifelse</span>(real_pred_20<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">0</span>, </span>
<span id="cb87-4"><a href="#cb87-4"></a>                                  <span class="st">"accept"</span>, <span class="st">"reject"</span>),</span>
<span id="cb87-5"><a href="#cb87-5"></a>                <span class="at">evaluation =</span> <span class="fu">ifelse</span>(real_pred_20<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb87-6"><a href="#cb87-6"></a>                                    <span class="st">"we rejected a good customer"</span>, </span>
<span id="cb87-7"><a href="#cb87-7"></a> <span class="fu">ifelse</span>(real_pred_20<span class="sc">$</span>pred_full_20 <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> real_pred_20<span class="sc">$</span><span class="st">`</span><span class="at">test$loan_st</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">0</span>,</span>
<span id="cb87-8"><a href="#cb87-8"></a>        <span class="st">"good decision"</span>, <span class="st">"bad decision"</span>))), <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   test.loan_st pred_full_20 decision                  evaluation
1             0            0   accept               good decision
2             0            0   accept               good decision
18            1            0   accept                bad decision
26            0            1   reject we rejected a good customer
27            0            0   accept               good decision
28            0            0   accept               good decision
30            0            0   accept               good decision
32            0            0   accept               good decision
34            0            1   reject we rejected a good customer
35            0            0   accept               good decision
36            0            0   accept               good decision
37            1            0   accept                bad decision</code></pre>
</div>
</div>
<p>In the table above, we have the first 12 loan applications. According to our rule, we accept 10 applications and we reject 2 (application #26 and #34). A <em>good decision</em> is because we accept the loan that did not default. A <em>bad decision</em> is because we accept the loan application and defaulted. We also have some cases in which we rejected a good customer and that is not good. This table above is interesting although a bit problematic as it incorporates a counterfactual approach. In particular, we are evaluating the cases in which we reject the application. A more pragmatic approach is to evaluate our rule according to the cases in which we actually accept the loan application. This is the basically a bad rate measure: <em>how many accepted loan applications default?</em></p>
<p>Remember we accepted 10 and rejected 2 loans. We can identify who default.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1"></a><span class="co"># We accept loans that the model predicts a no-default (0).</span></span>
<span id="cb89-2"><a href="#cb89-2"></a><span class="co"># In "accepted_loans" we know whether the accepted loans are in fact</span></span>
<span id="cb89-3"><a href="#cb89-3"></a><span class="co"># default or no-default.</span></span>
<span id="cb89-4"><a href="#cb89-4"></a>accepted_loans <span class="ot">&lt;-</span> real_pred_20[pred_full_20 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb89-5"><a href="#cb89-5"></a><span class="co"># The code above says: if we accept the application, tell me what happened.</span></span>
<span id="cb89-6"><a href="#cb89-6"></a><span class="fu">head</span>(accepted_loans, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0 0 1 0 0 0 0 0 0 1
Levels: 0 1</code></pre>
</div>
</div>
<p>Note that the third and the tenth application default. These are applications #18 and #37 as expected. Now let’s evaluate not 12 applications but all of them, which are 7,756. The bad rate is now expressed as a percentage of the total:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1"></a><span class="co"># bad_rate is the proportion of accepted loans that are in fact default.</span></span>
<span id="cb91-2"><a href="#cb91-2"></a>bad_rate <span class="ot">&lt;-</span> <span class="fu">sum</span>(accepted_loans <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">length</span>(accepted_loans)</span>
<span id="cb91-3"><a href="#cb91-3"></a>bad_rate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0576328</code></pre>
</div>
</div>
<p>This is, by following the model-based rule, we accepted 7,756 loan applications that represent 80% of the total applications. However, 5.76% of those accepted applications were in fact a default. In particular, we accepted 447 loans that are defaults so: <span class="math inline">\(447/7756=0.0576328\)</span>.</p>
<p>Models are not perfect but we are always interested to find out a good model that leads to a lower bad rate because (in principle) we do not want to accept many defaults. If we keep the same model, we could reduce this 5.76% by being more strict in the loan application which in simple terms mean to reduce the acceptance rate. This alternative could be controversial as a lower acceptance rate represents lower income (less customers) for the bank or financial firm. In any case, consider we reduce the acceptance rate from 80% to 65% so we can evaluate the impact over the bad rate.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1"></a><span class="co"># New cutoff value.</span></span>
<span id="cb93-2"><a href="#cb93-2"></a>cutoff <span class="ot">&lt;-</span> <span class="fu">quantile</span>(pred_logi_full, <span class="fl">0.65</span>)</span>
<span id="cb93-3"><a href="#cb93-3"></a><span class="co"># Split the pred_logi_full into a binary variable.</span></span>
<span id="cb93-4"><a href="#cb93-4"></a>pred_full_35 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_logi_full <span class="sc">&gt;</span> cutoff, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb93-5"><a href="#cb93-5"></a><span class="co"># A data frame with real and predicted loan status.</span></span>
<span id="cb93-6"><a href="#cb93-6"></a>real_pred_35 <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(test<span class="sc">$</span>loan_st, pred_full_35)</span>
<span id="cb93-7"><a href="#cb93-7"></a><span class="co"># Loans that we accept given these new rules.</span></span>
<span id="cb93-8"><a href="#cb93-8"></a>accepted_loans <span class="ot">&lt;-</span> real_pred_35[pred_full_35 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb93-9"><a href="#cb93-9"></a><span class="co"># Bad rate (accepted loan applications that are defaults).</span></span>
<span id="cb93-10"><a href="#cb93-10"></a>bad_rate <span class="ot">&lt;-</span> <span class="fu">sum</span>(accepted_loans <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">length</span>(accepted_loans)</span>
<span id="cb93-11"><a href="#cb93-11"></a><span class="co"># Show the bad rate.</span></span>
<span id="cb93-12"><a href="#cb93-12"></a>bad_rate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03713107</code></pre>
</div>
</div>
<p>As expected, the bad rate is lower (from 5.76%% to 3.71%). This is, the lower the acceptance rate the lower the bad rate. In the extreme, if we accept 0 loan applications then our bad rate would be zero, but doing so is equivalent as going out of business. We can create a function such that given a vector of prediction of loan status we can return the bad rate for different cutoff values. This could be useful to build the <em>bank strategy</em>. This function will reveal the trade-off between the acceptance rate and the bad rate. In particular, the lower the acceptance rate, the lower the income (bad thing) and the lower the bad rate (good thing). So, <em>which combination is the optimal?</em></p>
</section>
<section id="the-bank-strategy." class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="the-bank-strategy."><span class="header-section-number">1.4</span> The bank strategy.</h2>
<p>A bank could be interested to understand the relationship between the acceptance rate and the bad rate given a model that predicts the loan status.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1"></a><span class="co"># Function.</span></span>
<span id="cb95-2"><a href="#cb95-2"></a>bank <span class="ot">&lt;-</span> <span class="cf">function</span>(prob_of_def){</span>
<span id="cb95-3"><a href="#cb95-3"></a>  cutoff <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">21</span>)</span>
<span id="cb95-4"><a href="#cb95-4"></a>  bad_rate <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">21</span>)</span>
<span id="cb95-5"><a href="#cb95-5"></a>  accept_rate <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="at">by =</span> <span class="sc">-</span><span class="fl">0.05</span>)</span>
<span id="cb95-6"><a href="#cb95-6"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">21</span>){</span>
<span id="cb95-7"><a href="#cb95-7"></a>    cutoff[i] <span class="ot">&lt;-</span> <span class="fu">quantile</span>(prob_of_def, accept_rate[i])</span>
<span id="cb95-8"><a href="#cb95-8"></a>    pred_i <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prob_of_def <span class="sc">&gt;</span> cutoff[i], <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb95-9"><a href="#cb95-9"></a>    pred_as_good <span class="ot">&lt;-</span> test<span class="sc">$</span>loan_st[pred_i <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb95-10"><a href="#cb95-10"></a>    bad_rate[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(pred_as_good <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">length</span>(pred_as_good)}</span>
<span id="cb95-11"><a href="#cb95-11"></a>  table <span class="ot">&lt;-</span> <span class="fu">cbind</span>(accept_rate, <span class="at">cutoff =</span> <span class="fu">round</span>(cutoff, <span class="dv">4</span>), </span>
<span id="cb95-12"><a href="#cb95-12"></a>                 <span class="at">bad_rate =</span> <span class="fu">round</span>(bad_rate, <span class="dv">4</span>))</span>
<span id="cb95-13"><a href="#cb95-13"></a>  <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">table =</span> table, <span class="at">bad_rate =</span> bad_rate, </span>
<span id="cb95-14"><a href="#cb95-14"></a>              <span class="at">accept_rate =</span> accept_rate, <span class="at">cutoff =</span> cutoff))</span>
<span id="cb95-15"><a href="#cb95-15"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can evaluate this function for the <tt><code>logi_full</code></tt>, and a bad model like the <tt><code>logi_age</code></tt>. In principle, we expect the <tt><code>logi_full</code></tt> model to have a more attractive relationship between the acceptance rate and the bad rate. This is, lower bad rates for a given acceptance rate. Any financial institution could be interested in increasing the acceptance rate without increasing too much the bad rate.</p>
<p>Let’s apply the function to the <tt><code>pred_logi_full</code></tt> and the <tt><code>logi_age</code></tt>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1"></a><span class="co"># Apply the bank function.</span></span>
<span id="cb96-2"><a href="#cb96-2"></a>bank_logi_full <span class="ot">&lt;-</span> <span class="fu">bank</span>(pred_logi_full)</span>
<span id="cb96-3"><a href="#cb96-3"></a>bank_logi_age <span class="ot">&lt;-</span> <span class="fu">bank</span>(pred_logi_age)</span>
<span id="cb96-4"><a href="#cb96-4"></a></span>
<span id="cb96-5"><a href="#cb96-5"></a><span class="fu">data.frame</span>(<span class="at">accept_rate =</span> bank_logi_age<span class="sc">$</span>accept_rate,</span>
<span id="cb96-6"><a href="#cb96-6"></a>           <span class="st">"Bad_model_bad_rate"</span> <span class="ot">=</span> bank_logi_age<span class="sc">$</span>bad_rate, </span>
<span id="cb96-7"><a href="#cb96-7"></a>           <span class="st">"Good_model_bad_rate)"</span> <span class="ot">=</span> bank_logi_full<span class="sc">$</span>bad_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   accept_rate Bad_model_bad_rate Good_model_bad_rate.
1         1.00         0.10933471          0.109334709
2         0.95         0.10849715          0.090662324
3         0.90         0.10849715          0.076790831
4         0.85         0.10849715          0.066626214
5         0.80         0.10547397          0.057632800
6         0.75         0.10547397          0.050612020
7         0.70         0.10396251          0.043619216
8         0.65         0.10396251          0.037131070
9         0.60         0.10092961          0.029396596
10        0.55         0.10092961          0.023443361
11        0.50         0.09933775          0.021039604
12        0.45         0.10206865          0.018565207
13        0.40         0.10206865          0.015471893
14        0.35         0.09907039          0.011788977
15        0.30         0.09972041          0.009281540
16        0.25         0.10343554          0.005363036
17        0.20         0.09722922          0.003610108
18        0.15         0.09360190          0.001374570
19        0.10         0.10125362          0.000000000
20        0.05         0.10516605          0.000000000
21        0.00         0.00000000          0.000000000</code></pre>
</div>
</div>
<p>The full model is superior because at any acceptance rate we can reach a lower bad rate. A plot can reveal the main differences of these two models: <tt><code>logi_full</code></tt> and <tt><code>logi_age</code></tt>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1"></a><span class="co"># Plot the strategy functions</span></span>
<span id="cb98-2"><a href="#cb98-2"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb98-3"><a href="#cb98-3"></a><span class="fu">plot</span>(bank_logi_full<span class="sc">$</span>accept_rate, bank_logi_full<span class="sc">$</span>bad_rate, </span>
<span id="cb98-4"><a href="#cb98-4"></a>     <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">xlab =</span> <span class="st">"Acceptance rate"</span>, <span class="at">ylab =</span> <span class="st">"Bad rate"</span>, </span>
<span id="cb98-5"><a href="#cb98-5"></a>     <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">main =</span> <span class="st">"logi_full"</span>)</span>
<span id="cb98-6"><a href="#cb98-6"></a><span class="fu">abline</span>(<span class="at">v =</span> bank_logi_full[[<span class="st">"accept_rate"</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb98-7"><a href="#cb98-7"></a><span class="fu">abline</span>(<span class="at">h =</span> bank_logi_full[[<span class="st">"bad_rate"</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb98-8"><a href="#cb98-8"></a><span class="fu">abline</span>(<span class="at">v =</span> bank_logi_full[[<span class="st">"accept_rate"</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb98-9"><a href="#cb98-9"></a><span class="fu">abline</span>(<span class="at">h =</span> bank_logi_full[[<span class="st">"bad_rate"</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb98-10"><a href="#cb98-10"></a><span class="fu">plot</span>(bank_logi_age<span class="sc">$</span>accept_rate, bank_logi_age<span class="sc">$</span>bad_rate,</span>
<span id="cb98-11"><a href="#cb98-11"></a>     <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">xlab =</span> <span class="st">"Acceptance rate"</span>, </span>
<span id="cb98-12"><a href="#cb98-12"></a>     <span class="at">ylab =</span> <span class="st">"Bad rate"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">main =</span> <span class="st">"logi_age"</span>)</span>
<span id="cb98-13"><a href="#cb98-13"></a><span class="fu">abline</span>(<span class="at">v =</span> bank_logi_age[[<span class="st">"accept_rate"</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb98-14"><a href="#cb98-14"></a><span class="fu">abline</span>(<span class="at">h =</span> bank_logi_age[[<span class="st">"bad_rate"</span>]][<span class="dv">8</span>], <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb98-15"><a href="#cb98-15"></a><span class="fu">abline</span>(<span class="at">v =</span> bank_logi_age[[<span class="st">"accept_rate"</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb98-16"><a href="#cb98-16"></a><span class="fu">abline</span>(<span class="at">h =</span> bank_logi_age[[<span class="st">"bad_rate"</span>]][<span class="dv">5</span>], <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-agaabm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-agaabm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-agaabm-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-agaabm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.13: A good and a bad model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <tt><code>logi_full</code></tt> model is better because for any acceptance rate we can reach a lower bad rate compared with the <tt><code>logi_age</code></tt>. This is because the <tt><code>logi_full</code></tt> model can identify defaults and no defaults with higher precision compared with the <tt><code>logi_age</code></tt>. The value of a good model is that it can help us to make better business decisions, in this case better credit evaluation decisions.</p>
<p>The model ability to predict defaults and no defaults can be measured by the AUC. The AUC can be defined as the probability that the fit model will score a randomly drawn positive sample higher than a randomly drawn negative sample. AUC stands for area under the curve in the following context:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1"></a>ROC_logi_full <span class="ot">&lt;-</span> <span class="fu">roc</span>(test<span class="sc">$</span>loan_st, pred_logi_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1"></a>ROC_logi_age <span class="ot">&lt;-</span> <span class="fu">roc</span>(test<span class="sc">$</span>loan_st, pred_logi_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1
Setting direction: controls &lt; cases</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1"></a><span class="co"># Draw the ROCs on one plot</span></span>
<span id="cb104-2"><a href="#cb104-2"></a><span class="fu">plot</span>(ROC_logi_full, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb104-3"><a href="#cb104-3"></a><span class="fu">lines</span>(ROC_logi_age, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-fmiramib" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fmiramib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-fmiramib-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fmiramib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.14: Full model in red, age model in blue.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Sensitivity is the model ability to correctly identify defaults, these are known as true positive. Specificity is the model ability to correctly identify no-default loans, these are known as true negative.</p>
<p>As expected, the area under the curve (AUC) is higher for the red line which corresponds to the <tt><code>logi_full</code></tt> model. We can calculate the exact values:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1"></a><span class="co"># Compute the AUCs:</span></span>
<span id="cb105-2"><a href="#cb105-2"></a><span class="fu">auc</span>(ROC_logi_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.8213</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1"></a><span class="fu">auc</span>(ROC_logi_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.5301</code></pre>
</div>
</div>
<p>Note that the <tt><code>logi_age</code></tt> has an AUC of 0.5301. This is close to a loan approval process in which we randomly accept and reject with no further analysis. In other words, the <tt><code>logi_age</code></tt> is so bad that it is almost equivalent as using no model at all and accept and reject loan applications based on a random rule. A pure-random approval rule would look like this:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1"></a><span class="fu">set.seed</span>(<span class="dv">2020</span>)</span>
<span id="cb109-2"><a href="#cb109-2"></a>pred_rand_model <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fu">length</span>(pred_logi_age))</span>
<span id="cb109-3"><a href="#cb109-3"></a>ROC_rand <span class="ot">&lt;-</span> <span class="fu">roc</span>(test<span class="sc">$</span>loan_st, pred_rand_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1"></a><span class="co"># Draw the ROCs on one plot</span></span>
<span id="cb112-2"><a href="#cb112-2"></a><span class="fu">plot</span>(ROC_rand, <span class="at">col =</span> <span class="st">"orange"</span>)</span>
<span id="cb112-3"><a href="#cb112-3"></a><span class="fu">auc</span>(ROC_rand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.5105</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-rrm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rrm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-rrm-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rrm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.15: Random rule model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In theory, this random evaluation process would lead to an AUC of <span class="math inline">\(0.5 = (1 \times 1)/2\)</span>. In contrast, now imagine we have a perfect model:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1"></a>pred_perfect_model <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(test<span class="sc">$</span>loan_st)</span>
<span id="cb114-2"><a href="#cb114-2"></a>ROC_perfect <span class="ot">&lt;-</span> <span class="fu">roc</span>(test<span class="sc">$</span>loan_st, pred_perfect_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1"></a><span class="fu">plot</span>(ROC_perfect)</span>
<span id="cb117-2"><a href="#cb117-2"></a><span class="fu">auc</span>(ROC_perfect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 1</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-pm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Logistic_files/figure-html/fig-pm-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.16: Perfect model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In a perfect model, the AUC is equal to 1 (<span class="math inline">\(1 \times 1\)</span>). The model correctly identify defaults (100% sensitivity) and at the same time the model correctly identify no-defaults (100% specificity).</p>
<p>Edward Malthouse explains these concepts quite well:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1"></a><span class="fu">embed_url</span>(<span class="st">"https://youtu.be/HljSmQhLs8M"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="vembedr">
<div>
<iframe src="https://www.youtube.com/embed/HljSmQhLs8M" width="533" height="300" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Hull" class="csl-entry" role="listitem">
Hull, John C. 2015. <em>Options, Futures, and Other Derivatives</em>. 9th ed. Prentice Hall.
</div>
<div id="ref-hull2020machine" class="csl-entry" role="listitem">
———. 2020. <em>Machine Learning in Business: An Introduction to the World of Data Science</em>. Amazon Distribution.
</div>
<div id="ref-knuth1984literate" class="csl-entry" role="listitem">
Knuth, Donald Ervin. 1984. <span>“Literate Programming.”</span> <em>The Computer Journal</em> 27 (2): 97–111.
</div>
<div id="ref-Rref" class="csl-entry" role="listitem">
R Core Team. 2024. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<!-- Google tag (gtag.js) -->

<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-3RFWK4ZPH8"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());



  gtag('config', 'G-3RFWK4ZPH8');

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="Logistic_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>