<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 The Merton model. | Credit risk with R.</title>
  <meta name="description" content="2 The Merton model. | Credit risk with R." />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="2 The Merton model. | Credit risk with R." />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 The Merton model. | Credit risk with R." />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="loan-analysis..html"/>
<link rel="next" href="the-gaussian-copula-model..html"/>
<style type="text/css">
p.abstract{
  text-align: center;
  font-weight: bold;
}
div.abstract{
  margin: auto;
  width: 90%;
}
</style>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="loan-analysis..html"><a href="loan-analysis..html"><i class="fa fa-check"></i><b>1</b> Loan analysis.</a>
<ul>
<li class="chapter" data-level="1.1" data-path="loan-analysis..html"><a href="loan-analysis..html#explore-the-database."><i class="fa fa-check"></i><b>1.1</b> Explore the database.</a></li>
<li class="chapter" data-level="1.2" data-path="loan-analysis..html"><a href="loan-analysis..html#logistic-models."><i class="fa fa-check"></i><b>1.2</b> Logistic models.</a></li>
<li class="chapter" data-level="1.3" data-path="loan-analysis..html"><a href="loan-analysis..html#prediction-and-model-evaluation."><i class="fa fa-check"></i><b>1.3</b> Prediction and model evaluation.</a></li>
<li class="chapter" data-level="1.4" data-path="loan-analysis..html"><a href="loan-analysis..html#the-bank-strategy."><i class="fa fa-check"></i><b>1.4</b> The bank strategy.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="the-merton-model..html"><a href="the-merton-model..html"><i class="fa fa-check"></i><b>2</b> The Merton model.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-merton-model..html"><a href="the-merton-model..html#minimize-a-function-in-r."><i class="fa fa-check"></i><b>2.1</b> Minimize a function in R.</a></li>
<li class="chapter" data-level="2.2" data-path="the-merton-model..html"><a href="the-merton-model..html#applied-example."><i class="fa fa-check"></i><b>2.2</b> Applied example.</a></li>
<li class="chapter" data-level="2.3" data-path="the-merton-model..html"><a href="the-merton-model..html#inside-view-of-the-mertons-model."><i class="fa fa-check"></i><b>2.3</b> Inside view of the Merton’s model.</a></li>
<li class="chapter" data-level="2.4" data-path="the-merton-model..html"><a href="the-merton-model..html#the-probability-of-default-as-a-function-of-some-parameters."><i class="fa fa-check"></i><b>2.4</b> The probability of default as a function of some parameters.</a></li>
<li class="chapter" data-level="2.5" data-path="the-merton-model..html"><a href="the-merton-model..html#got-capital-structure."><i class="fa fa-check"></i><b>2.5</b> GoT: capital structure.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html"><i class="fa fa-check"></i><b>3</b> The Gaussian copula model.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#the-basics."><i class="fa fa-check"></i><b>3.1</b> The basics.</a></li>
<li class="chapter" data-level="3.2" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#introduction-to-example-24.6."><i class="fa fa-check"></i><b>3.2</b> Introduction to example 24.6.</a></li>
<li class="chapter" data-level="3.3" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#one-firm."><i class="fa fa-check"></i><b>3.3</b> One firm.</a></li>
<li class="chapter" data-level="3.4" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#two-firms."><i class="fa fa-check"></i><b>3.4</b> Two firms.</a></li>
<li class="chapter" data-level="3.5" data-path="the-gaussian-copula-model..html"><a href="the-gaussian-copula-model..html#ten-firms."><i class="fa fa-check"></i><b>3.5</b> Ten firms.</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="credit-var-example-24.7..html"><a href="credit-var-example-24.7..html"><i class="fa fa-check"></i><b>4</b> Credit VaR example 24.7.</a></li>
<li class="chapter" data-level="" data-path="references..html"><a href="references..html"><i class="fa fa-check"></i>References.</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Credit risk with R.</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-merton-model." class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> The Merton model.<a href="the-merton-model..html#the-merton-model." class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The Merton model is useful when we are interested to evaluate the credit risk of public firms. In short, it evaluates how likely is that the value of the firm’s assets fall in the future below a certain threshold represented by the firm’s debt. By doing that, the model is able to estimate a probability of default among other results. The model can be used as a tool to propose changes (for example) in the balance sheet to reduce the credit risk exposure of a firm.</p>
<div id="minimize-a-function-in-r." class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Minimize a function in R.<a href="the-merton-model..html#minimize-a-function-in-r." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The estimation of the credit risk Merton’s model requires a minimization of a function. In this section, we show a simple minimization example. Here are some useful online resources for further references.</p>
<ul>
<li><a href="https://youtu.be/lV0ytJYbVzc">FRM: How d2 in Black-Scholes becomes PD in Merton model.</a></li>
<li><a href="https://www.intmath.com/counting-probability/normal-distribution-graph-interactive.php">Normal Probability Distribution Graph. Interactive.</a></li>
<li><a href="https://www.r-bloggers.com/how-to-use-optim-in-r/">How to use optim in R.</a></li>
</ul>
<p>The objective function to be minimized is <span class="math inline">\(f(a,b)=\sum(a + bx_i-y_i)^2\)</span>. We have six values for <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, and we are expected to minimize the function <span class="math inline">\(f\)</span> by finding the parameter values <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. The <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> data looks like this:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="the-merton-model..html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data.</span></span>
<span id="cb84-2"><a href="the-merton-model..html#cb84-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>))</span>
<span id="cb84-3"><a href="the-merton-model..html#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(dat, <span class="at">caption =</span> <span class="st">&quot;Observations.&quot;</span>, <span class="at">row.names =</span> <span class="cn">TRUE</span>) <span class="co"># The table.</span></span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-20">Table 2.1: </span>Observations.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">x</th>
<th align="right">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">2</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="right">3</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="right">4</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="right">5</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="right">6</td>
<td align="right">12</td>
</tr>
</tbody>
</table>
<p>Graphically:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="the-merton-model..html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A scatter plot.</span></span>
<span id="cb85-2"><a href="the-merton-model..html#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dat, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="index_files/figure-html/unnamed-chunk-21-1.png" alt="Original data." width="672"  />
<p class="caption">
Figure 2.1: Original data.
</p>
</div>
<p>Let’s implement the minimization.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="the-merton-model..html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function that calculates the residual sum of squares.</span></span>
<span id="cb86-2"><a href="the-merton-model..html#cb86-2" aria-hidden="true" tabindex="-1"></a>min.RSS <span class="ot">&lt;-</span> <span class="cf">function</span>(data, par) {</span>
<span id="cb86-3"><a href="the-merton-model..html#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(data, <span class="fu">sum</span>((par[<span class="dv">1</span>] <span class="sc">+</span> par[<span class="dv">2</span>] <span class="sc">*</span> x <span class="sc">-</span> y)<span class="sc">^</span><span class="dv">2</span>)) }</span>
<span id="cb86-4"><a href="the-merton-model..html#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Function minimization.</span></span>
<span id="cb86-5"><a href="the-merton-model..html#cb86-5" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), min.RSS, <span class="at">data =</span> dat)</span>
<span id="cb86-6"><a href="the-merton-model..html#cb86-6" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> result<span class="sc">$</span>par[<span class="dv">1</span>]</span>
<span id="cb86-7"><a href="the-merton-model..html#cb86-7" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> result<span class="sc">$</span>par[<span class="dv">2</span>]</span>
<span id="cb86-8"><a href="the-merton-model..html#cb86-8" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">sum</span>((a <span class="sc">+</span> b <span class="sc">*</span> dat<span class="sc">$</span>x <span class="sc">-</span> dat<span class="sc">$</span>y)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb86-9"><a href="the-merton-model..html#cb86-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Minimization output.</span></span>
<span id="cb86-10"><a href="the-merton-model..html#cb86-10" aria-hidden="true" tabindex="-1"></a>ans <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(a, b, f)</span>
<span id="cb86-11"><a href="the-merton-model..html#cb86-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(ans, <span class="at">caption =</span> <span class="st">&quot;Minimization results f(a,b).&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-22">Table 2.2: </span>Minimization results f(a,b).</caption>
<thead>
<tr class="header">
<th align="right">a</th>
<th align="right">b</th>
<th align="right">f</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-1.266846</td>
<td align="right">2.02862</td>
<td align="right">2.819048</td>
</tr>
</tbody>
</table>
<p>The minimization result is represented by a line, and the line is characterized by an intercept equal to <span class="math inline">\(-1.266846\)</span> and a slope equal to <span class="math inline">\(2.02862\)</span>.</p>
<p>We can plot it and verify that this is indeed the right answer.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="the-merton-model..html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the results.</span></span>
<span id="cb87-2"><a href="the-merton-model..html#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dat, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">12</span>), <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">6</span>), <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb87-3"><a href="the-merton-model..html#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(a, b, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb87-4"><a href="the-merton-model..html#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb87-5"><a href="the-merton-model..html#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-23"></span>
<img src="index_files/figure-html/unnamed-chunk-23-1.png" alt="Line that minimize the residual sum of squares." width="672"  />
<p class="caption">
Figure 2.2: Line that minimize the residual sum of squares.
</p>
</div>
<p>The function that we minimize here is basically the OLS criterion. This is why the regression model leads to the same results.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="the-merton-model..html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The previous example is equivalent as a linear regression model.</span></span>
<span id="cb88-2"><a href="the-merton-model..html#cb88-2" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dat)</span>
<span id="cb88-3"><a href="the-merton-model..html#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="co"># See the results.</span></span>
<span id="cb88-4"><a href="the-merton-model..html#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = dat)
## 
## Residuals:
##       1       2       3       4       5       6 
##  0.2381  0.2095  0.1810 -0.8476 -0.8762  1.0952 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -1.2667     0.7815  -1.621 0.180388    
## x             2.0286     0.2007  10.109 0.000539 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8395 on 4 degrees of freedom
## Multiple R-squared:  0.9623, Adjusted R-squared:  0.9529 
## F-statistic: 102.2 on 1 and 4 DF,  p-value: 0.000539</code></pre>
<p>The function that we minimize in the estimation of the credit risk Merton model is more elaborated but we follow the same principle as above.</p>
</div>
<div id="applied-example." class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Applied example.<a href="the-merton-model..html#applied-example." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s follow the example 24.3 in <span class="citation">(Hull 2015)</span>. Five parameters: <span class="math inline">\(E_0=3\)</span>, <span class="math inline">\(\sigma_E=0.8\)</span>, <span class="math inline">\(rf=0.05\)</span>, <span class="math inline">\(T=1\)</span>, <span class="math inline">\(D=10\)</span> lead to an estimate of the value of the assets today <span class="math inline">\(V_0\)</span> and the volatility of the assets <span class="math inline">\(\sigma_V\)</span>. With these seven parameters we can estimate the probability of default (pd) among other results.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="the-merton-model..html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of known parameters.</span></span>
<span id="cb90-2"><a href="the-merton-model..html#cb90-2" aria-hidden="true" tabindex="-1"></a>E0 <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co"># Value of the equity as today, I recommend market capitalization.</span></span>
<span id="cb90-3"><a href="the-merton-model..html#cb90-3" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fl">0.8</span> <span class="co"># Stock returns volatility.</span></span>
<span id="cb90-4"><a href="the-merton-model..html#cb90-4" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co"># Risk-free rate.</span></span>
<span id="cb90-5"><a href="the-merton-model..html#cb90-5" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co"># Maturity.</span></span>
<span id="cb90-6"><a href="the-merton-model..html#cb90-6" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># Value of the debt. The Bloomberg function DDIS is useful.</span></span>
<span id="cb90-7"><a href="the-merton-model..html#cb90-7" aria-hidden="true" tabindex="-1"></a><span class="co"># We need equations 24.3 and 24.4 to estimate V0 and sv.</span></span>
<span id="cb90-8"><a href="the-merton-model..html#cb90-8" aria-hidden="true" tabindex="-1"></a>eq24<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb90-9"><a href="the-merton-model..html#cb90-9" aria-hidden="true" tabindex="-1"></a>  ((V0 <span class="sc">*</span> <span class="fu">pnorm</span>((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span></span>
<span id="cb90-10"><a href="the-merton-model..html#cb90-10" aria-hidden="true" tabindex="-1"></a>  D <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>rf <span class="sc">*</span> TT) <span class="sc">*</span> <span class="fu">pnorm</span>(((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span></span>
<span id="cb90-11"><a href="the-merton-model..html#cb90-11" aria-hidden="true" tabindex="-1"></a>  (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)) <span class="sc">-</span> E0)) }</span>
<span id="cb90-12"><a href="the-merton-model..html#cb90-12" aria-hidden="true" tabindex="-1"></a>eq24<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb90-13"><a href="the-merton-model..html#cb90-13" aria-hidden="true" tabindex="-1"></a>  ((<span class="fu">pnorm</span>((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">*</span></span>
<span id="cb90-14"><a href="the-merton-model..html#cb90-14" aria-hidden="true" tabindex="-1"></a>      sv <span class="sc">*</span> V0 <span class="sc">-</span> se <span class="sc">*</span> E0)) }</span>
<span id="cb90-15"><a href="the-merton-model..html#cb90-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Footnote 10 indicates that we should minimize F(x,y)^2+G(x,y)^2</span></span>
<span id="cb90-16"><a href="the-merton-model..html#cb90-16" aria-hidden="true" tabindex="-1"></a>min.footnote10 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) </span>
<span id="cb90-17"><a href="the-merton-model..html#cb90-17" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">eq24.3</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>]))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="fu">eq24.4</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>]))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb90-18"><a href="the-merton-model..html#cb90-18" aria-hidden="true" tabindex="-1"></a><span class="co"># The minimization leads to the values of V0 and sv.</span></span>
<span id="cb90-19"><a href="the-merton-model..html#cb90-19" aria-hidden="true" tabindex="-1"></a>V0_sv <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), min.footnote10)</span>
<span id="cb90-20"><a href="the-merton-model..html#cb90-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the values as parameters.</span></span>
<span id="cb90-21"><a href="the-merton-model..html#cb90-21" aria-hidden="true" tabindex="-1"></a>V0 <span class="ot">&lt;-</span> V0_sv<span class="sc">$</span>par[<span class="dv">1</span>]</span>
<span id="cb90-22"><a href="the-merton-model..html#cb90-22" aria-hidden="true" tabindex="-1"></a>sv <span class="ot">&lt;-</span> V0_sv<span class="sc">$</span>par[<span class="dv">2</span>]</span>
<span id="cb90-23"><a href="the-merton-model..html#cb90-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the probability of default as a function.</span></span>
<span id="cb90-24"><a href="the-merton-model..html#cb90-24" aria-hidden="true" tabindex="-1"></a>PD <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb90-25"><a href="the-merton-model..html#cb90-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pnorm</span>(<span class="sc">-</span>(((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> </span>
<span id="cb90-26"><a href="the-merton-model..html#cb90-26" aria-hidden="true" tabindex="-1"></a>             (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) }</span>
<span id="cb90-27"><a href="the-merton-model..html#cb90-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the probability of default given the previous parameters.</span></span>
<span id="cb90-28"><a href="the-merton-model..html#cb90-28" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="fu">PD</span>(V0, sv)</span>
<span id="cb90-29"><a href="the-merton-model..html#cb90-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Gather the results.</span></span>
<span id="cb90-30"><a href="the-merton-model..html#cb90-30" aria-hidden="true" tabindex="-1"></a>ans <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pd, V0, sv)</span>
<span id="cb90-31"><a href="the-merton-model..html#cb90-31" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(ans, <span class="at">caption =</span> <span class="st">&quot;Main model results.&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-25">Table 2.3: </span>Main model results.</caption>
<thead>
<tr class="header">
<th align="right">pd</th>
<th align="right">V0</th>
<th align="right">sv</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.1269396</td>
<td align="right">12.39578</td>
<td align="right">0.2123041</td>
</tr>
</tbody>
</table>
<p>Let’s analyze the role of the values of <span class="math inline">\(d_1\)</span>, <span class="math inline">\(d_2\)</span>, <span class="math inline">\(N(d_1)\)</span> and <span class="math inline">\(N(d_2)\)</span>. First we isolate these values.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="the-merton-model..html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the role of d and N(d).</span></span>
<span id="cb91-2"><a href="the-merton-model..html#cb91-2" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> (<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))</span>
<span id="cb91-3"><a href="the-merton-model..html#cb91-3" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d1 <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)</span>
<span id="cb91-4"><a href="the-merton-model..html#cb91-4" aria-hidden="true" tabindex="-1"></a>Nd1 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(d1)</span>
<span id="cb91-5"><a href="the-merton-model..html#cb91-5" aria-hidden="true" tabindex="-1"></a>Nd2 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(d2)</span>
<span id="cb91-6"><a href="the-merton-model..html#cb91-6" aria-hidden="true" tabindex="-1"></a>ans <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(d1, Nd1, d2, Nd2)</span>
<span id="cb91-7"><a href="the-merton-model..html#cb91-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(ans, <span class="at">caption =</span> <span class="st">&quot;Inspect the role of d and N(d).&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-26">Table 2.4: </span>Inspect the role of d and N(d).</caption>
<thead>
<tr class="header">
<th align="right">d1</th>
<th align="right">Nd1</th>
<th align="right">d2</th>
<th align="right">Nd2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.353282</td>
<td align="right">0.9120172</td>
<td align="right">1.140978</td>
<td align="right">0.8730604</td>
</tr>
</tbody>
</table>
<p>Now let’s illustrate how <span class="math inline">\(N(-d_2)\)</span> lead to the probability of default given the properties of a standard normal distribution.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="the-merton-model..html#cb92-1" aria-hidden="true" tabindex="-1"></a>xseq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">0.01</span>) </span>
<span id="cb92-2"><a href="the-merton-model..html#cb92-2" aria-hidden="true" tabindex="-1"></a>densities <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(xseq, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># Standard normal distribution.</span></span>
<span id="cb92-3"><a href="the-merton-model..html#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Graphical evaluation of N(-d_2).</span></span>
<span id="cb92-4"><a href="the-merton-model..html#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(xseq, densities, <span class="at">xlab =</span> <span class="st">&quot;d values (d_2 is dotted line)&quot;</span>, </span>
<span id="cb92-5"><a href="the-merton-model..html#cb92-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Density&quot;</span>, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb92-6"><a href="the-merton-model..html#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb92-7"><a href="the-merton-model..html#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(xseq[xseq <span class="sc">&gt;=</span> d2], d2), <span class="fu">c</span>(densities[xseq <span class="sc">&gt;=</span> d2], <span class="dv">0</span>), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb92-8"><a href="the-merton-model..html#cb92-8" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(xseq[xseq <span class="sc">&lt;</span> d2], d2), <span class="fu">c</span>(densities[xseq <span class="sc">&lt;</span> d2], <span class="dv">0</span>), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb92-9"><a href="the-merton-model..html#cb92-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;N(d_2)=0.8730604 </span></span>
<span id="cb92-10"><a href="the-merton-model..html#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="st">is represented in blue and</span></span>
<span id="cb92-11"><a href="the-merton-model..html#cb92-11" aria-hidden="true" tabindex="-1"></a><span class="st">N(-d_2)=0.1269396 in red.</span></span>
<span id="cb92-12"><a href="the-merton-model..html#cb92-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-13"><a href="the-merton-model..html#cb92-13" aria-hidden="true" tabindex="-1"></a><span class="st">N(d_2)+N(-d_2)=1&quot;</span>),</span>
<span id="cb92-14"><a href="the-merton-model..html#cb92-14" aria-hidden="true" tabindex="-1"></a><span class="at">bg =</span> <span class="st">&quot;white&quot;</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="at">cex =</span> <span class="fl">0.9</span>)</span>
<span id="cb92-15"><a href="the-merton-model..html#cb92-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> d2, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-27"></span>
<img src="index_files/figure-html/unnamed-chunk-27-1.png" alt="The red area represents the probability of default." width="672"  />
<p class="caption">
Figure 2.3: The red area represents the probability of default.
</p>
</div>
<p>Now let’s analyze the minimization that leads to <span class="math inline">\(V_0\)</span> and <span class="math inline">\(\sigma_V\)</span>. We do not have an analytic math expressions (closed form) to calculate <span class="math inline">\(V_0\)</span> and <span class="math inline">\(\sigma_V\)</span>, instead we have approximate values or estimates given the minimization of equations 24.3 and 24.4. In order to see how good this approximation is, we can retrieve the value of <span class="math inline">\([F(x,y)]^2+[G(x,y)]^2\)</span> evaluated at <span class="math inline">\(x=V_0\)</span> and <span class="math inline">\(y=\sigma_v\)</span>. This value is supposed to be positive as both <span class="math inline">\(F(x,y)\)</span> and <span class="math inline">\(G(x,y)\)</span> functions are squared, so we expect a positive number close to zero when evaluated at <span class="math inline">\(x=V_0\)</span> and <span class="math inline">\(y=\sigma_v\)</span>.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="the-merton-model..html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate how good is the minimization.</span></span>
<span id="cb93-2"><a href="the-merton-model..html#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min.footnote10</span>(<span class="at">x =</span> <span class="fu">c</span>(V0, sv))</span></code></pre></div>
<pre><code>## [1] 1.425797e-07</code></pre>
<p>The minimization conducted in the function above worked fairly well.</p>
<p>There is another way to approach how the minimization work. We can propose a graphical analysis. In particular, we can verify whether <span class="math inline">\(V_0=12.39578\)</span> and <span class="math inline">\(\sigma_V=0.2123041\)</span> minimizes the objective function. To illustrate this in two axis, we need to fix either <span class="math inline">\(V_0\)</span> or <span class="math inline">\(\sigma_V\)</span>, and evaluate <span class="math inline">\([F(x,y)]^2+[G(x,y)]^2\)</span> with different values of <span class="math inline">\(V_0\)</span> or <span class="math inline">\(\sigma_V\)</span>. Let’s do that.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="the-merton-model..html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix sv and evaluate different values of V0.</span></span>
<span id="cb95-2"><a href="the-merton-model..html#cb95-2" aria-hidden="true" tabindex="-1"></a>V0.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">4</span>, <span class="at">to =</span> <span class="dv">20</span>, <span class="at">length.out=</span><span class="dv">50</span>)</span>
<span id="cb95-3"><a href="the-merton-model..html#cb95-3" aria-hidden="true" tabindex="-1"></a>sv.rep <span class="ot">&lt;-</span> <span class="fu">rep</span>(sv, <span class="dv">50</span>)</span>
<span id="cb95-4"><a href="the-merton-model..html#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to be evaluated.</span></span>
<span id="cb95-5"><a href="the-merton-model..html#cb95-5" aria-hidden="true" tabindex="-1"></a>FG <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { (<span class="fu">eq24.3</span>(V0, sv))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="fu">eq24.4</span>(V0, sv))<span class="sc">^</span><span class="dv">2</span> }</span>
<span id="cb95-6"><a href="the-merton-model..html#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the function with fixed sv and different V0 values.</span></span>
<span id="cb95-7"><a href="the-merton-model..html#cb95-7" aria-hidden="true" tabindex="-1"></a>FG.V0 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(FG, V0.seq, sv.rep)</span></code></pre></div>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="the-merton-model..html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results.</span></span>
<span id="cb96-2"><a href="the-merton-model..html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(V0.seq, FG.V0, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[<span class="dv">0</span>])),</span>
<span id="cb96-3"><a href="the-merton-model..html#cb96-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="fu">F</span>(x,y)<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span><span class="fu">G</span>(x,y)<span class="sc">^</span><span class="dv">2</span>)), <span class="at">cex.lab =</span> <span class="fl">0.8</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb96-4"><a href="the-merton-model..html#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> V0, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb96-5"><a href="the-merton-model..html#cb96-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">FG</span>(V0, sv), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb96-6"><a href="the-merton-model..html#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(V0, <span class="fu">FG</span>(V0, sv), <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-30"></span>
<img src="index_files/figure-html/unnamed-chunk-30-1.png" alt="Here we fix the volatility of the assets and change the value of the assets at time zero. The minimization looks fine." width="672"  />
<p class="caption">
Figure 2.4: Here we fix the volatility of the assets and change the value of the assets at time zero. The minimization looks fine.
</p>
</div>
<p>Clearly the minimization worked well here. For the sake of completeness, now we fix the <span class="math inline">\(V_0\)</span> value and evaluate the function again.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="the-merton-model..html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now fix V0, and evaluate different sv values.</span></span>
<span id="cb97-2"><a href="the-merton-model..html#cb97-2" aria-hidden="true" tabindex="-1"></a>sv.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.6</span>, <span class="at">length.out =</span> <span class="dv">50</span>)</span>
<span id="cb97-3"><a href="the-merton-model..html#cb97-3" aria-hidden="true" tabindex="-1"></a>V0.rep <span class="ot">&lt;-</span> <span class="fu">rep</span>(V0, <span class="dv">50</span>)</span>
<span id="cb97-4"><a href="the-merton-model..html#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the function with these parameters.</span></span>
<span id="cb97-5"><a href="the-merton-model..html#cb97-5" aria-hidden="true" tabindex="-1"></a>FG.sv <span class="ot">&lt;-</span> <span class="fu">mapply</span>(FG, V0.rep, sv.seq)</span>
<span id="cb97-6"><a href="the-merton-model..html#cb97-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results.</span></span>
<span id="cb97-7"><a href="the-merton-model..html#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sv.seq, FG.sv, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(sigma[V])), </span>
<span id="cb97-8"><a href="the-merton-model..html#cb97-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="fu">F</span>(x, y)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">G</span>(x, y)<span class="sc">^</span><span class="dv">2</span>)), </span>
<span id="cb97-9"><a href="the-merton-model..html#cb97-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">0.8</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb97-10"><a href="the-merton-model..html#cb97-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> sv, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb97-11"><a href="the-merton-model..html#cb97-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">FG</span>(V0, sv), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb97-12"><a href="the-merton-model..html#cb97-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(sv, <span class="fu">FG</span>(V0, sv), <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-31"></span>
<img src="index_files/figure-html/unnamed-chunk-31-1.png" alt="Here we fix the value of the assets at time zero and change the volatility of the assets. The minimization looks fine." width="672"  />
<p class="caption">
Figure 2.5: Here we fix the value of the assets at time zero and change the volatility of the assets. The minimization looks fine.
</p>
</div>
<p>We can show the same as before but in a 3D plot.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="the-merton-model..html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># outer evaluates the function for each combination of the vectors.</span></span>
<span id="cb98-2"><a href="the-merton-model..html#cb98-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">outer</span>(V0.seq, sv.seq, FG) <span class="co"># z is now 50x50 matrix.</span></span>
<span id="cb98-3"><a href="the-merton-model..html#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">persp</span>(V0.seq, sv.seq, z, <span class="at">col =</span> <span class="st">&quot;springgreen&quot;</span>, <span class="at">shade =</span> <span class="dv">0</span>, <span class="at">xlab =</span> <span class="st">&quot;V0&quot;</span>,</span>
<span id="cb98-4"><a href="the-merton-model..html#cb98-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">&quot;sv&quot;</span>, <span class="at">zlab =</span> <span class="st">&quot;Probability of default&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-32"></span>
<img src="index_files/figure-html/unnamed-chunk-32-1.png" alt="Minimization of the function." width="672"  />
<p class="caption">
Figure 2.6: Minimization of the function.
</p>
</div>
<p>This green plot is nice but it is not interactive. We could plot interactive three-dimension plots with other R packages like and show them in a html context or java environment. Given that this is a PDF document, we cannot show dynamic plots (at least not yet), so we propose to use contour plots. Contour plots or level plots are a way to show a three-dimensional surface on a two-dimensional plane.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="the-merton-model..html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The nlevels is high to emphasize the minimum value in blue.</span></span>
<span id="cb99-2"><a href="the-merton-model..html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(V0.seq, sv.seq, z, <span class="at">xlab =</span> <span class="st">&quot;V0&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;sv&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">nlevels =</span> <span class="dv">300</span>)</span>
<span id="cb99-3"><a href="the-merton-model..html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(V0, sv, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="index_files/figure-html/unnamed-chunk-33-1.png" alt="Minimization of the function: a contour view." width="672"  />
<p class="caption">
Figure 2.7: Minimization of the function: a contour view.
</p>
</div>
<p>The following plot cannot be seen in a PDF output, but it can be seen in a browser as an interactive plot.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="the-merton-model..html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb100-2"><a href="the-merton-model..html#cb100-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">plot_ly</span>(<span class="at">x =</span> V0.seq, <span class="at">y =</span> sv.seq, <span class="at">z =</span> z, <span class="at">type =</span> <span class="st">&quot;surface&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb100-3"><a href="the-merton-model..html#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(</span>
<span id="cb100-4"><a href="the-merton-model..html#cb100-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">&quot;Minimization of f at V0=12.395 an sv=0.212&quot;</span>,</span>
<span id="cb100-5"><a href="the-merton-model..html#cb100-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">scene =</span> <span class="fu">list</span>(<span class="at">xaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">&quot;V0&quot;</span>), <span class="at">yaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">&quot;sv&quot;</span>),</span>
<span id="cb100-6"><a href="the-merton-model..html#cb100-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">zaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">&quot;f=F^2+G^2&quot;</span>))) </span>
<span id="cb100-7"><a href="the-merton-model..html#cb100-7" aria-hidden="true" tabindex="-1"></a><span class="fu">add_markers</span>(p, <span class="at">x =</span> <span class="fl">12.3957765</span>, <span class="at">y =</span> <span class="fl">0.2123041</span>, <span class="at">z =</span> <span class="dv">0</span>, <span class="at">inherit =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>The Merton model allows us to calculate more values in this credit risk assessment.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="the-merton-model..html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Other results in the Merton&#39;s model.</span></span>
<span id="cb101-2"><a href="the-merton-model..html#cb101-2" aria-hidden="true" tabindex="-1"></a>market_value_debt <span class="ot">&lt;-</span> V0 <span class="sc">-</span> E0</span>
<span id="cb101-3"><a href="the-merton-model..html#cb101-3" aria-hidden="true" tabindex="-1"></a>pv_promised_payment_debt <span class="ot">&lt;-</span> D <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>rf <span class="sc">*</span> TT)</span>
<span id="cb101-4"><a href="the-merton-model..html#cb101-4" aria-hidden="true" tabindex="-1"></a>Expected_Loss <span class="ot">&lt;-</span> (pv_promised_payment_debt <span class="sc">-</span> market_value_debt) <span class="sc">/</span></span>
<span id="cb101-5"><a href="the-merton-model..html#cb101-5" aria-hidden="true" tabindex="-1"></a>  pv_promised_payment_debt</span>
<span id="cb101-6"><a href="the-merton-model..html#cb101-6" aria-hidden="true" tabindex="-1"></a>recovery_rate <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (Expected_Loss <span class="sc">/</span> pd)</span>
<span id="cb101-7"><a href="the-merton-model..html#cb101-7" aria-hidden="true" tabindex="-1"></a>ans <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(market_value_debt, pv_promised_payment_debt, </span>
<span id="cb101-8"><a href="the-merton-model..html#cb101-8" aria-hidden="true" tabindex="-1"></a>                  Expected_Loss, recovery_rate, pd)</span>
<span id="cb101-9"><a href="the-merton-model..html#cb101-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">t</span>(ans), <span class="at">caption =</span> <span class="st">&quot;Other results in the Merton&#39;s model.&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-35">Table 2.5: </span>Other results in the Merton’s model.</caption>
<tbody>
<tr class="odd">
<td align="left">market_value_debt</td>
<td align="right">9.3957765</td>
</tr>
<tr class="even">
<td align="left">pv_promised_payment_debt</td>
<td align="right">9.5122942</td>
</tr>
<tr class="odd">
<td align="left">Expected_Loss</td>
<td align="right">0.0122492</td>
</tr>
<tr class="even">
<td align="left">recovery_rate</td>
<td align="right">0.9035039</td>
</tr>
<tr class="odd">
<td align="left">pd</td>
<td align="right">0.1269396</td>
</tr>
</tbody>
</table>
<p>Could we figure out the implied bond yield spread? It would be similar to the fair interest rate that this firm has to pay given its probability of default and recovery rate. Take Hull’s equation 24.2 as a reference: <span class="math inline">\(\lambda(T)=S(T)/(1-R)\)</span> and solve for <span class="math inline">\(S(T)\)</span>: <span class="math inline">\(S(T)=\lambda(T)\times(1-R)\)</span>, so <span class="math inline">\(S(T)=(0.12693963)\times(1-0.90350393)\)</span>. This is 122.4918 basis points more than the risk-free rate. Then, with five parameters we can calculate (among other things) the firm’s probability of default and the correspondent yield spread of this firm’s bond. It would be interesting to compare this value with the market yield spread and evaluate whether the market yield is over or underestimated according to our theoretical value.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="the-merton-model..html#cb102-1" aria-hidden="true" tabindex="-1"></a>spread <span class="ot">&lt;-</span> <span class="cf">function</span>(E0, se, rf, TT, D) { </span>
<span id="cb102-2"><a href="the-merton-model..html#cb102-2" aria-hidden="true" tabindex="-1"></a>  eq24<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb102-3"><a href="the-merton-model..html#cb102-3" aria-hidden="true" tabindex="-1"></a>  ((V0 <span class="sc">*</span> <span class="fu">pnorm</span>((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span></span>
<span id="cb102-4"><a href="the-merton-model..html#cb102-4" aria-hidden="true" tabindex="-1"></a>  D <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>rf <span class="sc">*</span> TT) <span class="sc">*</span> <span class="fu">pnorm</span>(((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span></span>
<span id="cb102-5"><a href="the-merton-model..html#cb102-5" aria-hidden="true" tabindex="-1"></a>  (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)) <span class="sc">-</span> E0)) }</span>
<span id="cb102-6"><a href="the-merton-model..html#cb102-6" aria-hidden="true" tabindex="-1"></a>eq24<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb102-7"><a href="the-merton-model..html#cb102-7" aria-hidden="true" tabindex="-1"></a>  ((<span class="fu">pnorm</span>((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">*</span></span>
<span id="cb102-8"><a href="the-merton-model..html#cb102-8" aria-hidden="true" tabindex="-1"></a>      sv <span class="sc">*</span> V0 <span class="sc">-</span> se <span class="sc">*</span> E0)) }</span>
<span id="cb102-9"><a href="the-merton-model..html#cb102-9" aria-hidden="true" tabindex="-1"></a>  min.footnote10 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) </span>
<span id="cb102-10"><a href="the-merton-model..html#cb102-10" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">eq24.3</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>]))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="fu">eq24.4</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>]))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb102-11"><a href="the-merton-model..html#cb102-11" aria-hidden="true" tabindex="-1"></a>V0_sv <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), min.footnote10)</span>
<span id="cb102-12"><a href="the-merton-model..html#cb102-12" aria-hidden="true" tabindex="-1"></a>V0 <span class="ot">&lt;-</span> V0_sv<span class="sc">$</span>par[<span class="dv">1</span>]</span>
<span id="cb102-13"><a href="the-merton-model..html#cb102-13" aria-hidden="true" tabindex="-1"></a>sv <span class="ot">&lt;-</span> V0_sv<span class="sc">$</span>par[<span class="dv">2</span>]</span>
<span id="cb102-14"><a href="the-merton-model..html#cb102-14" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="sc">-</span>(((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span></span>
<span id="cb102-15"><a href="the-merton-model..html#cb102-15" aria-hidden="true" tabindex="-1"></a>          (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)))</span>
<span id="cb102-16"><a href="the-merton-model..html#cb102-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-17"><a href="the-merton-model..html#cb102-17" aria-hidden="true" tabindex="-1"></a>market_value_debt <span class="ot">&lt;-</span> V0 <span class="sc">-</span> E0</span>
<span id="cb102-18"><a href="the-merton-model..html#cb102-18" aria-hidden="true" tabindex="-1"></a>pv_promised_payment_debt <span class="ot">&lt;-</span> D <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>rf <span class="sc">*</span> TT)</span>
<span id="cb102-19"><a href="the-merton-model..html#cb102-19" aria-hidden="true" tabindex="-1"></a>Expected_Loss <span class="ot">&lt;-</span> (pv_promised_payment_debt <span class="sc">-</span> market_value_debt) <span class="sc">/</span></span>
<span id="cb102-20"><a href="the-merton-model..html#cb102-20" aria-hidden="true" tabindex="-1"></a>  pv_promised_payment_debt</span>
<span id="cb102-21"><a href="the-merton-model..html#cb102-21" aria-hidden="true" tabindex="-1"></a>recovery_rate <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (Expected_Loss <span class="sc">/</span> pd)</span>
<span id="cb102-22"><a href="the-merton-model..html#cb102-22" aria-hidden="true" tabindex="-1"></a>spread <span class="ot">&lt;-</span> pd <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>recovery_rate)</span>
<span id="cb102-23"><a href="the-merton-model..html#cb102-23" aria-hidden="true" tabindex="-1"></a>spread</span>
<span id="cb102-24"><a href="the-merton-model..html#cb102-24" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="the-merton-model..html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spread</span>(<span class="at">E0 =</span> <span class="dv">3</span>, <span class="at">se =</span> <span class="fl">0.8</span>, <span class="at">rf =</span> <span class="fl">0.05</span>, <span class="at">TT =</span> <span class="dv">1</span>, <span class="at">D =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## [1] 0.01224917</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="the-merton-model..html#cb105-1" aria-hidden="true" tabindex="-1"></a>x.T <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">10</span>, <span class="fl">0.5</span>)</span>
<span id="cb105-2"><a href="the-merton-model..html#cb105-2" aria-hidden="true" tabindex="-1"></a>spread.T <span class="ot">&lt;-</span> <span class="fu">mapply</span>(spread, <span class="at">E0 =</span> <span class="dv">3</span>, <span class="at">se =</span> <span class="fl">0.8</span>, <span class="at">rf =</span> <span class="fl">0.05</span>, x.T, <span class="at">D =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="the-merton-model..html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(x.T, spread.T)</span></code></pre></div>
<pre><code>##     x.T    spread.T
## 1   0.5 0.001436993
## 2   1.0 0.012249175
## 3   1.5 0.034639827
## 4   2.0 0.067649103
## 5   2.5 0.109582247
## 6   3.0 0.158117325
## 7   3.5 0.210872346
## 8   4.0 0.265378322
## 9   4.5 0.319998224
## 10  5.0 0.373117588
## 11  5.5 0.423629820
## 12  6.0 0.470524979
## 13  6.5 0.514157658
## 14  7.0 0.553779756
## 15  7.5 0.590028475
## 16  8.0 0.622657593
## 17  8.5 0.652347129
## 18  9.0 0.678931474
## 19  9.5 0.702941509
## 20 10.0 0.724762411</code></pre>
</div>
<div id="inside-view-of-the-mertons-model." class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Inside view of the Merton’s model.<a href="the-merton-model..html#inside-view-of-the-mertons-model." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The model assumes that the assets follow a geometric Brownian stochastic process. Let’s assume the daily evolution of the market value of the firm assets over a year. Here are 10 simulated paths of <span class="math inline">\(V_t\)</span> from <span class="math inline">\(t=t,...,T\)</span>. The reference of this section is Chapter 14 and 15 (John C. Hull).</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="the-merton-model..html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merton assumes V follows a geometric brownian motion process.</span></span>
<span id="cb108-2"><a href="the-merton-model..html#cb108-2" aria-hidden="true" tabindex="-1"></a>V0.sim <span class="ot">&lt;-</span> <span class="cf">function</span>(i) {  <span class="co"># the argument i is not used here.</span></span>
<span id="cb108-3"><a href="the-merton-model..html#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">GBM</span>(<span class="at">N =</span> <span class="dv">365</span>, <span class="at">T =</span> <span class="dv">1</span>, <span class="at">t0 =</span> <span class="dv">0</span>, <span class="at">x0 =</span> V0, <span class="at">theta =</span> <span class="fl">0.05</span>, <span class="at">sigma =</span> sv)</span>
<span id="cb108-4"><a href="the-merton-model..html#cb108-4" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb108-5"><a href="the-merton-model..html#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>) <span class="co"># Reproducibility  </span></span>
<span id="cb108-6"><a href="the-merton-model..html#cb108-6" aria-hidden="true" tabindex="-1"></a>paths <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, V0.sim) <span class="co"># Create 10 paths for V.</span></span>
<span id="cb108-7"><a href="the-merton-model..html#cb108-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot results.</span></span>
<span id="cb108-8"><a href="the-merton-model..html#cb108-8" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(paths, <span class="at">type =</span><span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb108-9"><a href="the-merton-model..html#cb108-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb108-10"><a href="the-merton-model..html#cb108-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb108-11"><a href="the-merton-model..html#cb108-11" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="index_files/figure-html/unnamed-chunk-40-1.png" alt="Simulation of 10 paths of the assets." width="672"  />
<p class="caption">
Figure 2.8: Simulation of 10 paths of the assets.
</p>
</div>
<p>These simulations can be interpreted as the evolution of the value of the firm’s assets in 10 parallel universes. In the past, some students have called this figure <em>la grafica de los pelitos</em>, this is OK as long as you understand the figure implications. The right name is 10 simulated geometric brownian processes. Let’s count the cases in which <span class="math inline">\(V_t&lt;D\)</span> note that here I use <span class="math inline">\(t\)</span> and not <span class="math inline">\(T\)</span>, so we are counting the cases in which at least at some time <span class="math inline">\(t\)</span> the value of the assets were lower than 10.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="the-merton-model..html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Which path went lower than D?</span></span>
<span id="cb109-2"><a href="the-merton-model..html#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">colSums</span>(paths <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 2 4 9</code></pre>
<p>The value of the assets was lower than $10 at some time in the second, fourth and ninth alternate universes. Let’s plot these cases.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="the-merton-model..html#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There might be an easier way to select these cases.</span></span>
<span id="cb111-2"><a href="the-merton-model..html#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(paths[,<span class="fu">which</span>(<span class="fu">colSums</span>(paths <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">&gt;</span> <span class="dv">0</span>)], <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb111-3"><a href="the-merton-model..html#cb111-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;green&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb111-4"><a href="the-merton-model..html#cb111-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb111-5"><a href="the-merton-model..html#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb111-6"><a href="the-merton-model..html#cb111-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-42"></span>
<img src="index_files/figure-html/unnamed-chunk-42-1.png" alt="Note that the blue path finally did not default. Recovery is possible as in the real life." width="672"  />
<p class="caption">
Figure 2.9: Note that the blue path finally did not default. Recovery is possible as in the real life.
</p>
</div>
<p>The blue path was lower than 10 at some time, but at <span class="math inline">\(t=T\)</span> it is clearly higher than 10. For this reason, the blue path does not represent a firm’s default. See how the assets are not high enough to pay the debt at maturity only in two cases: green and red. Thus, according to this simulation the probability of default is 20%. Here is how we can calculate the cases in which <span class="math inline">\(V_T&lt;D\)</span>.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="the-merton-model..html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(paths[<span class="dv">366</span>,] <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">/</span> <span class="dv">10</span></span></code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<p>The probability of default of 20% can be disappointing because it is significantly higher than 0.12693963. This is because the number of simulations is small. The following examples show how these values tend to converge as we increase the number of simulations from 100 to 100,000.</p>
<p>Here are 100 simulated paths of <span class="math inline">\(V_0\)</span> to <span class="math inline">\(V_T\)</span>.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="the-merton-model..html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>) <span class="co"># Reproducibility  </span></span>
<span id="cb114-2"><a href="the-merton-model..html#cb114-2" aria-hidden="true" tabindex="-1"></a>paths <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, V0.sim) <span class="co"># Create 100 paths.</span></span>
<span id="cb114-3"><a href="the-merton-model..html#cb114-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot results.</span></span>
<span id="cb114-4"><a href="the-merton-model..html#cb114-4" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(paths, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb114-5"><a href="the-merton-model..html#cb114-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb114-6"><a href="the-merton-model..html#cb114-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb114-7"><a href="the-merton-model..html#cb114-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-44"></span>
<img src="index_files/figure-html/unnamed-chunk-44-1.png" alt="Simulation of 100 paths of the assets." width="672"  />
<p class="caption">
Figure 2.10: Simulation of 100 paths of the assets.
</p>
</div>
<p>Given the simulation above, the probability of default is 17%. This is closer to 12.693963%.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="the-merton-model..html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(paths[<span class="dv">366</span>,] <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">/</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 0.17</code></pre>
<p>Let’s see all the 17 cases that end in default.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="the-merton-model..html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co"># These are the 17 default cases.</span></span>
<span id="cb117-2"><a href="the-merton-model..html#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(paths[,<span class="fu">which</span>(paths[<span class="dv">366</span>,] <span class="sc">&lt;</span> <span class="dv">10</span>)], <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb117-3"><a href="the-merton-model..html#cb117-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), </span>
<span id="cb117-4"><a href="the-merton-model..html#cb117-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb117-5"><a href="the-merton-model..html#cb117-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb117-6"><a href="the-merton-model..html#cb117-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-46"></span>
<img src="index_files/figure-html/unnamed-chunk-46-1.png" alt="Default cases." width="672"  />
<p class="caption">
Figure 2.11: Default cases.
</p>
</div>
<p>Now, let’s see the 11 cases in which <span class="math inline">\(V_t\)</span> eventually went lower than $10 but at the end did not default.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="the-merton-model..html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># V_t &lt; 10</span></span>
<span id="cb118-2"><a href="the-merton-model..html#cb118-2" aria-hidden="true" tabindex="-1"></a>almost_default <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colSums</span>(paths <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb118-3"><a href="the-merton-model..html#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="co"># V_T &lt; 10</span></span>
<span id="cb118-4"><a href="the-merton-model..html#cb118-4" aria-hidden="true" tabindex="-1"></a>default <span class="ot">&lt;-</span> <span class="fu">which</span>((paths[<span class="dv">366</span>,] <span class="sc">&lt;</span> <span class="dv">10</span>))</span>
<span id="cb118-5"><a href="the-merton-model..html#cb118-5" aria-hidden="true" tabindex="-1"></a><span class="co"># There should be an easier way to do this:</span></span>
<span id="cb118-6"><a href="the-merton-model..html#cb118-6" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(paths[,almost_default[<span class="fu">which</span>(almost_default <span class="sc">%in%</span> default <span class="sc">==</span> <span class="cn">FALSE</span>)]], </span>
<span id="cb118-7"><a href="the-merton-model..html#cb118-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>), <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>, </span>
<span id="cb118-8"><a href="the-merton-model..html#cb118-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb118-9"><a href="the-merton-model..html#cb118-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb118-10"><a href="the-merton-model..html#cb118-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-47"></span>
<img src="index_files/figure-html/unnamed-chunk-47-1.png" alt="All these paths went lower than 10 at some point, but at the end the value of the assets are higher than 10. These are paralell universes in which the firm finally survived after some drama." width="672"  />
<p class="caption">
Figure 2.12: All these paths went lower than 10 at some point, but at the end the value of the assets are higher than 10. These are paralell universes in which the firm finally survived after some drama.
</p>
</div>
<p>What if the asset value is decreasing over time <span class="math inline">\(V_t \leq V_0\)</span>? Just as in the case of a physical assets that depreciates over time. What if we are interested in evaluating <span class="math inline">\(V_t&lt;D\)</span> at any time, not only at maturity? Ideally, we should consider an alternative to the geometric brownian motion stochastic process in order to conduct our simulation analysis. However, we could consider a shortcut. This is, take the same GBM stochastic process and filter those paths which are <span class="math inline">\(V_t \leq V_0\)</span>. There are some minor pitfalls here. For example, we still have some paths which show a decrease and then an increase. Those cases can be interpreted as if the depreciation is lower than an asset value increase. In any case, our approach delivers paths which never lead to an asset value higher than <span class="math inline">\(V_0\)</span>.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="the-merton-model..html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>) <span class="co"># Reproducibility </span></span>
<span id="cb119-2"><a href="the-merton-model..html#cb119-2" aria-hidden="true" tabindex="-1"></a>paths <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, V0.sim) <span class="co"># Create 100 paths.</span></span>
<span id="cb119-3"><a href="the-merton-model..html#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select those paths with all 366 values lower or equal than V0.</span></span>
<span id="cb119-4"><a href="the-merton-model..html#cb119-4" aria-hidden="true" tabindex="-1"></a>select.paths <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colSums</span>(paths <span class="sc">&lt;=</span> V0) <span class="sc">==</span> <span class="dv">366</span>)</span>
<span id="cb119-5"><a href="the-merton-model..html#cb119-5" aria-hidden="true" tabindex="-1"></a>new.paths <span class="ot">&lt;-</span> paths[,select.paths]</span>
<span id="cb119-6"><a href="the-merton-model..html#cb119-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot.</span></span>
<span id="cb119-7"><a href="the-merton-model..html#cb119-7" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(new.paths,</span>
<span id="cb119-8"><a href="the-merton-model..html#cb119-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>), <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb119-9"><a href="the-merton-model..html#cb119-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), </span>
<span id="cb119-10"><a href="the-merton-model..html#cb119-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb119-11"><a href="the-merton-model..html#cb119-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb119-12"><a href="the-merton-model..html#cb119-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-48-1.png" width="672"  /></p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="the-merton-model..html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability</span></span>
<span id="cb120-2"><a href="the-merton-model..html#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(new.paths <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">/</span> <span class="fu">length</span>(new.paths)</span></code></pre></div>
<pre><code>## [1] 0.4754098</code></pre>
<p>Here, only path number 49 out of 100 meet our condition. This path meets <span class="math inline">\(V_t&lt;D\)</span> in 47.54098% of the cases. Let’s increase the number of simulations because 100 was apparently rather small. With 1,000 simulations the probability is 43.23445%. Let’s see the case of 10,000 simulations.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="the-merton-model..html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>) <span class="co"># Reproducibility </span></span>
<span id="cb122-2"><a href="the-merton-model..html#cb122-2" aria-hidden="true" tabindex="-1"></a>paths <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>, V0.sim) <span class="co"># Create 10,000 paths.</span></span>
<span id="cb122-3"><a href="the-merton-model..html#cb122-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select those paths with all 366 values lower or equal than V0.</span></span>
<span id="cb122-4"><a href="the-merton-model..html#cb122-4" aria-hidden="true" tabindex="-1"></a>select.paths <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colSums</span>(paths <span class="sc">&lt;=</span> V0) <span class="sc">==</span> <span class="dv">366</span>)</span>
<span id="cb122-5"><a href="the-merton-model..html#cb122-5" aria-hidden="true" tabindex="-1"></a>new.paths <span class="ot">&lt;-</span> paths[,select.paths]</span>
<span id="cb122-6"><a href="the-merton-model..html#cb122-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot.</span></span>
<span id="cb122-7"><a href="the-merton-model..html#cb122-7" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(new.paths,</span>
<span id="cb122-8"><a href="the-merton-model..html#cb122-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>), <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb122-9"><a href="the-merton-model..html#cb122-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(V[t])), </span>
<span id="cb122-10"><a href="the-merton-model..html#cb122-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Time in days (0 to T)&quot;</span>)</span>
<span id="cb122-11"><a href="the-merton-model..html#cb122-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> D, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb122-12"><a href="the-merton-model..html#cb122-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, V0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-49-1.png" width="672"  /></p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="the-merton-model..html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability</span></span>
<span id="cb123-2"><a href="the-merton-model..html#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(new.paths <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">/</span> <span class="fu">length</span>(new.paths)</span></code></pre></div>
<pre><code>## [1] 0.3596873</code></pre>
<p>Now the probability is 35.96873%. We can consider this one as the final result for our purposes.</p>
<p>Here are 100,000 simulated <span class="math inline">\(V_T\)</span> showed in a histogram. The reference for this section is 15.1 (John C. Hull). Note that instead of drawing the complete paths, we can directly get the distribution of <span class="math inline">\(V_T\)</span>. The resulting distribution is log-normal.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="the-merton-model..html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">13</span>)</span>
<span id="cb125-2"><a href="the-merton-model..html#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 100,000 values of VT at once.</span></span>
<span id="cb125-3"><a href="the-merton-model..html#cb125-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Here, I added a TT value twice. This was not a mistake, because in the tutorial this value was equal to one. However, my students are trying with different maturities. For a formal reference please see equation 15.3 in Hull.</span></span>
<span id="cb125-4"><a href="the-merton-model..html#cb125-4" aria-hidden="true" tabindex="-1"></a>VT <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">rnorm</span>(<span class="dv">100000</span>, <span class="fu">log</span>(V0) <span class="sc">+</span> (<span class="fl">0.05</span> <span class="sc">-</span> (sv<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span>)<span class="sc">*</span>TT, sv<span class="sc">*</span><span class="fu">sqrt</span>(TT)))</span>
<span id="cb125-5"><a href="the-merton-model..html#cb125-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot results.</span></span>
<span id="cb125-6"><a href="the-merton-model..html#cb125-6" aria-hidden="true" tabindex="-1"></a><span class="co"># You may need to change the 100 if colors do not show properly. Sometimes this value is too high and bins are so many that it looks all black.</span></span>
<span id="cb125-7"><a href="the-merton-model..html#cb125-7" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">hist</span>(VT, <span class="dv">100</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb125-8"><a href="the-merton-model..html#cb125-8" aria-hidden="true" tabindex="-1"></a>ccat <span class="ot">&lt;-</span> <span class="fu">cut</span>(h<span class="sc">$</span>breaks, <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, D, <span class="cn">Inf</span>))</span>
<span id="cb125-9"><a href="the-merton-model..html#cb125-9" aria-hidden="true" tabindex="-1"></a><span class="co"># You may also need to change the xlim if a big red square appears as changes in maturity may imply larger values of VT. I recommend trying without xlim and see.</span></span>
<span id="cb125-10"><a href="the-merton-model..html#cb125-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(h, <span class="at">main =</span> <span class="cn">NULL</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>)[ccat], </span>
<span id="cb125-11"><a href="the-merton-model..html#cb125-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Value of the assets at maturity&quot;</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">30</span>))</span>
<span id="cb125-12"><a href="the-merton-model..html#cb125-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, </span>
<span id="cb125-13"><a href="the-merton-model..html#cb125-13" aria-hidden="true" tabindex="-1"></a><span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;The red area is 12.657%, and represents</span></span>
<span id="cb125-14"><a href="the-merton-model..html#cb125-14" aria-hidden="true" tabindex="-1"></a><span class="st">the simulated probability of default.</span></span>
<span id="cb125-15"><a href="the-merton-model..html#cb125-15" aria-hidden="true" tabindex="-1"></a><span class="st">The probability of default of the model</span></span>
<span id="cb125-16"><a href="the-merton-model..html#cb125-16" aria-hidden="true" tabindex="-1"></a><span class="st">following the textbook example is </span></span>
<span id="cb125-17"><a href="the-merton-model..html#cb125-17" aria-hidden="true" tabindex="-1"></a><span class="st">N(-d_2)=12.69396%. As we can see,</span></span>
<span id="cb125-18"><a href="the-merton-model..html#cb125-18" aria-hidden="true" tabindex="-1"></a><span class="st">both are very close.&quot;</span>),</span>
<span id="cb125-19"><a href="the-merton-model..html#cb125-19" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">19</span>), <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-50"></span>
<img src="index_files/figure-html/unnamed-chunk-50-1.png" alt="Histogram of 100,000 values of the assets at maturity." width="672"  />
<p class="caption">
Figure 2.13: Histogram of 100,000 values of the assets at maturity.
</p>
</div>
<p>The probability of default can be calculated as:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="the-merton-model..html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(VT <span class="sc">&lt;</span> <span class="dv">10</span>) <span class="sc">/</span> <span class="dv">100000</span></span></code></pre></div>
<pre><code>## [1] 0.12657</code></pre>
<p>Note that 0.12657 is now much closer than 0.12693963. Convergence achieved.</p>
<p>This firm can be represented as an European call option payoff. The payoff of a typical stock option is <span class="math inline">\(c=max(S_T-K, 0)\)</span> or equivalently in terms of Merton’s model: <span class="math inline">\(E_T=max(V_T-D, 0)\)</span>.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="the-merton-model..html#cb128-1" aria-hidden="true" tabindex="-1"></a>ET <span class="ot">&lt;-</span> <span class="fu">pmax</span>(VT <span class="sc">-</span> D, <span class="dv">0</span>) <span class="co"># payoff function of a typical call option.</span></span>
<span id="cb128-2"><a href="the-merton-model..html#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">sort</span>(VT), <span class="fu">sort</span>(ET), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">lwd =</span> <span class="dv">4</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">20</span>), </span>
<span id="cb128-3"><a href="the-merton-model..html#cb128-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), <span class="at">xlab =</span> <span class="st">&quot;Simulated assets at maturity (V_T)&quot;</span>,</span>
<span id="cb128-4"><a href="the-merton-model..html#cb128-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span><span class="st">&quot;Simulated equity at maturity (E_T)&quot;</span>)</span>
<span id="cb128-5"><a href="the-merton-model..html#cb128-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">10</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb128-6"><a href="the-merton-model..html#cb128-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;right&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;E_T=max(V_T-D,0). Given the</span></span>
<span id="cb128-7"><a href="the-merton-model..html#cb128-7" aria-hidden="true" tabindex="-1"></a><span class="st">simulation, E_T=0 happens in </span></span>
<span id="cb128-8"><a href="the-merton-model..html#cb128-8" aria-hidden="true" tabindex="-1"></a><span class="st">12.657% of the cases.</span></span>
<span id="cb128-9"><a href="the-merton-model..html#cb128-9" aria-hidden="true" tabindex="-1"></a><span class="st">According to the model, E_T=0</span></span>
<span id="cb128-10"><a href="the-merton-model..html#cb128-10" aria-hidden="true" tabindex="-1"></a><span class="st">happens in 12.69396% of the </span></span>
<span id="cb128-11"><a href="the-merton-model..html#cb128-11" aria-hidden="true" tabindex="-1"></a><span class="st">cases.&quot;</span>),</span>
<span id="cb128-12"><a href="the-merton-model..html#cb128-12" aria-hidden="true" tabindex="-1"></a><span class="at">bg =</span> <span class="st">&quot;white&quot;</span>, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>, <span class="at">cex =</span> <span class="fl">0.7</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-52"></span>
<img src="index_files/figure-html/unnamed-chunk-52-1.png" alt="A view of the firm's balance sheet in the future. Looks like a typical European call option payoff." width="672"  />
<p class="caption">
Figure 2.14: A view of the firm’s balance sheet in the future. Looks like a typical European call option payoff.
</p>
</div>
<p>This diagram show the relevant balance sheet accounts in the future, at maturity. This is because the <span class="math inline">\(E_T\)</span> is a function of <span class="math inline">\(V_T\)</span> and <span class="math inline">\(D\)</span>. As long as <span class="math inline">\(V_T&lt;D\)</span>, then the value of <span class="math inline">\(E_T=0\)</span>. Otherwise, the value of <span class="math inline">\(E_T= V_T-D\)</span>, just as the accounting equation suggest but in future terms. Note that the Merton’s model say nothing about the estimate value of <span class="math inline">\(E_T\)</span>, instead we have an estimate about how likely is that <span class="math inline">\(V_T&lt;D\)</span>, or in other words how likely is that <span class="math inline">\(E_T&lt;0\)</span>.</p>
<p>Then, we know that <span class="math inline">\(E_T= max(V_T-D, 0)\)</span>. The Black???Scholes???Merton formula can also estimate the theoretical value of <span class="math inline">\(E_0\)</span>. This is, if the observable market value given by the market capitalization available in any financial site is <span class="math inline">\(E_0=3\)</span>, we can retrieve the theoretical value of <span class="math inline">\(E_0\)</span> so we can compare whether the firm observable market value is over or undervalued. In other words, the Black-Scholes-Merton model can give us an estimate of the firm value. In particular, the model gives the value of the equity today as:</p>
<p><span class="math inline">\(E_0=V_0N(d_1)-De^{-rT}N(d_2)\)</span></p>
<p>This is equation 24.3 in Hull. To estimate <span class="math inline">\(E_0\)</span>, we need <span class="math inline">\(V_0\)</span> and <span class="math inline">\(\sigma_V\)</span> and these two values were already estimated before with the implementation of the min.footnote10 function above. It is true that this minimization requires <span class="math inline">\(E_0\)</span>, the point here is to use the observable market capitalization <span class="math inline">\(E_0=3\)</span> to find out the unobsevable <span class="math inline">\(V_0\)</span> and <span class="math inline">\(\sigma_V\)</span> and then estimate the theoretical value of <span class="math inline">\(E_0\)</span>.</p>
<p>The code is:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="the-merton-model..html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Black-Scholes call.</span></span>
<span id="cb129-2"><a href="the-merton-model..html#cb129-2" aria-hidden="true" tabindex="-1"></a>E0.theo <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, D, rf, TT, sv) {</span>
<span id="cb129-3"><a href="the-merton-model..html#cb129-3" aria-hidden="true" tabindex="-1"></a>  d1 <span class="ot">&lt;-</span> (<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))</span>
<span id="cb129-4"><a href="the-merton-model..html#cb129-4" aria-hidden="true" tabindex="-1"></a>  d2 <span class="ot">&lt;-</span> d1 <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)</span>
<span id="cb129-5"><a href="the-merton-model..html#cb129-5" aria-hidden="true" tabindex="-1"></a>  c <span class="ot">&lt;-</span> V0 <span class="sc">*</span> <span class="fu">pnorm</span>(d1) <span class="sc">-</span> D <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>rf <span class="sc">*</span> TT) <span class="sc">*</span> <span class="fu">pnorm</span>(d2)</span>
<span id="cb129-6"><a href="the-merton-model..html#cb129-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb129-7"><a href="the-merton-model..html#cb129-7" aria-hidden="true" tabindex="-1"></a>V0 <span class="ot">&lt;-</span> <span class="fl">12.39578</span> <span class="co"># Assets.</span></span>
<span id="cb129-8"><a href="the-merton-model..html#cb129-8" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># Debt.</span></span>
<span id="cb129-9"><a href="the-merton-model..html#cb129-9" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co"># Risk-free rate.</span></span>
<span id="cb129-10"><a href="the-merton-model..html#cb129-10" aria-hidden="true" tabindex="-1"></a>TT <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co"># Maturity.</span></span>
<span id="cb129-11"><a href="the-merton-model..html#cb129-11" aria-hidden="true" tabindex="-1"></a>sv <span class="ot">&lt;-</span> <span class="fl">0.2123041</span> <span class="co"># Volatility of assets.</span></span>
<span id="cb129-12"><a href="the-merton-model..html#cb129-12" aria-hidden="true" tabindex="-1"></a>(<span class="fu">E0.theo</span>(V0, D, rf, TT, sv))</span></code></pre></div>
<pre><code>## [1] 3.000357</code></pre>
<p>Then, we can argue that the market value of the firm is slightly undervalued since the theoretical value of the firm is 3.000357 compared with 3. This approach opens the possibility to value firms. It also opens the possibility to compare the book value in the Balance sheet of the total assets versus the estimate <span class="math inline">\(V_0\)</span>. This will allow us to understand the difference between book value and market value of the assets, not only of the equity. We can even implement a similar analysis about the market value of the debt just as we did before.</p>
</div>
<div id="the-probability-of-default-as-a-function-of-some-parameters." class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> The probability of default as a function of some parameters.<a href="the-merton-model..html#the-probability-of-default-as-a-function-of-some-parameters." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can expand our analysis by evaluating how changes in parameters change the probability of default in the context of the Merton model. This is interesting because we can move from estimating a probability of default to propose changes in the firm’s parameters like the capital structure to reduce a firm’s probability of default. First, we need the probability of default as a function.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="the-merton-model..html#cb131-1" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="cf">function</span>(E0, se, rf, TT, D) { </span>
<span id="cb131-2"><a href="the-merton-model..html#cb131-2" aria-hidden="true" tabindex="-1"></a>  eq24<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb131-3"><a href="the-merton-model..html#cb131-3" aria-hidden="true" tabindex="-1"></a>  ((V0 <span class="sc">*</span> <span class="fu">pnorm</span>((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span></span>
<span id="cb131-4"><a href="the-merton-model..html#cb131-4" aria-hidden="true" tabindex="-1"></a>  D <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>rf <span class="sc">*</span> TT) <span class="sc">*</span> <span class="fu">pnorm</span>(((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span></span>
<span id="cb131-5"><a href="the-merton-model..html#cb131-5" aria-hidden="true" tabindex="-1"></a>  (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)) <span class="sc">-</span> E0)) }</span>
<span id="cb131-6"><a href="the-merton-model..html#cb131-6" aria-hidden="true" tabindex="-1"></a>eq24<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(V0, sv) { </span>
<span id="cb131-7"><a href="the-merton-model..html#cb131-7" aria-hidden="true" tabindex="-1"></a>  ((<span class="fu">pnorm</span>((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span> (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">*</span></span>
<span id="cb131-8"><a href="the-merton-model..html#cb131-8" aria-hidden="true" tabindex="-1"></a>      sv <span class="sc">*</span> V0 <span class="sc">-</span> se <span class="sc">*</span> E0)) }</span>
<span id="cb131-9"><a href="the-merton-model..html#cb131-9" aria-hidden="true" tabindex="-1"></a>  min.footnote10 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) </span>
<span id="cb131-10"><a href="the-merton-model..html#cb131-10" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">eq24.3</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>]))<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (<span class="fu">eq24.4</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>]))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb131-11"><a href="the-merton-model..html#cb131-11" aria-hidden="true" tabindex="-1"></a>V0_sv <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), min.footnote10)</span>
<span id="cb131-12"><a href="the-merton-model..html#cb131-12" aria-hidden="true" tabindex="-1"></a>V0 <span class="ot">&lt;-</span> V0_sv<span class="sc">$</span>par[<span class="dv">1</span>]</span>
<span id="cb131-13"><a href="the-merton-model..html#cb131-13" aria-hidden="true" tabindex="-1"></a>sv <span class="ot">&lt;-</span> V0_sv<span class="sc">$</span>par[<span class="dv">2</span>]</span>
<span id="cb131-14"><a href="the-merton-model..html#cb131-14" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="sc">-</span>(((<span class="fu">log</span>(V0 <span class="sc">/</span> D) <span class="sc">+</span> (rf <span class="sc">+</span> sv<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> TT) <span class="sc">/</span></span>
<span id="cb131-15"><a href="the-merton-model..html#cb131-15" aria-hidden="true" tabindex="-1"></a>          (sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT))) <span class="sc">-</span> sv <span class="sc">*</span> <span class="fu">sqrt</span>(TT)))</span>
<span id="cb131-16"><a href="the-merton-model..html#cb131-16" aria-hidden="true" tabindex="-1"></a>pd }</span></code></pre></div>
<p>Now we have a convenient function: <span class="math inline">\(pd = f(E_0, \sigma_E, rf, T, D)\)</span>. Remember these five parameters are required to estimate <span class="math inline">\(V_0\)</span> and <span class="math inline">\(\sigma_V\)</span> before calculating <span class="math inline">\(pd\)</span>.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="the-merton-model..html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the case of the textbook example.</span></span>
<span id="cb132-2"><a href="the-merton-model..html#cb132-2" aria-hidden="true" tabindex="-1"></a>pd1 <span class="ot">&lt;-</span> <span class="fu">pd</span>(<span class="dv">3</span>, <span class="fl">0.8</span>, <span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">10</span>)</span>
<span id="cb132-3"><a href="the-merton-model..html#cb132-3" aria-hidden="true" tabindex="-1"></a>pd1</span></code></pre></div>
<pre><code>## [1] 0.1269396</code></pre>
<p>Now, we create vectors of parameters and evaluate the function.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="the-merton-model..html#cb134-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">=</span> <span class="dv">50</span> <span class="co"># Vectors of length 50.</span></span>
<span id="cb134-2"><a href="the-merton-model..html#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create vectors of the parameters.</span></span>
<span id="cb134-3"><a href="the-merton-model..html#cb134-3" aria-hidden="true" tabindex="-1"></a>x.E <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">20</span>, <span class="at">length.out =</span> l)</span>
<span id="cb134-4"><a href="the-merton-model..html#cb134-4" aria-hidden="true" tabindex="-1"></a>x.rf <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="at">length.out =</span> l)</span>
<span id="cb134-5"><a href="the-merton-model..html#cb134-5" aria-hidden="true" tabindex="-1"></a>x.D <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">20</span>, <span class="at">length.out =</span> l)</span>
<span id="cb134-6"><a href="the-merton-model..html#cb134-6" aria-hidden="true" tabindex="-1"></a>x.T <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">20</span>, <span class="at">length.out =</span> l)</span>
<span id="cb134-7"><a href="the-merton-model..html#cb134-7" aria-hidden="true" tabindex="-1"></a>x.se <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="at">length.out =</span> l)</span>
<span id="cb134-8"><a href="the-merton-model..html#cb134-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the pd at different values.</span></span>
<span id="cb134-9"><a href="the-merton-model..html#cb134-9" aria-hidden="true" tabindex="-1"></a>pd.E <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, x.E, se, rf, TT, D)</span>
<span id="cb134-10"><a href="the-merton-model..html#cb134-10" aria-hidden="true" tabindex="-1"></a>pd.rf <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, x.rf, TT, D)</span>
<span id="cb134-11"><a href="the-merton-model..html#cb134-11" aria-hidden="true" tabindex="-1"></a>pd.D <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, TT, x.D)</span>
<span id="cb134-12"><a href="the-merton-model..html#cb134-12" aria-hidden="true" tabindex="-1"></a>pd.T <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, x.T, D)</span>
<span id="cb134-13"><a href="the-merton-model..html#cb134-13" aria-hidden="true" tabindex="-1"></a>pd.se <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, x.se, rf, TT, D)</span></code></pre></div>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="the-merton-model..html#cb135-1" aria-hidden="true" tabindex="-1"></a>pd.E <span class="co"># vemos que hay en pd.E</span></span></code></pre></div>
<pre><code>##  [1] 0.15540348 0.14901392 0.14320202 0.13768571 0.13261199 0.12764964
##  [7] 0.12308008 0.11884785 0.11459711 0.11076647 0.10703359 0.10358685
## [13] 0.10027904 0.09705949 0.09400846 0.09099382 0.08829345 0.08564796
## [19] 0.08301610 0.08064451 0.07827914 0.07603520 0.07387230 0.07173820
## [25] 0.06986438 0.06783357 0.06602684 0.06416119 0.06256656 0.06089248
## [31] 0.05923871 0.05772111 0.05624785 0.05480055 0.05342181 0.05206815
## [37] 0.05076260 0.04952178 0.04825154 0.04709231 0.04595749 0.04482100
## [43] 0.04375887 0.04272127 0.04173439 0.04072829 0.03984186 0.03887309
## [49] 0.03795462 0.03714601</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="the-merton-model..html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Busco el valor de pd mas parecido a 0.05</span></span>
<span id="cb137-2"><a href="the-merton-model..html#cb137-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">almost.equal</span>(pd.E, <span class="fl">0.05</span>, <span class="at">tolerance =</span> <span class="fl">0.01</span>))</span>
<span id="cb137-3"><a href="the-merton-model..html#cb137-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ??Que numero de observacion es? (da 38 con los datos del tutorial)</span></span>
<span id="cb137-4"><a href="the-merton-model..html#cb137-4" aria-hidden="true" tabindex="-1"></a>index</span></code></pre></div>
<pre><code>## [1] 38</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="the-merton-model..html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ??Que valor de equity me da una pd de 0.05?</span></span>
<span id="cb139-2"><a href="the-merton-model..html#cb139-2" aria-hidden="true" tabindex="-1"></a>x.E[index] <span class="co"># da 15.34694 con los datos del tutorial.</span></span></code></pre></div>
<pre><code>## [1] 15.34694</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="the-merton-model..html#cb141-1" aria-hidden="true" tabindex="-1"></a>pd.E[index] <span class="co"># da 0.04952178 con los datos del tutorial.</span></span></code></pre></div>
<pre><code>## [1] 0.04952178</code></pre>
<p>Let’s plot the probability of default as a function of equity. What we are doing here is to evaluate the probability of default function 50 times, as the <span class="math inline">\(E_0\)</span> has 50 values from 1 to 20. By doing this, we end up with 50 values of the probability of default.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="the-merton-model..html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x.E, pd.E, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Probability of default&quot;</span>, </span>
<span id="cb143-2"><a href="the-merton-model..html#cb143-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Equity at time zero&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))</span>
<span id="cb143-3"><a href="the-merton-model..html#cb143-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.E, pd.E)</span>
<span id="cb143-4"><a href="the-merton-model..html#cb143-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> E0, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb143-5"><a href="the-merton-model..html#cb143-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb143-6"><a href="the-merton-model..html#cb143-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(E0, pd1, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-58"></span>
<img src="index_files/figure-html/unnamed-chunk-58-1.png" alt="The probability of default as a function of the equity at time zero." width="672"  />
<p class="caption">
Figure 2.15: The probability of default as a function of the equity at time zero.
</p>
</div>
<p>These relationships between the parameters and the probability of default are all non-linear. This is interesting because according to the model, the current levels of the parameters are important when deciding which parameter might lead to a high or low impact over the probability of default.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="the-merton-model..html#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x.rf, pd.rf, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Probability of default&quot;</span>, </span>
<span id="cb144-2"><a href="the-merton-model..html#cb144-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Risk-free rate&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb144-3"><a href="the-merton-model..html#cb144-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb144-4"><a href="the-merton-model..html#cb144-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> rf, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb144-5"><a href="the-merton-model..html#cb144-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb144-6"><a href="the-merton-model..html#cb144-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(rf, pd1, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-59"></span>
<img src="index_files/figure-html/unnamed-chunk-59-1.png" alt="The probability of default as a function of the risk-free rate." width="672"  />
<p class="caption">
Figure 2.16: The probability of default as a function of the risk-free rate.
</p>
</div>
<p>Probability of default as a function of debt. Note that adding 1 or subtracting 1 unit of debt has different impact over the probability of default.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="the-merton-model..html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x.D, pd.D, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Probability of default&quot;</span>, </span>
<span id="cb145-2"><a href="the-merton-model..html#cb145-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))</span>
<span id="cb145-3"><a href="the-merton-model..html#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb145-4"><a href="the-merton-model..html#cb145-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> D, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb145-5"><a href="the-merton-model..html#cb145-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb145-6"><a href="the-merton-model..html#cb145-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(D, pd1, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-60"></span>
<img src="index_files/figure-html/unnamed-chunk-60-1.png" alt="The probability of default as a function of the debt." width="672"  />
<p class="caption">
Figure 2.17: The probability of default as a function of the debt.
</p>
</div>
<p>Probability of default as a function of maturity. Note that asking for a higher debt maturity (as in a negotiation), do not lead to a lower probability of default if we keep the rest of the parameters unchanged in our firm. Imagine we arrange a meeting with the bank manager and we ask for more time to pay our debt. The bank manager should not (in principle) extend the debt maturity as long as we commit to do some changes in the firm. For example, we can negotiate a longer maturity and promise to increase the firm’s equity.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="the-merton-model..html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x.T, pd.T, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Probability of default&quot;</span>, </span>
<span id="cb146-2"><a href="the-merton-model..html#cb146-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Maturity&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb146-3"><a href="the-merton-model..html#cb146-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb146-4"><a href="the-merton-model..html#cb146-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> TT, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb146-5"><a href="the-merton-model..html#cb146-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb146-6"><a href="the-merton-model..html#cb146-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(TT, pd1, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-61"></span>
<img src="index_files/figure-html/unnamed-chunk-61-1.png" alt="The probability of default as a function of the debt's maturity." width="672"  />
<p class="caption">
Figure 2.18: The probability of default as a function of the debt’s maturity.
</p>
</div>
<p>Probability of default as a function of the volatility of the equity <span class="math inline">\(\sigma_E\)</span>.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="the-merton-model..html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x.se, pd.se, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Probability of default&quot;</span>,</span>
<span id="cb147-2"><a href="the-merton-model..html#cb147-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Standard deviation of equity&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb147-3"><a href="the-merton-model..html#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb147-4"><a href="the-merton-model..html#cb147-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> se, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb147-5"><a href="the-merton-model..html#cb147-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb147-6"><a href="the-merton-model..html#cb147-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(se, pd1, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">cex =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-62"></span>
<img src="index_files/figure-html/unnamed-chunk-62-1.png" alt="The probability of default as a function of the volatility of the equity." width="672"  />
<p class="caption">
Figure 2.19: The probability of default as a function of the volatility of the equity.
</p>
</div>
<p>In the previous plots we evaluate the probability of default function by changing one of the following parameters: <span class="math inline">\(E_0\)</span>, <span class="math inline">\(\sigma_E\)</span>, <span class="math inline">\(rf\)</span>, <span class="math inline">\(T\)</span> or <span class="math inline">\(D\)</span>. We were able to do that because we constructed a vector of 50 different values for these five parameters. Note that <span class="math inline">\(V_0\)</span> and <span class="math inline">\(\sigma_V\)</span> do not remain fixed because they are at the same time a function of <span class="math inline">\(E_0\)</span>, <span class="math inline">\(\sigma_E\)</span>, <span class="math inline">\(rf\)</span>, <span class="math inline">\(T\)</span> and <span class="math inline">\(D\)</span>. Now, let’s start by plotting the probability of default as a function of <span class="math inline">\(E_0\)</span> and <span class="math inline">\(\sigma_E\)</span>.</p>
<p>One alternative is to evaluate the probability of default function 50 times by taking the 50 pairs of values of <span class="math inline">\(E_0\)</span> and <span class="math inline">\(\sigma_E\)</span>. By doing that, we will end with three vectors of size 50 that we can plot as a three dimension scatter plot.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="the-merton-model..html#cb148-1" aria-hidden="true" tabindex="-1"></a>ED <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, x.E, x.se, rf, TT, D)</span>
<span id="cb148-2"><a href="the-merton-model..html#cb148-2" aria-hidden="true" tabindex="-1"></a>p.ED <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(x.E, x.se, ED, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">color =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>, </span>
<span id="cb148-3"><a href="the-merton-model..html#cb148-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">angle =</span> <span class="dv">100</span>, <span class="at">xlab =</span> <span class="st">&quot;Equity at time zero&quot;</span>, </span>
<span id="cb148-4"><a href="the-merton-model..html#cb148-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">ylab =</span> <span class="st">&quot;Volatility of equity&quot;</span>, </span>
<span id="cb148-5"><a href="the-merton-model..html#cb148-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">zlab =</span> <span class="st">&quot;Probability of default&quot;</span>)</span>
<span id="cb148-6"><a href="the-merton-model..html#cb148-6" aria-hidden="true" tabindex="-1"></a>p.ED<span class="sc">$</span><span class="fu">points3d</span>(E0, se, pd1, <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">3</span>)  </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-63"></span>
<img src="index_files/figure-html/unnamed-chunk-63-1.png" alt="The probability of default as a function of the equity at time zero and the volatility of equity." width="672"  />
<p class="caption">
Figure 2.20: The probability of default as a function of the equity at time zero and the volatility of equity.
</p>
</div>
<p>The red point represent the case of the original textbook example in which <span class="math inline">\(pd = f(E_0=3, \sigma_E=0.8,rf=0.05,T=1,D=10)=0.1269396\)</span>. Note that the red point is not part of the 50 plotted observations simply because there is no case in which the probability of default function is evaluated in <span class="math inline">\(E_0=3, \sigma_E=0.8\)</span>. Although the plot above is not incorrect, it might be incomplete as we are not showing all possible values of the probability of default. One alternative to show a more complete plot is to evaluate all possible combinations of <span class="math inline">\(E_0\)</span> and <span class="math inline">\(\sigma_E\)</span> to evaluate the probability of default function. If we do that, we will have 50 values for <span class="math inline">\(E_0\)</span> and <span class="math inline">\(\sigma_E\)</span> that represent the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> axis, and a <span class="math inline">\(50 \times 50\)</span> matrix containing the probability of default. This allows us to plot a surface plot and a contour plot.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="the-merton-model..html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the empty matrix.</span></span>
<span id="cb149-2"><a href="the-merton-model..html#cb149-2" aria-hidden="true" tabindex="-1"></a>p_E_se <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> l, <span class="at">ncol =</span> l)</span>
<span id="cb149-3"><a href="the-merton-model..html#cb149-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill the empty matrix with probability of default values.</span></span>
<span id="cb149-4"><a href="the-merton-model..html#cb149-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span> l){ <span class="co"># Is there an easier way to do this?</span></span>
<span id="cb149-5"><a href="the-merton-model..html#cb149-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span> l){</span>
<span id="cb149-6"><a href="the-merton-model..html#cb149-6" aria-hidden="true" tabindex="-1"></a>    p_E_se[i,j] <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, x.E[i], x.se[j], rf, TT, D) } }</span></code></pre></div>
<p>Let’s plot the results.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="the-merton-model..html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot results.</span></span>
<span id="cb150-2"><a href="the-merton-model..html#cb150-2" aria-hidden="true" tabindex="-1"></a>p.ED1 <span class="ot">&lt;-</span> <span class="fu">persp</span>(x.E, x.se, p_E_se, <span class="at">zlab =</span> <span class="st">&quot;pd&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Equity at time zero&quot;</span>, </span>
<span id="cb150-3"><a href="the-merton-model..html#cb150-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">ylab =</span> <span class="st">&quot;Volatility of equity&quot;</span>, <span class="at">theta =</span> <span class="dv">60</span>, <span class="at">phi =</span> <span class="dv">10</span>, </span>
<span id="cb150-4"><a href="the-merton-model..html#cb150-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">expand =</span>  <span class="fl">0.5</span>, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>, <span class="at">shade =</span> <span class="fl">0.2</span>, </span>
<span id="cb150-5"><a href="the-merton-model..html#cb150-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">ticktype =</span> <span class="st">&quot;detailed&quot;</span>) </span>
<span id="cb150-6"><a href="the-merton-model..html#cb150-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the original pd value as in the textbook example.</span></span>
<span id="cb150-7"><a href="the-merton-model..html#cb150-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">trans3d</span>(E0, se, pd1, p.ED1), <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-65"></span>
<img src="index_files/figure-html/unnamed-chunk-65-1.png" alt="The probability of default as a function of the equity at time zero and the volatility of equity: A plane or surface view." width="672"  />
<p class="caption">
Figure 2.21: The probability of default as a function of the equity at time zero and the volatility of equity: A plane or surface view.
</p>
</div>
<p>Now the plot becomes a plane. A contour plot simplify the reading of a three dimension plot by reducing it into two dimensions: <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> coordinates. The value of the probability of default is represented by the contour lines.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="the-merton-model..html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(x.E, x.se, p_E_se, <span class="at">xlab =</span> <span class="st">&quot;Equity at time zero&quot;</span>, </span>
<span id="cb151-2"><a href="the-merton-model..html#cb151-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Volatility of equity&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb151-3"><a href="the-merton-model..html#cb151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(E0, se, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-66"></span>
<img src="index_files/figure-html/unnamed-chunk-66-1.png" alt="The probability of default as a function of the equity at time zero and the volatility of equity: A contour view." width="672"  />
<p class="caption">
Figure 2.22: The probability of default as a function of the equity at time zero and the volatility of equity: A contour view.
</p>
</div>
<p>The blue point is the original case. Note that the value is slightly higher than 0.1, which is consistent with the <span class="math inline">\(pd=0.1269396\)</span>.</p>
</div>
<div id="got-capital-structure." class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> GoT: capital structure.<a href="the-merton-model..html#got-capital-structure." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The problem. Daenerys Targaryen owns a big manufacturing firm that produces fire extinguishers. Surprisingly, the firm data corresponds exactly as the data in the example 24.3. She is planning to ask the Iron Bank of Braavos for a loan using the peaceful civilized way (without dragons). However, she would like to reduce the probability of default of the firm first, in that way she might negotiate better credit conditions. Daenerys has some understanding about very basic finance because she knows that she could either reduce the debt, or increase the capital in order to reduce the probability of default. Doing both alternatives at the same time is clearly more expensive so she is not very keen about it.</p>
<p>What is the best strategy to reduce the probability of default? Reduce the debt by 2 or increase the capital by 2?</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="the-merton-model..html#cb152-1" aria-hidden="true" tabindex="-1"></a>D.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">13</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb152-2"><a href="the-merton-model..html#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate pd function: E0 changes from 1 to 5; debt goes from 0 to 13.</span></span>
<span id="cb152-3"><a href="the-merton-model..html#cb152-3" aria-hidden="true" tabindex="-1"></a>E1 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, <span class="dv">1</span>, se, rf, TT, D.seq)</span>
<span id="cb152-4"><a href="the-merton-model..html#cb152-4" aria-hidden="true" tabindex="-1"></a>E2 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, <span class="dv">2</span>, se, rf, TT, D.seq)</span>
<span id="cb152-5"><a href="the-merton-model..html#cb152-5" aria-hidden="true" tabindex="-1"></a>E3 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, <span class="dv">3</span>, se, rf, TT, D.seq)</span>
<span id="cb152-6"><a href="the-merton-model..html#cb152-6" aria-hidden="true" tabindex="-1"></a>E4 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, <span class="dv">4</span>, se, rf, TT, D.seq)</span>
<span id="cb152-7"><a href="the-merton-model..html#cb152-7" aria-hidden="true" tabindex="-1"></a>E5 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, <span class="dv">5</span>, se, rf, TT, D.seq)</span></code></pre></div>
<p>Plot the results.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="the-merton-model..html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We use these vectors for colors and legends in the following plots.</span></span>
<span id="cb153-2"><a href="the-merton-model..html#cb153-2" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;green&quot;</span>, <span class="st">&quot;purple&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>)</span>
<span id="cb153-3"><a href="the-merton-model..html#cb153-3" aria-hidden="true" tabindex="-1"></a>leg <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;E0=1&quot;</span>, <span class="st">&quot;E0=2&quot;</span>, <span class="st">&quot;E0=3 (initial value)&quot;</span>, <span class="st">&quot;E0=4&quot;</span>, <span class="st">&quot;E0=5&quot;</span>)</span>
<span id="cb153-4"><a href="the-merton-model..html#cb153-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot.</span></span>
<span id="cb153-5"><a href="the-merton-model..html#cb153-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D.seq, E1, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>,</span>
<span id="cb153-6"><a href="the-merton-model..html#cb153-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt value. Initially, D=10&quot;</span>,</span>
<span id="cb153-7"><a href="the-merton-model..html#cb153-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability of default. Initially PD=12.69%&quot;</span>)</span>
<span id="cb153-8"><a href="the-merton-model..html#cb153-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E2, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb153-9"><a href="the-merton-model..html#cb153-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E3, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb153-10"><a href="the-merton-model..html#cb153-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E4, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb153-11"><a href="the-merton-model..html#cb153-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E5, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb153-12"><a href="the-merton-model..html#cb153-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> D, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb153-13"><a href="the-merton-model..html#cb153-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb153-14"><a href="the-merton-model..html#cb153-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> leg, <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">5</span>), <span class="at">col =</span> colors, </span>
<span id="cb153-15"><a href="the-merton-model..html#cb153-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>)</span>
<span id="cb153-16"><a href="the-merton-model..html#cb153-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(D, pd1, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-68"></span>
<img src="index_files/figure-html/unnamed-chunk-68-1.png" alt="GoT problem. Probability of default and capital structure." width="672"  />
<p class="caption">
Figure 2.23: GoT problem. Probability of default and capital structure.
</p>
</div>
<p>Let’s illustrate the alternatives as clear as possible.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="the-merton-model..html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D.seq, E1, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>,</span>
<span id="cb154-2"><a href="the-merton-model..html#cb154-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt value. Initially, D=10&quot;</span>,</span>
<span id="cb154-3"><a href="the-merton-model..html#cb154-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability of default. Initially PD=12.69%&quot;</span>)</span>
<span id="cb154-4"><a href="the-merton-model..html#cb154-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E2, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb154-5"><a href="the-merton-model..html#cb154-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E3, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb154-6"><a href="the-merton-model..html#cb154-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E4, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb154-7"><a href="the-merton-model..html#cb154-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E5, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb154-8"><a href="the-merton-model..html#cb154-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> D, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb154-9"><a href="the-merton-model..html#cb154-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">8</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb154-10"><a href="the-merton-model..html#cb154-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> pd1, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb154-11"><a href="the-merton-model..html#cb154-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, TT, <span class="dv">8</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb154-12"><a href="the-merton-model..html#cb154-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(<span class="dv">5</span>, se, rf, TT, D), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb154-13"><a href="the-merton-model..html#cb154-13" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> leg, <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">5</span>), <span class="at">col =</span> colors, </span>
<span id="cb154-14"><a href="the-merton-model..html#cb154-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>)</span>
<span id="cb154-15"><a href="the-merton-model..html#cb154-15" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(D, pd1, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb154-16"><a href="the-merton-model..html#cb154-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(D, <span class="fu">pd</span>(<span class="dv">5</span>, se, rf, TT, D), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb154-17"><a href="the-merton-model..html#cb154-17" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">8</span>, <span class="fu">pd</span>(<span class="dv">3</span>, se, rf, TT, <span class="dv">8</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;yellow&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-69"></span>
<img src="index_files/figure-html/unnamed-chunk-69-1.png" alt="GoT solution. Probability of default and capital structure." width="672"  />
<p class="caption">
Figure 2.24: GoT solution. Probability of default and capital structure.
</p>
</div>
<p>Consider a different initial situation. Now, <span class="math inline">\(E_0=2\)</span> and <span class="math inline">\(D=2\)</span> and the rest remains the same. In this case, the probability of default is now 7.13%. What is the best strategy to reduce the probability of default? Reduce the debt by 1 or increase the capital by 1?</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="the-merton-model..html#cb155-1" aria-hidden="true" tabindex="-1"></a>leg2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;E0=1&quot;</span>, <span class="st">&quot;E0=2 (initial value)&quot;</span>, <span class="st">&quot;E0=3&quot;</span>, <span class="st">&quot;E0=4&quot;</span>, <span class="st">&quot;E0=5&quot;</span>)</span>
<span id="cb155-2"><a href="the-merton-model..html#cb155-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb155-3"><a href="the-merton-model..html#cb155-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D.seq, E1, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>,</span>
<span id="cb155-4"><a href="the-merton-model..html#cb155-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt value. Initially, D=2&quot;</span>,</span>
<span id="cb155-5"><a href="the-merton-model..html#cb155-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability of default. Initially PD=7.13%&quot;</span>, </span>
<span id="cb155-6"><a href="the-merton-model..html#cb155-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.08</span>))</span>
<span id="cb155-7"><a href="the-merton-model..html#cb155-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E2, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb155-8"><a href="the-merton-model..html#cb155-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E3, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb155-9"><a href="the-merton-model..html#cb155-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E4, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb155-10"><a href="the-merton-model..html#cb155-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E5, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb155-11"><a href="the-merton-model..html#cb155-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb155-12"><a href="the-merton-model..html#cb155-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(<span class="dv">2</span>, se, rf, TT, <span class="dv">2</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb155-13"><a href="the-merton-model..html#cb155-13" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> leg2, <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">5</span>), <span class="at">col =</span> colors, </span>
<span id="cb155-14"><a href="the-merton-model..html#cb155-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span>
<span id="cb155-15"><a href="the-merton-model..html#cb155-15" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">2</span>, <span class="fu">pd</span>(<span class="dv">2</span>, se, rf, TT, <span class="dv">2</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-70"></span>
<img src="index_files/figure-html/unnamed-chunk-70-1.png" alt="GoT problem 2. Probability of default and capital structure." width="672"  />
<p class="caption">
Figure 2.25: GoT problem 2. Probability of default and capital structure.
</p>
</div>
<p>The solution can be illustrated as follows:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="the-merton-model..html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D.seq, E1, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>,</span>
<span id="cb156-2"><a href="the-merton-model..html#cb156-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt value. Initially, D=2&quot;</span>,</span>
<span id="cb156-3"><a href="the-merton-model..html#cb156-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability of default. Initially PD=7.13%&quot;</span>, </span>
<span id="cb156-4"><a href="the-merton-model..html#cb156-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.08</span>))</span>
<span id="cb156-5"><a href="the-merton-model..html#cb156-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E2, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb156-6"><a href="the-merton-model..html#cb156-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E3, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb156-7"><a href="the-merton-model..html#cb156-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E4, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb156-8"><a href="the-merton-model..html#cb156-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, E5, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb156-9"><a href="the-merton-model..html#cb156-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb156-10"><a href="the-merton-model..html#cb156-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb156-11"><a href="the-merton-model..html#cb156-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(<span class="dv">2</span>, se, rf, TT, <span class="dv">2</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb156-12"><a href="the-merton-model..html#cb156-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(<span class="dv">2</span>, se, rf, TT, <span class="dv">1</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb156-13"><a href="the-merton-model..html#cb156-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, TT, <span class="dv">2</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb156-14"><a href="the-merton-model..html#cb156-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> leg2, <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">5</span>), <span class="at">col =</span> colors, </span>
<span id="cb156-15"><a href="the-merton-model..html#cb156-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span>
<span id="cb156-16"><a href="the-merton-model..html#cb156-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">2</span>, <span class="fu">pd</span>(<span class="dv">2</span>, se, rf, TT, <span class="dv">2</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>)</span>
<span id="cb156-17"><a href="the-merton-model..html#cb156-17" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, <span class="fu">pd</span>(<span class="dv">2</span>, se, rf, TT, <span class="dv">1</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;yellow&quot;</span>)</span>
<span id="cb156-18"><a href="the-merton-model..html#cb156-18" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">2</span>, <span class="fu">pd</span>(E0, se, rf, TT, <span class="dv">2</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-71"></span>
<img src="index_files/figure-html/unnamed-chunk-71-1.png" alt="GoT solution 2. Probability of default and capital structure." width="672"  />
<p class="caption">
Figure 2.26: GoT solution 2. Probability of default and capital structure.
</p>
</div>
<p>Interesting.</p>
<p>Consider a third problem. In a parallel universe, Daenerys Targaryen’s firm has some liquidity short-term troubles. She needs either more cash now or some more time to pay her current debt. She would like to know which alternative leads to the lowest increase of the probability of default. Add $2 more to her current debt, or ask for a half year more time to pay her current debt?</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="the-merton-model..html#cb157-1" aria-hidden="true" tabindex="-1"></a>T1 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, <span class="fl">0.5</span>, D.seq)</span>
<span id="cb157-2"><a href="the-merton-model..html#cb157-2" aria-hidden="true" tabindex="-1"></a>T2 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, <span class="dv">1</span>, D.seq)</span>
<span id="cb157-3"><a href="the-merton-model..html#cb157-3" aria-hidden="true" tabindex="-1"></a>T3 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, <span class="fl">1.5</span>, D.seq)</span>
<span id="cb157-4"><a href="the-merton-model..html#cb157-4" aria-hidden="true" tabindex="-1"></a>T4 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, <span class="dv">2</span>, D.seq)</span>
<span id="cb157-5"><a href="the-merton-model..html#cb157-5" aria-hidden="true" tabindex="-1"></a>T5 <span class="ot">&lt;-</span> <span class="fu">mapply</span>(pd, E0, se, rf, <span class="fl">2.5</span>, D.seq)</span></code></pre></div>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="the-merton-model..html#cb158-1" aria-hidden="true" tabindex="-1"></a>leg3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;T=2.5&quot;</span>, <span class="st">&quot;T=2&quot;</span>, <span class="st">&quot;T=1.5&quot;</span>, <span class="st">&quot;T=1&quot;</span>, <span class="st">&quot;T=0.5&quot;</span>)</span>
<span id="cb158-2"><a href="the-merton-model..html#cb158-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-3"><a href="the-merton-model..html#cb158-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D.seq, T5, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>,</span>
<span id="cb158-4"><a href="the-merton-model..html#cb158-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt value. Initially, D=6&quot;</span>,</span>
<span id="cb158-5"><a href="the-merton-model..html#cb158-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability of default. Initially PD=20.33%&quot;</span>)</span>
<span id="cb158-6"><a href="the-merton-model..html#cb158-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T4, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb158-7"><a href="the-merton-model..html#cb158-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T3, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb158-8"><a href="the-merton-model..html#cb158-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T2, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb158-9"><a href="the-merton-model..html#cb158-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T1, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb158-10"><a href="the-merton-model..html#cb158-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">6</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb158-11"><a href="the-merton-model..html#cb158-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">6</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb158-12"><a href="the-merton-model..html#cb158-12" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> leg3, <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">5</span>), <span class="at">col =</span> colors, </span>
<span id="cb158-13"><a href="the-merton-model..html#cb158-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>)</span>
<span id="cb158-14"><a href="the-merton-model..html#cb158-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">6</span>, <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">6</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-73"></span>
<img src="index_files/figure-html/unnamed-chunk-73-1.png" alt="GoT problem 3. More debt or longer maturity?" width="672"  />
<p class="caption">
Figure 2.27: GoT problem 3. More debt or longer maturity?
</p>
</div>
<p>Let’s visualize the result.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="the-merton-model..html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(D.seq, T5, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>,</span>
<span id="cb159-2"><a href="the-merton-model..html#cb159-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Debt value. Initially, D=6&quot;</span>,</span>
<span id="cb159-3"><a href="the-merton-model..html#cb159-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Probability of default. Initially PD=20.33%&quot;</span>)</span>
<span id="cb159-4"><a href="the-merton-model..html#cb159-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T4, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb159-5"><a href="the-merton-model..html#cb159-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T3, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb159-6"><a href="the-merton-model..html#cb159-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T2, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb159-7"><a href="the-merton-model..html#cb159-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(D.seq, T1, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb159-8"><a href="the-merton-model..html#cb159-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">6</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb159-9"><a href="the-merton-model..html#cb159-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">8</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb159-10"><a href="the-merton-model..html#cb159-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">6</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb159-11"><a href="the-merton-model..html#cb159-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, <span class="dv">2</span>, <span class="dv">6</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb159-12"><a href="the-merton-model..html#cb159-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">6</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb159-13"><a href="the-merton-model..html#cb159-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">8</span>), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb159-14"><a href="the-merton-model..html#cb159-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend =</span> leg3, <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">5</span>), <span class="at">col =</span> colors, </span>
<span id="cb159-15"><a href="the-merton-model..html#cb159-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">bg =</span> <span class="st">&quot;white&quot;</span>)</span>
<span id="cb159-16"><a href="the-merton-model..html#cb159-16" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">6</span>, <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">6</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb159-17"><a href="the-merton-model..html#cb159-17" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">8</span>, <span class="fu">pd</span>(E0, se, rf, <span class="fl">1.5</span>, <span class="dv">8</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;yellow&quot;</span>)</span>
<span id="cb159-18"><a href="the-merton-model..html#cb159-18" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">6</span>, <span class="fu">pd</span>(E0, se, rf, <span class="dv">2</span>, <span class="dv">6</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-74"></span>
<img src="index_files/figure-html/unnamed-chunk-74-1.png" alt="GoT answer 3. More debt or longer maturity?" width="672"  />
<p class="caption">
Figure 2.28: GoT answer 3. More debt or longer maturity?
</p>
</div>
<p>You are expected to discuss the results and implications.</p>
<div style="page-break-after: always;"></div>
</div>
</div>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3RFWK4ZPH8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-3RFWK4ZPH8');
</script>
            </section>

          </div>
        </div>
      </div>
<a href="loan-analysis..html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-gaussian-copula-model..html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
